### ISSUE TITLE
pipenv: error: no such option: --upgrade

### ISSUE THREAD

**Issue by kafejo** [kennethreitz/pipenv#1056]
Getting an no such option error with every install command.

##### Describe your environment

1. MacOS High Sierra
1. Python version: 2.7
1. Pipenv version: 8.3.2

##### Expected result

Just install the package

##### Actual result

```
$ pipenv install --verbose
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Usage: pipenv [options]

Traceback (most recent call last):
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/bin/pipenv", line 9, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 1866, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy, pre=pre)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 1330, in do_init
    do_lock(system=system, pre=pre)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 1121, in do_lock
    pre=pre
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/utils.py", line 426, in resolve_deps
    constraint = [c for c in pip.req.parse_requirements(t, session=pip._vendor.requests)][0]
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/patched/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/patched/pip/req/req_file.py", line 140, in process_line
    opts, _ = parser.parse_args(shlex.split(options_str), defaults)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/patched/pip/req/req_file.py", line 284, in parser_exit
    raise RequirementsFileParseError(msg)
pip.exceptions.RequirementsFileParseError: pipenv: error: no such option: --upgrade
```

##### Steps to replicate

It started when I run by mistake `pipenv install [package] --upgrade`.

**Comment by kafejo** [comment]
Ah. It added the `--upgrade` into my Pipfile as a dependency…
```
--upgrade = "*"
```
Just deleted it and it works. Weird error though.

**Comment by techalchemy** [comment]
yeah it got passed to the requirements parser as a requirement (since you told it to install a package), and the parser failed to parse that option since it isnn't one 

definitely shouldn't have been added to the pipfile though!
