### ISSUE TITLE
RuntimeError: No stable configuration of concrete packages could be found for the given constraints after 16 rounds of resolving.

### ISSUE THREAD

**Issue by kafejo** [kennethreitz/pipenv#1057]
RuntimeError: No stable configuration of concrete packages could be found for the given constraints after 16 rounds of resolving.

When `pipenv install google-cloud`

##### Describe your environment

1. MacOS High Sierra
1. Python version: 2.7
1. Pipenv version: 8.3.2

##### Expected result

To install it.

##### Actual result

```
Adding google-cloud to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/bin/pipenv", line 9, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 1935, in install
    do_lock(system=system, pre=pre)
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 1121, in do_lock
    pre=pre
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/utils.py", line 461, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/Users/aleskocur-rubicoin/Library/Python/2.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 98, in resolve
    'This is likely a bug.' % max_rounds)
RuntimeError: No stable configuration of concrete packages could be found for the given constraints after 16 rounds of resolving.
This is likely a bug.
```

##### Steps to replicate

run `pipenv install google-cloud`

**Comment by vphilippon** [comment]
Hi @kafejo, thanks for using `pipenv`.

I'll need the output of `pipenv lock --verbose --clear` to take a look at what's going on.

**Comment by techalchemy** [comment]
@kafejo also please make sure you have set `LANG` and `LC_ALL` to a proper utf-8 compatible setting on your terminal (this is a known issue with mac) as this may resolve any issue you encounter

**Comment by brett-miller** [comment]
I'm debugging similar issues with another package so I tested this issue and found the same problem, however @techalchemy's suggestion resolved the issue.

- Mac Sierra (10.12.6)
- pipenv  8.3.2
- python 2.7 (Mac's default build)
- `LANG=en_US.UTF-8`
- `LC_ALL=`

**Repro**
```
pipenv install google-cloud
...
RuntimeError: No stable configuration of concrete packages could be found for the given constraints after 16 rounds of resolving.
This is likely a bug.
```

**Then set LC_ALL**

```
export LC_ALL=en_US.UTF-8
pipenv install google-cloud
...
Adding google-cloud to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (######)!
```

**Then unset LC_ALL and installed with python3**

```
export LC_ALL=
pipenv --three install google-cloud
...
Adding google-cloud to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (######)!
```

**Comment by sourcec0de** [comment]
Really loving `pipenv`.

I wasn't able to get past this using the instructions above.
It only seemed to work after installing the dependencies and then running `pipenv lock` after.

1. `pipenv install --skip-locked`
2. `pipenv lock --verbose --clear`
