### ISSUE TITLE
pipenv doesn't like non-writable home directory

### ISSUE THREAD

**Issue by astronouth7303** [kennethreitz/pipenv#1061]
I tried running `pipenv` on debian under the `www-data` user, which has the configured home directory of `/var/www`, which isn't actually writable by `www-data`.

This produces errors like:

```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1626, in cli
    if need_update_check():
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 962, in need_update_check
    mkdir_p(PIPENV_CACHE_DIR)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 750, in mkdir_p
    mkdir_p(head)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 752, in mkdir_p
    os.mkdir(newdir)
PermissionError: [Errno 13] Permission denied: '/var/www/.cache'
```

(Set `PIPENV_CACHE_DIR` in the environment to `/tmp/pipenv-cache`)

```
Virtualenv location: 
Creating a virtualenv for this project…
Running virtualenv with interpreter /usr/bin/python2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 946, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1157, in install_python
    mkdir(lib_dir)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 329, in mkdir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/www/.local'
Error while trying to remove the /var/www/.local/share/virtualenvs/paa-SPp5mrC7 env: 
No such file or directory
```

(At this point, I decided to just give the application its own user, which did work.)

In general, I'm trying to use pipenv in production.

##### Describe your environment

1. Debian stretch
1. Python 3.5.3 (using `pipenv --three`)
1. Pipenv 8.3.2

**Comment by techalchemy** [comment]
@astronouth7303 `Pipenv` is a dependency manager and virtualenv manager, that means it installs things and manipulates the environment using virtualenvs and `pip`, python's package manager.  That means it needs permission to do that and you need to tell it where it can operate (by setting `WORKON_HOME` so it knows where to put virtualenv directories, It would be kind of pointless if it can't install the dependencies it is managing :)

Generally speaking it's hard to tell you how to allocate permissions to whatever application you're trying to use, but if your applicaiton is using `/var/www` as its project root (and that is where your `Pipfile` lives, the presumably it should have read/write access to that directory.  It would be unusual for something that runs out of that path as a root directory to not be able to write to the same path (e.g. logs, data, etc)

**Comment by techalchemy** [comment]
Oh I see you are running pipenv as *www-data* -- that is probably a bad idea

**Comment by astronouth7303** [comment]
Ok, so what's the correct way to:

1. Develop using pipfiles
2. Deploy to a server and set up the appropriate venv based on the pipfile
3. Run the service in the pipfile-based venv in a limited user

**Comment by astronouth7303** [comment]
Not having the application user being able to write its own code is _extremely_ common. Logs are in `/var/log/app`, managed by the service manager (eg stdout -> supervisord), and data is kept in a database (SQL etc), object store (S3), or just in a writable directory.

It's a standard security recommendation to keep deployed code separate from writable data directories.

**Comment by techalchemy** [comment]
@astronouth7303 nobody is disputing that. The normal arrangement for this is to use a user account and tell the webserver where it is, not to store and run it in `/var/www`.  This isn't the right place to talk about how to structure your server permissions, the bottom line is that pipenv needs to be told where to store and access virtualenvs and it needs to have access to write to those directories.

This is obvious.  If you want to install packages, you need to have write access to install them.  I'm going to close this because it is not an issue with pipenv.
