### ISSUE TITLE
 Failed building wheel for pyyaml in Python 3.6.3

### ISSUE THREAD

**Issue by franchb** [kennethreitz/pipenv#1062]
Failed building wheel for pyyaml

##### Describe your environment

1. OS Type: Linux Mint 17.3 (Ubuntu 16.04)
1. Python version: **3.6.3**
1. Pipenv version: **8.3.2**

##### Expected result

`pipenv install` to be performed with a good result

##### Actual result

```
Command "/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/bin/python3.6m -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7hz0sdbc/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2l01koac-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/site/python3.6/pyyaml" failed with error code 1 in /tmp/pip-build-7hz0sdbc/pyyaml/
```

```
  checking if libyaml is compilable
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/python3.6m -c build/temp.linux-x86_64-3.6/check_libyaml.c -o build/temp.linux-x86_64-3.6/check_libyaml.o
  checking if libyaml is linkable
  x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-3.6/check_libyaml.o -lyaml -o build/temp.linux-x86_64-3.6/check_libyaml
  building '_yaml' extension
  creating build/temp.linux-x86_64-3.6/ext
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/python3.6m -c ext/_yaml.c -o build/temp.linux-x86_64-3.6/ext/_yaml.o
  ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
```

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Pipfile:

```
...
[requires]

python_full_version = "3.6.3"
...
[dev-packages]

awscli = "*"
"flake8" = "*"
"autopep8" = "*"
ipython = "*"
```

Next `pipenv install`

**Comment by vphilippon** [comment]
First of all, just to avoid looking for an issue at the wrong place, can you confirm that `pip install pyyaml` works on your setup?

Then, I've noted the example `Pipfile` to replicate you gave does not end up installing `pyyaml`. Was your next command `pipenv install pyyaml`, or have you forgotten a part of your `Pipfile`?

**Comment by franchb** [comment]
Yes, of course, I first checked the duplicate. I'm still the beginner so maybe don't understand the `pipenv` process deeply. But there definitely is some issue with `pyyaml` and Python 3.6.3.

So I will put here now all verbose output.

```
Collecting pyyaml==3.12 
  1 location(s) to search for versions of pyyaml:
  * https://pypi.python.org/simple/pyyaml/
  Getting page https://pypi.python.org/simple/pyyaml/
  Looking up "https://pypi.python.org/simple/pyyaml/" in the cache
  Current age based on date: 178
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 178
  Analyzing links from page https://pypi.python.org/simple/pyyaml/
    Found link https://pypi.python.org/packages/00/17/3b822893a1789a025d3f676a381338516a8f65e686d915b0834ecc9b4979/PyYAML-3.10.tar.gz#md5=74c94a383886519e9e7b3dd1ee540247 (from https://pypi.python.org/simple/pyyaml/), version: 3.10
    Found link https://pypi.python.org/packages/04/60/abfb3a665ee0569b60c89148b7187ddd8a36cb65e254fba945ae1315645d/PyYAML-3.11.zip#md5=89cbc92cda979042533b640b76e6e055 (from https://pypi.python.org/simple/pyyaml/), version: 3.11
    Skipping link https://pypi.python.org/packages/0b/13/eb09da839a8c8b3be81322b0a5f546e0f549e06c774350e34e38f797893e/PyYAML-3.12-cp27-cp27m-win32.whl#md5=f12d8328a19ad25ca1cc6baba576b9da (from https://pypi.python.org/simple/pyyaml/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/13/9f/d065366ee3733cc35d7b955e3e0c185e52098f1e2ddeb9a944187141bf9b/PyYAML-3.11.win32-py3.1.exe#md5=1b3b956bbe638c50eb80273b639be692 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/13/f2/9f13805a9b7eaeaf0a4406a3decba7ed1bc834e5e4b07bdbd8699f4f6034/PyYAML-3.12-cp35-cp35m-win_amd64.whl#md5=8c1cd6270280967ca713d96b82fd4091 (from https://pypi.python.org/simple/pyyaml/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/17/5f/fa55c61560ba9e7eda66b7847ae0a0fdaf1c51dcb9dddde5befa54ea9eab/PyYAML-3.10.win32-py3.1.exe#md5=6c830441d9df703458e2f34c2e6a413a (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/23/65/4d170a802b35e27d295e6168e3db339e220ca207df71c766166beb90751b/PyYAML-3.12.win-amd64-py3.5.exe#md5=a771f67088b43725ae6694b59320400d (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/33/eb/e73b546cb82e24bd8ca30aa8c57d3a7d13294039592a5df980089a913ffa/PyYAML-3.10.win32-py3.0.exe#md5=0360710722fdc58e519d6a76324aa1d7 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/35/ed/37bf4758d977a7440a2b1538e44b0fc5992e3726d12aebbb41d79794241d/PyYAML-3.11.win32-py3.2.exe#md5=b40a15302b494d0bcc79568ff38ab43c (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz#md5=4c129761b661d181ebf7ff4eb2d79950 (from https://pypi.python.org/simple/pyyaml/), version: 3.12
    Skipping link https://pypi.python.org/packages/54/73/948e534e63f338a382737364a2c5ce89792478a11bae3cff1bf5e42897ee/PyYAML-3.12-cp27-cp27m-win_amd64.whl#md5=0a48252d96ba9af8cf6fdddb3bfb390f (from https://pypi.python.org/simple/pyyaml/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/58/ef/05f956add22b886f5f5fbcc42d006bfb171782ccf765ef2694ca301912c9/PyYAML-3.11.win-amd64-py3.2.exe#md5=328bfd749ee42279b9d8a75397e9444d (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/59/ba/a764604baa98a4d4a5a9d64c28c4e37758be0592905a20f730288e437b4b/PyYAML-3.10.win32-py3.2.exe#md5=fc582f2f46f6494a97c9cae938a19f59 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/63/45/107cbbbf40ab721b07b5b73a6bd62a4cdf2f2c0be197b7780a8fb806a53a/PyYAML-3.12-cp34-cp34m-win_amd64.whl#md5=ded3dd616cb77a02cb3a6b2b84c61ea2 (from https://pypi.python.org/simple/pyyaml/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/69/2f/73448cf6a52cebe584da7a44fec19044e0d9e9b193f3b50d6f80d87361c6/PyYAML-3.11.win32-py3.3.exe#md5=c3990781cc999744cd21df473068f388 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/6b/f0/a0250248ea260d55748fff586d89a32afbb22656f4498b08d2636a48d4ec/PyYAML-3.12.zip#md5=aa5e762e79b19bb80dbcf04f82178832 (from https://pypi.python.org/simple/pyyaml/), version: 3.12
    Found link https://pypi.python.org/packages/75/5e/b84feba55e20f8da46ead76f14a3943c8cb722d40360702b2365b91dec00/PyYAML-3.11.tar.gz#md5=f50e08ef0fe55178479d3a618efe21db (from https://pypi.python.org/simple/pyyaml/), version: 3.11
    Skipping link https://pypi.python.org/packages/77/a9/92e09914e3d7768b0cab5a5432d019be393df50e89b284ad1c67562dcbdd/PyYAML-3.11.win-amd64-py2.7.exe#md5=538cd92d63068161d229cb8a65db7f23 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/79/1a/1a5ac6111ec2586ee2cc689e8e587222b0be25b65e9fbfa086569210bb78/PyYAML-3.11.win-amd64-py2.6.exe#md5=af7eade45dcb408473928953f430e7db (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/9f/41/6e6ca6b982aecc8ecd3e833590de9dae85ce542c581985c11a8b52106e6a/PyYAML-3.11.win-amd64-py3.4.exe#md5=0dfcdae003642dfdfb49d5f16ff63717 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/a1/8b/c2fbad63a8022278fded695d29002b0ddb7aa0dc1fc4424df16eb64b44c7/PyYAML-3.10.win32-py2.7.exe#md5=73309e5fe73d7d84e0af3213b2c957ff (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/a3/56/e9c29363f8c70c0117fd583ad98f4cacc13cd9d261ec77435929a0215659/PyYAML-3.12.win32-py3.4.exe#md5=6bc4685063e241f97615a4f5294c1fb9 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/a5/55/47bf6e4a09a889db739b1ae02b05d5a2c1d7792aca14078728887f41815c/PyYAML-3.11.win32-py2.7.exe#md5=d75320c7a904731d6e27418e346a92e1 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/a5/de/23cad8dafd6439e4439f50cb6f08abefb92fa0c3addab579e76e4b5e5db6/PyYAML-3.12.win32-py3.5.exe#md5=52c98a791fa57ab312dd4fd25ffb7443 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/a7/fc/348f24960dd7363bb54b541fc2d10cd3a87e65680bcdf08d66ad7a0f511d/PyYAML-3.11.win32-py2.6.exe#md5=83b0f47825feac2da99b75bfbd65a3ab (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/aa/c9/a36ebedc2128c4a371258b03ae84ee1268a797cd206a55fce472eaa71b6d/PyYAML-3.12.win-amd64-py3.4.exe#md5=61abc1ef5a186e6b36e5fb4b8e6c8700 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/af/98/94fb3e555d1f8c6664c3080d71bbe1af74d90029ea99ef5aea8fd5b36c29/PyYAML-3.11.win-amd64-py3.3.exe#md5=672275294ababb18794b328a24c836b4 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/af/be/a0b2db944133c832bc094960850f4129f1180d341fe1660b72d80b806ecc/PyYAML-3.12.win-amd64-py2.7.exe#md5=49e84078efd63701336f667b76d3d7bb (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/b5/3f/658f63e3cc92d1ffe189297f75088a45c5cdd0c1e1c5b373d762e147bc89/PyYAML-3.12-cp34-cp34m-win32.whl#md5=9d72fa8128e01a03a39bcf4e4a5b83f2 (from https://pypi.python.org/simple/pyyaml/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/cf/e2/3567dec97968e36c027aa5143016c211c8f02e4cbaf1155f1223671dae55/PyYAML-3.10.win32-py2.5.exe#md5=dfb573ab41cdfee1b2794b7a155e72e6 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/da/82/435334c350fc480e598301521f86d7bfbdc436341a674b4076cdf2812d1f/PyYAML-3.10.win32-py2.6.exe#md5=4c1a374cb89fa0ff43f3b94b5692edd9 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/dc/69/1fe8dee4728e69aae332c9f4edf356e4dd59a4a5f95bf910ab4c0210d6a3/PyYAML-3.12.win32-py2.7.exe#md5=5dcf1a3d92ec480e6d4612069858ebaf (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/e4/a4/6c1f6c989d97c62ea50329b3803ca214ccfed7e4c1f82fe30c6e048645a0/PyYAML-3.10.zip#md5=b1a2b30cdf481da4249c917c3307f129 (from https://pypi.python.org/simple/pyyaml/), version: 3.10
    Skipping link https://pypi.python.org/packages/f5/34/e557935bbd64db72b9cc20ab71ddce508556bfe7074d2494e063d0f0e19e/PyYAML-3.11.win32-py3.4.exe#md5=5c14b49d828766c23bb9c83d6a60aaf5 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/f7/3c/57e71eccfb6b737c48fd5c7ae0b33a747b79fa8070ad5e517e30f7d3f954/PyYAML-3.12-cp35-cp35m-win32.whl#md5=d32d5b3c1d4d183df7d81631565de56c (from https://pypi.python.org/simple/pyyaml/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/fe/65/2735b15d118765bdc23be7d9b2ffbf843e2e87c18cd4e8193d63fd09c901/PyYAML-3.11.win-amd64-py3.1.exe#md5=d52af84d2cd6ce9b7cfddb2c525bd957 (from https://pypi.python.org/simple/pyyaml/); unsupported archive format: .exe
  Using version 3.12 (newest of versions: 3.12)
  Looking up "https://pypi.python.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz" in the cache
  Current age based on date: 31064377
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 31064377
  Using cached PyYAML-3.12.tar.gz
  Downloading from URL https://pypi.python.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz#md5=4c129761b661d181ebf7ff4eb2d79950 (from https://pypi.python.org/simple/pyyaml/)
  Running setup.py (path:/tmp/pip-build-jxk3vqsh/pyyaml/setup.py) egg_info for package pyyaml
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/PyYAML.egg-info
    writing pip-egg-info/PyYAML.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/PyYAML.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/PyYAML.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/PyYAML.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/PyYAML.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/PyYAML.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-jxk3vqsh/pyyaml has version 3.12, which satisfies requirement pyyaml==3.12 from https://pypi.python.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz#md5=4c129761b661d181ebf7ff4eb2d79950 
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml: started
  Destination directory: /tmp/tmppondtlr1pip-wheel-
  Running command /home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/bin/python3.6m -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jxk3vqsh/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmppondtlr1pip-wheel- --python-tag cp36
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/resolver.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/events.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/error.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/constructor.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/tokens.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/dumper.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/reader.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/__init__.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/nodes.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/serializer.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/composer.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/representer.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/cyaml.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/scanner.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/parser.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/emitter.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/loader.py -> build/lib.linux-x86_64-3.6/yaml
  running build_ext
  creating build/temp.linux-x86_64-3.6
  checking if libyaml is compilable
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/python3.6m -c build/temp.linux-x86_64-3.6/check_libyaml.c -o build/temp.linux-x86_64-3.6/check_libyaml.o
  checking if libyaml is linkable
  x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-3.6/check_libyaml.o -lyaml -o build/temp.linux-x86_64-3.6/check_libyaml
  building '_yaml' extension
  creating build/temp.linux-x86_64-3.6/ext
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/python3.6m -c ext/_yaml.c -o build/temp.linux-x86_64-3.6/ext/_yaml.o
  ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  Running setup.py bdist_wheel for pyyaml: finished with status 'error'
  Running setup.py clean for pyyaml
  Running command /home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/bin/python3.6m -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jxk3vqsh/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'build/temp.linux-x86_64-3.6' (and everything under it)
  removing 'build/lib.linux-x86_64-3.6' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.6' does not exist -- can't clean it
  removing 'build'
Failed to build pyyaml
Installing collected packages: pyyaml
  Running setup.py install for pyyaml: started
    Running command /home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/bin/python3.6m -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jxk3vqsh/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-se2ryo94-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/site/python3.6/pyyaml
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/resolver.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/events.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/error.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/constructor.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/tokens.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/dumper.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/reader.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/__init__.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/nodes.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/serializer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/composer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/representer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/cyaml.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/scanner.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/parser.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/emitter.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/loader.py -> build/lib.linux-x86_64-3.6/yaml
    running build_ext
    creating build/temp.linux-x86_64-3.6
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/python3.6m -c build/temp.linux-x86_64-3.6/check_libyaml.c -o build/temp.linux-x86_64-3.6/check_libyaml.o
    checking if libyaml is linkable
    x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-3.6/check_libyaml.o -lyaml -o build/temp.linux-x86_64-3.6/check_libyaml
    building '_yaml' extension
    creating build/temp.linux-x86_64-3.6/ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/python3.6m -c ext/_yaml.c -o build/temp.linux-x86_64-3.6/ext/_yaml.o
    ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Running setup.py install for pyyaml: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-build-jxk3vqsh/pyyaml
Exception information:
Traceback (most recent call last):
  File "/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/bin/python3.6m -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jxk3vqsh/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-se2ryo94-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/site/python3.6/pyyaml" failed with error code 1 in /tmp/pip-build-jxk3vqsh/pyyaml/

  Failed building wheel for pyyaml
Command "/home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/bin/python3.6m -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jxk3vqsh/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-se2ryo94-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/franchb/.local/share/virtualenvs/sfbot-aws-ofIdPII4/include/site/python3.6/pyyaml" failed with error code 1 in /tmp/pip-build-jxk3vqsh/pyyaml/
```

**Comment by techalchemy** [comment]
@franchb since it is attempting to build the wheel from source, you will need the python3 development headers,  Since Mint is a Debian/Ubunut variant I'm guessing you need to run `sudo apt-get install python3.6-dev`

**Comment by KevinDCruz** [comment]
Virtual Environment Setting 

```
Python version: 3.6.3
Operating system: Windows, 64 Bits
```
 

Keras was not installing because of pyyaml setting not meeting up for python 3.6. I already had Anaconda installed in a different virtualenv with keras working fine (pyyaml module installed). I just used conda install pyyaml instead of pip and it got installed, thereby using `pip install keras` to install the keras library in my new virtual environment.

if you have anaconda installed already, try using

`conda install yaml
`

and see if it works. It worked for me!
