### ISSUE TITLE
How to install setup.py optional dependencies for a package with extras?

### ISSUE THREAD

**Issue by tedmiston** [kennethreitz/pipenv#1083]
Possibly related issues: https://github.com/kennethreitz/pipenv/issues/858, https://github.com/kennethreitz/pipenv/issues/870, https://github.com/kennethreitz/pipenv/issues/1014.

I'm attempting to install a package which uses the `extras_require` kwarg in its setup function.

The package is in a repo I created [here](https://github.com/astronomerio/boa).  You can see that the setup.py provides two extras: `dev` and `test`.  I'm attempting to use pipenv to create a virtual env for this package.

In a virtual environment I would run `pip install .[dev]` but running the same in pipenv either doesn't seem to work or I'm doing something wrong.

##### Describe your environment

1. macOS 10.13.1
1. Python version: Python 3.6.3
1. Pipenv version: pipenv, version 8.3.2

##### Expected result

I expected a virtual environment to be created by pipenv.

##### Actual result

```
Installing .[dev]…
Traceback (most recent call last):
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2873, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'.[dev]'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/taylor/.pyenv/versions/3.6.3/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 1876, in install
    c = pip_install(package_name, ignore_hashes=True, allow_global=system, no_deps=False, verbose=verbose, pre=pre)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 1355, in pip_install
    if [x for x in requirements.parse(package_name.split('--hash')[0].split('--trusted-host')[0])][0].vcs:
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 1355, in <listcomp>
    if [x for x in requirements.parse(package_name.split('--hash')[0].split('--trusted-host')[0])][0].vcs:
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/requirements/parser.py", line 50, in parse
    yield Requirement.parse(line)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/requirements/requirement.py", line 220, in parse
    return cls.parse_line(line)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/requirements/requirement.py", line 198, in parse_line
    pkg_req = Req.parse(line)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2918, in parse
    req, = parse_requirements(s)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2866, in parse_requirements
    yield Requirement(line)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2875, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'.[dev]'"
```

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

1. `git clone git@github.com:astronomerio/boa.git`
1. `cd boa`
1. `pipenv install .[dev]`

---

**Workaround**

Here's my current workaround for others that stumble upon this issue:

1. cd into project directory
1. `pipenv shell`
1. Inside that virtual env, run `pip install -e .[dev]`

(This works but kind of feels like "doing it wrong".)

**Comment by techalchemy** [comment]
Erm if you know to use the `-e` flag with pip why omit it when using pipenv? Does it work with that flag?

**Comment by tedmiston** [comment]
A normal install without the `-e` is valid in the pip docs and does work.  I'm trying to do the same here since I'm not actually editing the package.

**Comment by tedmiston** [comment]
For reference, I believe `pipenv install -e .[dev]` did not work either.

**Comment by tedmiston** [comment]
I wanted to follow back with variations of the above command that give similar output.

```
$ pipenv install -e .
Creating a virtualenv for this project…
⠋Using base prefix '/Users/taylor/.pyenv/versions/3.6.3'
New python executable in /Users/taylor/.virtualenvs/boa-zEMXr5G8/bin/python3.6
Also creating executable in /Users/taylor/.virtualenvs/boa-zEMXr5G8/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/taylor/.virtualenvs/boa-zEMXr5G8
Creating a Pipfile for this project…
Installing -e .…
Traceback (most recent call last):
  File "/Users/taylor/.pyenv/versions/3.6.3/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 1880, in install
    converted = convert_deps_from_pip(package_name)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/utils.py", line 547, in convert_deps_from_pip
    os.path.isfile(req.name)) and not req.vcs:
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```

```
t-mbp:boa taylor$ pipenv install -e .[dev]
Installing -e .[dev]…
Traceback (most recent call last):
  File "/Users/taylor/.pyenv/versions/3.6.3/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/cli.py", line 1880, in install
    converted = convert_deps_from_pip(package_name)
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pipenv/utils.py", line 547, in convert_deps_from_pip
    os.path.isfile(req.name)) and not req.vcs:
  File "/Users/taylor/.pyenv/versions/3.6.3/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by techalchemy** [comment]
@tedmiston sorry this is fixed in master with #958 for the `-e` case but not the alternative case. We need to handle requirement parsing better...

**Comment by mdeguzis** [comment]
This also seems to work until this is fixed:
```
pipenv run pip install -e .
```

**Comment by kennethreitz** [comment]
@mdeguzis that is fixed in master

**Comment by techalchemy** [comment]
@kennethreitz #1083 is not fixed in master until #1095 is merged, but `pipenv install -e .` is currently fixed

**Comment by kennethreitz** [comment]
merged :)

**Comment by mdeguzis** [comment]
Any idea when that will make it into PyPi? I install via `pip install --user pipenv`

**Comment by nateprewitt** [comment]
@mdeguzis likely early next week but we're waiting on resolving a few other things before cutting the 9.0 release.

**Comment by techalchemy** [comment]
@mdeguzis in the meantime you can do `pip install --user --upgrade git+https://github.com/kennethreitz/pipenv.git@master#egg=pipenv`, but you will have to reinstall from PyPI when the new one is released

**Comment by tedmiston** [comment]
@kennethreitz Thanks for merging.  Just updated to 9.0.1 today and my commands above work now. 👍

**Comment by romantolkachyov** [comment]
I found that zsh trying to interpret `.[dev]` part so under zsh you must run `pipenv install -e '.[dev]'` (escape it somehow)

**Comment by topless** [comment]
Or add `unsetopt nomatch` to your `zshrc` to stop escaping them
