### ISSUE TITLE
Broken `pipenv install -e .`?

### ISSUE THREAD

**Issue by resurtm** [kennethreitz/pipenv#1104]
Hi @kennethreitz!

Thank you for the nice project! ;-) I've stumbled upon this issue today:

Operating system:
```
resurtm@resurtm-desktop:~$ screenfetch
         _,met$$$$$gg.           resurtm@resurtm-desktop
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 9.1 stretch
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.9.0-4-amd64
   ,$$P'              `$$$.      Uptime: 2h 47m
  ',$$P       ,ggs.     `$$b:    Packages: 2430
  `d$$'     ,$P"'   .    $$$     Shell: bash 4.4.12
   $$P      d$'     ,    $$P     Resolution: 1920x1200
   $$:      $$.   -    ,d$$'     DE: XFCE
   $$\;      Y$b._   _,d$P'      WM: Xfwm4
   Y$$.    `.`"Y$$$$P"'          WM Theme: Default
   `$$b      "-.__               GTK Theme: Adwaita [GTK2]
    `Y$$                         Icon Theme: Tango
     `Y$$.                       Font: Sans 10
       `$$b.                     CPU: Intel Core i5 CPU 760 @ 2.801GHz
         `Y$$b.                  GPU: GeForce GT 640/PCIe/SSE2
            `"Y$b._              RAM: 5115MiB / 16041MiB
                `""""           
```

Python and pipenv versions:
```
(message_wiper_ng-UjpHa307) resurtm@resurtm-desktop:~/dev/message_wiper_ng$ python -V
Python 3.5.3
(message_wiper_ng-UjpHa307) resurtm@resurtm-desktop:~/dev/message_wiper_ng$ pipenv --version
pipenv, version 8.3.2
```

What I'm trying to do and what I'm getting:
```
resurtm@resurtm-desktop:~/dev/message_wiper_ng$ pipenv --three
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/resurtm/.local/share/virtualenvs/message_wiper_ng-UjpHa307/bin/python3
Also creating executable in /home/resurtm/.local/share/virtualenvs/message_wiper_ng-UjpHa307/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

Virtualenv location: /home/resurtm/.local/share/virtualenvs/message_wiper_ng-UjpHa307

resurtm@resurtm-desktop:~/dev/message_wiper_ng$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
source /home/resurtm/.local/share/virtualenvs/message_wiper_ng-UjpHa307/bin/activate

resurtm@resurtm-desktop:~/dev/message_wiper_ng$ source /home/resurtm/.local/share/virtualenvs/message_wiper_ng-UjpHa307/bin/activate

(message_wiper_ng-UjpHa307) resurtm@resurtm-desktop:~/dev/message_wiper_ng$ pipenv install
Installing dependencies from Pipfile.lock (74f424)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:03

(message_wiper_ng-UjpHa307) resurtm@resurtm-desktop:~/dev/message_wiper_ng$ pipenv install -e .
Installing -e .…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1880, in install
    converted = convert_deps_from_pip(package_name)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 547, in convert_deps_from_pip
    os.path.isfile(req.name)) and not req.vcs:
  File "/usr/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument
```

![image](https://user-images.githubusercontent.com/100198/33060960-667f323e-cec4-11e7-8fbf-df64c0493335.png)

My `setup.py` file:

```python
from setuptools import setup


def readme():
    with open('README.rst') as f:
        return f.read()


setup(
    name='message_wiper_ng',
    version='0.0.1',
    description='MessageWiperNG',
    long_description=readme(),
    url='https://github.com/resurtm/message_wiper_ng',
    download_url='https://github.com/resurtm/message_wiper_ng/archive/v0.0.1.tar.gz',
    author='resurtm',
    author_email='resurtm@gmail.com',
    license='MIT',
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'Intended Audience :: End Users/Desktop',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
    ],
    packages=['message_wiper_ng'],
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'telethon',
    ],
)
```

Let me know if you need some more details on this. Please also tell me if I'm doing something wrong. Thanks!

Cheers,
@resurtm

**Comment by erinxocon** [comment]
Hi @resurtm, thanks for using pipenv!  What does your `Pipfile` look like when it gets created?  I also see you did `pipenv shell` and then execute pipenv commands inside of it.  This isn't necessary, and may in fact be causing the issue.  Could you try executing the install command outside of the invoked subshell?

**Comment by resurtm** [comment]
Hi @erinxocon!

> I also see you did pipenv shell and then execute pipenv commands inside of it. This isn't necessary, and may in fact be causing the issue.

Oh, right! I can just use `pipenv whatever` without activating `pipenv shell`, and it will use the current project's pip & virtualenv.

> Could you try executing the install command outside of the invoked subshell?

No, it doesn't work for this case too.

```
resurtm@resurtm-desktop:~/dev/message_wiper_ng$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
source /home/resurtm/.local/share/virtualenvs/message_wiper_ng-UjpHa307/bin/activate
resurtm@resurtm-desktop:~/dev/message_wiper_ng$ source /home/resurtm/.local/share/virtualenvs/message_wiper_ng-UjpHa307/bin/activate
(message_wiper_ng-UjpHa307) resurtm@resurtm-desktop:~/dev/message_wiper_ng$ exit
exit
resurtm@resurtm-desktop:~/dev/message_wiper_ng$ pipenv install -e .
Installing -e .…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1880, in install
    converted = convert_deps_from_pip(package_name)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 547, in convert_deps_from_pip
    os.path.isfile(req.name)) and not req.vcs:
  File "/usr/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument
resurtm@resurtm-desktop:~/dev/message_wiper_ng$ 
```

![image](https://user-images.githubusercontent.com/100198/33063376-7bb95fa0-cecc-11e7-9854-c83773ad3840.png)

Pipfile:
```toml
[[source]]

name = "pypi"
url = "https://pypi.python.org/simple"
verify_ssl = true


[dev-packages]



[requires]

python_version = "3.5"


[packages]

telethon = "*"
```

Pipfile.lock:
```json
{
    "_meta": {
        "hash": {
            "sha256": "1a83e7ff1c2920f1b656992870a94a2e45943e21e6a4f665b26aba3b8574f424"
        },
        "host-environment-markers": {
            "implementation_name": "cpython",
            "implementation_version": "3.5.3",
            "os_name": "posix",
            "platform_machine": "x86_64",
            "platform_python_implementation": "CPython",
            "platform_release": "4.9.0-4-amd64",
            "platform_system": "Linux",
            "platform_version": "#1 SMP Debian 4.9.51-1 (2017-09-28)",
            "python_full_version": "3.5.3",
            "python_version": "3.5",
            "sys_platform": "linux"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.5"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pyaes": {
            "hashes": [
                "sha256:02c1b1405c38d3c370b085fb952dd8bea3fadcee6411ad99f312cc129c536d8f"
            ],
            "version": "==1.6.1"
        },
        "pyasn1": {
            "hashes": [
                "sha256:5eac8d0c1c1282842c9145ae134990a1baf7616eb4cee9129213fad76eba4f54",
                "sha256:960a603e677897ea29b9a1327b789b7b8a9e187a89e05fed9c3152b3b7c22954",
                "sha256:4bb562b9f1fc4526028b2aa4dc027dce08f3ade0780abc593a02ce6dbade6e6c",
                "sha256:8fa8884056bd5b2c92ca1685e6344121b6b43718b44f0c6eb223958003c9d14a",
                "sha256:16e896433f84575f0636cd9aa8b24659689268a62e00f17235e1fc23c6b00b25",
                "sha256:bb6f5d5507621e0298794bc3e75b8f963e886cee388a378ab58e5c35ac024276",
                "sha256:60bf78784b117979f5517c38308f6965fff6c803660fbb16368d94433953b62a",
                "sha256:4a677c6c9e484977ed6c6a93714ff06ac374220408afeaeef4ef2af652af0f3d",
                "sha256:b16fb6097d00bbafc114861b16ea41cfe63e32fed1bdc7cd5905a3e02a992fa3",
                "sha256:8212bde51ec192e30654efe10e636082738ed728e316049f3685d66b8c92941c",
                "sha256:8d4f0971682203bdfc93740ee7d3fcba0a7f55629451dbe2d32af2335c55b2be",
                "sha256:187f2a66d617683f8e82d5c00033b7c8a0287e1da88a9d577aebec321cad4965"
            ],
            "version": "==0.3.7"
        },
        "rsa": {
            "hashes": [
                "sha256:43f682fea81c452c98d09fc316aae12de6d30c4b5c84226642cf8f8fd1c93abd",
                "sha256:25df4e10c263fb88b5ace923dd84bf9aa7f5019687b5e55382ffcdb8bede9db5"
            ],
            "version": "==3.4.2"
        },
        "telethon": {
            "hashes": [
                "sha256:1a39bedd606c203ed346935cad4ce32215c8e4d0a98b3df974bf4ee1ed66d56a",
                "sha256:1875dfdcd3bf42f1b46b78e54b46d4d694644206742360e6d00a7b3165a7cce5"
            ],
            "version": "==0.15.5.1"
        }
    },
    "develop": {}
}
```

**Comment by resurtm** [comment]
@erinxocon, as a temporary workaround I'm doing now:

```
pipenv shell
pip install -e .
```

**Comment by erinxocon** [comment]
@resurtm That was my goto workaround until we fixed this.  Unclear why it's not working now.  I'll have to investigate in the morning!

**Comment by resurtm** [comment]
Here's my repo I'm working on using pipenv (just in case): https://github.com/resurtm/message_wiper_ng

**Comment by techalchemy** [comment]
@erinxocon @resurtm this is fixed in master and will be out in the next release — see also #1083

**Comment by resurtm** [comment]
@techalchemy Thanks! I've installed master version and it works as it should. ;-)

@erinxocon I guess we can close this?

**Comment by kennethreitz** [comment]
why wasn't this closed when this was fixed?

**Comment by techalchemy** [comment]
@kennethreitz because its only 9 hours old
