### ISSUE TITLE
Install a local wheel file

### ISSUE THREAD

**Issue by julianwachholz** [kennethreitz/pipenv#1105]
Trying to install a local `*.whl` wheel file fails with pipenv.
This is related to https://github.com/kennethreitz/pipenv/issues/480
I have verified my wheel that it works when I install it using `python -m http.server` and using a HTTP URI for the wheel instead of a local file system path.

##### Describe your environment

1. **OS Type**: Linux pns-mac-003 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
1. **Python version**: Python 3.6.3 
1. **Pipenv version**: pipenv, version 8.3.2

##### Expected result

Wheel installs correctly. In the same way I can install a wheel using `pip install path/to/package.whl`.

##### Actual result

```
$ pipenv install ../foolib/dist/foo-0.0.0.dev0-py3-none-any.whl 
Installing ../foolib/dist/foo-0.0.0.dev0-py3-none-any.whl…
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 2689, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3015, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.6/site-packages/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'../foolib/'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jwa/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/cli.py", line 1876, in install
    c = pip_install(package_name, ignore_hashes=True, allow_global=system, no_deps=False, verbose=verbose, pre=pre)
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/cli.py", line 1355, in pip_install
    if [x for x in requirements.parse(package_name.split('--hash')[0].split('--trusted-host')[0])][0].vcs:
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/cli.py", line 1355, in <listcomp>
    if [x for x in requirements.parse(package_name.split('--hash')[0].split('--trusted-host')[0])][0].vcs:
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/vendor/requirements/parser.py", line 50, in parse
    yield Requirement.parse(line)
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/vendor/requirements/requirement.py", line 220, in parse
    return cls.parse_line(line)
  File "/home/jwa/.local/lib/python3.6/site-packages/pipenv/vendor/requirements/requirement.py", line 198, in parse_line
    pkg_req = Req.parse(line)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3061, in parse
    req, = parse_requirements(s)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3008, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'../foolib/'"
```

Trying to install the wheel with `-e` does not work, either. But that is expected as a wheel shouldn't be editable.

##### Steps to replicate

1. Download any `.whl` file to your local filesystem
2. Try to install it using `pipenv install path/to/package.whl`

**Comment by techalchemy** [comment]
Hey @julianwachholz thanks for the report — this one sucks to run into but is actually fixed in master and will be out in the next release. In the meantime you can work around this by using the `file://` URI format instead of a relative path, but let me know if that doesn’t work

**Comment by julianwachholz** [comment]
Thanks for the heads up! I confirmed this works with the latest master checked out.

Great work, keep it up!

**Comment by wedesoft** [comment]
Another way might be to run `pipenv run pip install wheelname.whl`.
