### ISSUE TITLE
Can't lock private pypi packages when connection to https://pypi.org is iffy

### ISSUE THREAD

**Issue by helderco** [kennethreitz/pipenv#1110]
At least from my company network, I can't get a reliable connection to https://pypi.org:

```
$ curl https://pypi.org/ 
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to pypi.org:443 
```

This is causing `pipenv lock` to fail with a "Connection reset by peer", when pipenv is trying to grab hashes from the new warehouse API, for our private pypi packages.

##### Describe your environment

1. Mac OS X
1. Python version: 3.6.3
1. Pipenv version: 8.3.2

##### Expected result

I expect the lock to skip failed hash grabbing.

##### Actual result
```
. . .
Result of round 6: stable, done
Traceback (most recent call last):
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/opt/pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/opt/pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/opt/pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/opt/pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/opt/pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/opt/pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/opt/pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/opt/pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/helder/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 2061, in lock
    do_lock(verbose=verbose, clear=clear, pre=pre)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 1121, in do_lock
    pre=pre
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/utils.py", line 496, in resolve_deps
    r = requests.get('https://pypi.org/pypi/{0}/json'.format(name), timeout=10)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/helder/.local/venvs/pipenv/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

##### Fix

We can catch connection failures to `https://pypi.org/pypi/{name}/json`, in `resolve_deps()`:

```
index 919f824..6cfcdc1 100644
--- a/pipenv/utils.py
+++ b/pipenv/utils.py
@@ -39 +39 @@ from pip.exceptions import DistributionNotFound
-from requests.exceptions import HTTPError
+from requests.exceptions import HTTPError, ConnectionError
@@ -594 +594 @@ def resolve_deps(deps, which, which_pip, project, sources=None, verbose=False, p
-                except (ValueError, KeyError):
+                except (ValueError, KeyError, ConnectionError):
```

**Comment by nateprewitt** [comment]
Yep, that is a sensible patch for this. If you'd like to open that as a PR, I'm happy to merge it. Thanks @helderco!

**Comment by mattjegan** [comment]
As per the discussion with @nateprewitt in #1113 I think it could be beneficial to implement retries on some `ConnectionError`s since this can occur in continuous integration environments and it may just be a temporary network issue. However, as per Nate's comment in #1113 I can see this being an issue if the network is completely out so perhaps the retries should be triggered through some flag to the effect of `pipenv install --retries=4` for example.

**Comment by erinxocon** [comment]
I'd like to avoid adding another flag to `pipenv install`.  I do think some sort of retry should happen eventually however I'm more in @nateprewitt's camp right now as if the network issue is persistent, we should fail quickly and continue.  We had a similar issue with really slow internet connections timing out when checking for updates and we decided that if the connection is down, it won't check for another update for 24 hours in case of persistent network issues.

**Comment by mattjegan** [comment]
@erinxocon I understand the annoyance of another flag, however, I think we need a way to have this functionality optionally since pipenv is run both locally and in automated processes such as CI/CD builds. If it was optional, then we completely avoid the frustrating user experience, however, I'm not sure what the correct path would be for implementing this feature without the use of a flag.

**Comment by techalchemy** [comment]
One option might be to do what pipenv does in other cases like this, and use an environment variable, e.g. `PIPENV_MAX_RETRIES`, which defaults to 1, but checks if pipenv is running in a CI environment. If so, it can set the default to 4 or something.

**Comment by erinxocon** [comment]
I'd be open to maybe having an environment variable `PIPENV_MAX_RETRIES` or somerhing similar.  I don't know how we'd detect it was a CI environment though.  We should just let the user set that env variable manually in their CI script.  @nateprewitt thoughts?

**Comment by mattjegan** [comment]
I think that would be a great idea @erinxocon and @techalchemy

**Comment by techalchemy** [comment]
@erinxocon from `environments.py`:

```python
# Disable the spinner on Travis-Ci (and friends).
if 'CI' in os.environ:
    PIPENV_NOSPIN = True
```

CI environments pretty much universally set an environment variable called 'CI', so you just have to check for it.

**Comment by erinxocon** [comment]
Oh well will you look at that.  How convenient!

**Comment by nateprewitt** [comment]
@techalchemy are you sure about that? I'm pretty sure we determined this is *only* a Travis-CI thing a few months ago.

**Comment by techalchemy** [comment]
@nateprewitt I am sure as in I made a bunch of assumptions, so could easily be wrong about the universality.  However, I know that Travis, Appveyor, and Circle-CI all set it.  I am fairly sure it is a standard practice and haven't encountered a CI environment that doesn't set it.

For those that don't, environment variable feels safest to me anyway since users can still set it for their CI environment either way, and pipenv can check if it's set and have a default/fallback to 1 for normal use and 4/whatever for CI. But that's just my $0.02.

**Comment by nateprewitt** [comment]
If @helderco wants to add the retry functionality to his PR that's fine with me, otherwise we can add it after that's merged.

As for variable retry counts in CI vs regular, I'm skeptical we need a higher retry count than 1. If it really is a transient network error it's unlikely it will fail twice in a row but succeed a third or fourth time. Having the variable for users to pass to their CI environment with another value seems sufficient.

**Comment by techalchemy** [comment]
Seems right to me

**Comment by erinxocon** [comment]
@nateprewitt I've merged @helderco's fix, it does not contain anything regarding retires, so either us or the community will need to tackle it if we want to go that route.  Do you want to continue tracking the retires here or open another issue for that?
