### ISSUE TITLE
i can't install mysql-python   who can help me  ..thanks

### ISSUE THREAD

**Issue by zilinyo** [kennethreitz/pipenv#1154]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type
1. Python version: `$ python3.6`

error log

inzidembp:3.6.3 linzi$ brew install mysql-connector-c
Updating Homebrew...
Warning: mysql-connector-c 6.1.11 is already installed
linzidembp:3.6.3 linzi$ pip install mysql-python
Collecting mysql-python
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6n/xm3z1f1x5sd37p3dtd3hgggm0000gn/T/pip-build-SYqF3p/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 53, in get_config
        libraries = [ dequote(i[2:]) for i in libs if i.startswith(compiler_flag("l")) ]
      File "setup_posix.py", line 8, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6n/xm3z1f1x5sd37p3dtd3hgggm0000gn/T/pip-build-SYqF3p/mysql-python/

**Comment by zilinyo** [comment]
my system is  mscOS 10.13.1

**Comment by shreyashk09** [comment]
In order to connect to mysql from python (mine 3.7) (import mysql.connector), I used 'pip install mysql-connector-python'. Worked for me

**Comment by nrmculu** [comment]
Update python 2.X to a later version. It worked for me.

I had 2.7.0 installed. After updating it, i was sorted
