### ISSUE TITLE
Default pypi URL from previous releases no longer works

### ISSUE THREAD

**Issue by thirtyseven** [kennethreitz/pipenv#116]
```
$ pipenv --version
pipenv, version 3.2.3
```

```
$ cat Pipfile 
[[source]]
url = "https://pypi.org/"
verify_ssl = true

[requires]
os_name = "posix"
python_version = "3.5"

[dev-packages]
google-api-python-client = "*"
fakeredis = "==0.7"
mock = "==1.2.0"

[packages]
ua-parser = "==0.7.1"
fluent-logger = "==0.4.0"
gevent = "*"
isodate = "==0.5.4"
newrelic = "==2.72.0.52"
click = "==6.6"
redis = "==2.10.5"
numpy = "==1.11.1"
hiredis = "==0.2.0"
gunicorn = "==18.0"
simplejson = "==3.5.2"
Django = "==1.8"
maxminddb = "==1.2.0"
pytz = "==2016.6.1"
user-agents = "==1.0.1"
python-dateutil = "==2.4.2"
boto = "==2.42.0"
SPARQLWrapper = "==1.7.6"
geoip2 = "==2.2.0"
django-cors-headers = "==1.1.0"
nose = "==1.3.7"
httpagentparser = "==1.6.0"
requests = "==2.8.1"
```

```$ rm -r Pipfile.lock .venv
$ pipenv install
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==3.2.3', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 576, in install
    ensure_project(three=three)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 92, in ensure_project
    ensure_pipfile()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 69, in ensure_pipfile
    ensure_proper_casing()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 120, in ensure_proper_casing
    proper_case_section('packages')
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 109, in proper_case_section
    new_casing = proper_case(dep)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 474, in proper_case
    raise IOError('Unable to find package {0} in PyPI repository.'.format(crayons.green(package_name)))
OSError: Unable to find package pytz in PyPI repository.
```
Running pipenv install again will report a different package not being found.

This worked fine before upgrading.  Did the Pipfile format change?

**Comment by nateprewitt** [comment]
Hey @thirtyseven, it looks like the problem is actually in your Pipfile. `https://pypi.org/` isn't a valid endpoint for retrieving packages, it needs to be something like `https://pypi.org/simple` or `https://pypi.python.org/simple`.

Is this a new Pipfile, or was this working prior to 3.2.3?

**Comment by thirtyseven** [comment]
The Pipfile was created with an 0.2 release and definitely works if I test
with 0.2.8.

**Comment by nateprewitt** [comment]
Ok, I think I've got a handle on this. `pipenv` didn't use the source field until 0.2.6 which was after you generated your original file. When we started using the source field, we realized that the default configuration was wrong and updated it. The default since ~3.0.0 has been https://pypi.python.org/simple. It should be updated here and at the Pipfile repo.

If you update your URL to that, things should work as intended. I had a moment of hesitation because there is in fact a bug when using https://pypi.org/simple because the HTML returned is slightly different and tripping up our parser.

Let me know if you're still experiencing issues after updating the URL and running `pipenv lock`.

**Comment by thirtyseven** [comment]
Confirming that updating the source fixes the issue.  I'm leaving the issue open though in case you want to handle this case for the users that started with the bad version.

**Comment by nateprewitt** [comment]
@thirtyseven could you clarify what you'd like to see to address this?

**Comment by thirtyseven** [comment]
I think the most helpful thing to do would be for pipenv to check if the source is exactly the string `"https://pypi.org/"`, and if so display a warning message like: "Your Pipfile was created with a buggy version of pipenv, please change source.url to _correct url_".  Or it could just change the source itself.

I can write a PR implementing this if you'd like.  It's also quite possible that not enough people were affected by this to make it worth it.

**Comment by kennethreitz** [comment]
I agree that adding a helpful message may be useful, as this bug was caused by this software.

**Comment by paradox41** [comment]
I am not sure if this is related at all, but I am now unable to fetch packages from public git repos:

#### Traceback

```
pipenv install git+https://github.com/paradox41/heroprotocol.git#egg=heroprotocol 
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 594, in install
    ensure_project(three=three)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 92, in ensure_project
    ensure_pipfile()
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 69, in ensure_pipfile
    ensure_proper_casing()
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 128, in ensure_proper_casing
    casing_changed = proper_case_section('packages')
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 111, in proper_case_section
    new_casing = proper_case(dep)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 492, in proper_case
    raise IOError('Unable to find package {0} in PyPI repository.'.format(crayons.green(package_name)))
IOError: Unable to find package heroprotocol in PyPI repository.
```

#### Pipfile
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
flask-oauthlib = "==0.9.3"
py = "==1.4.32"
"delegator.py" = "==0.0.7"
configargparse = "==0.11.0"
pytest-cov = "==2.2.0"
graphene = "==1.1.3"
fixture = "==1.5.9"
dateutils = "==0.6.6"
ipython-genutils = "==0.1.0"
packaging = "==16.8"
ipython = "==5.1.0"
pydash = "==3.4.8"
pygments = "==2.2.0"
promise = "==1.0.1"
prompt-toolkit = "==1.0.9"
pyparsing = "==2.1.10"
click = "==6.7"
appdirs = "==1.4.0"
mako = "==1.0.6"
oauthlib = "==2.0.1"
pexpect = "==4.2.1"
amqp = "==2.1.4"
flask = "==0.12"
ipdb = "==0.10.1"
ujson = "==1.35"
flask-sqlalchemy = "==2.1"
redis = "==2.10.5"
ptyprocess = "==0.5.1"
kafka-python = "==1.3.2"
celery = "==4.0.2"
graphql-relay = "==0.4.5"
pytest = "==2.8.7"
flask-bcrypt = "==0.7.1"
kombu = "==4.0.2"
typing = "==3.5.3.0"
toml = "==0.9.2"
itsdangerous = "==0.24"
bcrypt = "==3.1.2"
uwsgi = "==2.0.14"
python-editor = "==1.0.3"
virtualenv = "==15.1.0"
crayons = "==0.1.2"
requirements-parser = "==0.1.0"
pathlib2 = "==2.2.1"
simplejson = "==3.10.0"
vine = "==1.1.3"
flask-login = "==0.4.0"
graphene-sqlalchemy = "==1.1.1"
markupsafe = "==0.23"
billiard = "==3.5.0.2"
colorama = "==0.3.7"
coverage = "==3.7.1"
flask-shell-ipython = "==0.2.2"
python-dateutil = "==2.6.0"
coveralls = "==1.1"
iso8601 = "==0.1.11"
pickleshare = "==0.7.4"
six = "==1.10.0"
decorator = "==4.0.11"
"backports.shutil-get-terminal-size" = "==1.0.0"
mpyq = "==0.2.5"
flask-script = "==2.0.5"
flask-graphql = "==1.4.0"
graphql-core = "==1.0.1"
pipenv = "==0.2.8"
enum34 = "==1.1.6"
pytz = "==2016.10"
sqlalchemy = "==1.1.5"
wcwidth = "==0.1.7"
jinja2 = "==2.9.4"
traitlets = "==4.3.1"
requests-oauthlib = "==0.7.0"
alembic = "==0.8.10"
pycparser = "==2.17"
psycopg2 = "==2.6.2"
singledispatch = "==3.4.0.3"
requests = "==2.13.0"
docopt = "==0.6.2"
simplegeneric = "==0.8.1"
cffi = "==1.9.1"
scandir = "==1.4"

[packages.heroprotocol]
git = "https://github.com/paradox41/heroprotocol.git"

[packages.resource_alchemy]
git = "https://github.com/tomneyland/resource-alchemy.git"
```

#### Pipefile.lock

```
{
    "default": {
        "Mako": "==1.0.6",
        "flask-oauthlib": "==0.9.3",
        "flask-sqlalchemy": "==2.1",
        "configargparse": "==0.11.0",
        "Flask": "==0.12",
        "cffi": "==1.9.1",
        "ipython-genutils": "==0.1.0",
        "packaging": "==16.8",
        "pygments": "==2.2.0",
        "promise": "==1.0.1",
        "Werkzeug": "==0.11.15",
        "prompt-toolkit": "==1.0.9",
        "pyparsing": "==2.1.10",
        "appdirs": "==1.4.0",
        "oauthlib": "==2.0.1",
        "Flask-Script": "==2.0.5",
        "pexpect": "==4.2.1",
        "flask": "==0.12",
        "ipdb": "==0.10.1",
        "py": "==1.4.32",
        "celery": "==4.0.2",
        "Jinja2": "==2.9.4",
        "python-editor": "==1.0.3",
        "typing": "==3.5.3.0",
        "itsdangerous": "==0.24",
        "appnope": "==0.1.0",
        "sqlalchemy": "==1.1.5",
        "pathlib2": "==2.2.1",
        "simplejson": "==3.10.0",
        "vine": "==1.1.3",
        "Flask-OAuthlib": "==0.9.3",
        "iso8601": "==0.1.11",
        "markupsafe": "==0.23",
        "billiard": "==3.5.0.2",
        "jinja2": "==2.9.4",
        "python-dateutil": "==2.6.0",
        "flask-graphql": "==1.4.0",
        "decorator": "==4.0.11",
        "graphql-core": "==1.0.1",
        "mpyq": "==0.2.5",
        "flask-script": "==2.0.5",
        "coveralls": "==1.1",
        "delegator.py": "==0.0.7",
        "Pygments": "==2.2.0",
        "requests-oauthlib": "==0.7.0",
        "uWSGI": "==2.0.14",
        "pycparser": "==2.17",
        "pydash": "==3.4.8",
        "resource-alchemy": "==0.1.0",
        "dateutils": "==0.6.6",
        "resource_alchemy": {
            "git": "https://github.com/tomneyland/resource-alchemy.git"
        },
        "graphene": "==1.1.3",
        "Flask-SQLAlchemy": "==2.1",
        "fixture": "==1.5.9",
        "SQLAlchemy": "==1.1.5",
        "singledispatch": "==3.4.0.3",
        "click": "==6.7",
        "mako": "==1.0.6",
        "amqp": "==2.1.4",
        "ujson": "==1.35",
        "six": "==1.10.0",
        "redis": "==2.10.5",
        "ptyprocess": "==0.5.1",
        "kafka-python": "==1.3.2",
        "graphql-relay": "==0.4.5",
        "pytest": "==2.8.7",
        "flask-bcrypt": "==0.7.1",
        "kombu": "==4.0.2",
        "Flask-Bcrypt": "==0.7.1",
        "bcrypt": "==3.1.2",
        "uwsgi": "==2.0.14",
        "heroprotocol": {
            "git": "https://github.com/paradox41/heroprotocol.git"
        },
        "virtualenv": "==15.1.0",
        "crayons": "==0.1.2",
        "requirements-parser": "==0.1.0",
        "traitlets": "==4.3.1",
        "flask-login": "==0.4.0",
        "graphene-sqlalchemy": "==1.1.1",
        "colorama": "==0.3.7",
        "coverage": "==3.7.1",
        "flask-shell-ipython": "==0.2.2",
        "ipython": "==5.1.0",
        "pickleshare": "==0.7.4",
        "Flask-Login": "==0.4.0",
        "Flask-GraphQL": "==1.4.0",
        "ConfigArgParse": "==0.11.0",
        "pipenv": "==0.2.8",
        "MarkupSafe": "==0.23",
        "enum34": "==1.1.6",
        "simplegeneric": "==0.8.1",
        "pytest-cov": "==2.2.0",
        "wcwidth": "==0.1.7",
        "pytz": "==2016.10",
        "toml": "==0.9.2",
        "psycopg2": "==2.6.2",
        "requests": "==2.13.0",
        "docopt": "==0.6.2",
        "backports.shutil-get-terminal-size": "==1.0.0",
        "alembic": "==0.8.10",
        "scandir": "==1.4"
    },
    "develop": {},
    "_meta": {
        "sources": [
            {
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ],
        "requires": {},
        "Pipfile-sha256": "16d57a0d06ac907d923c9b516310698779fab27ca9487b89de1c26d09fd1bd9e"
    }
}
```

This was working prior to v3.0.0 FWIW. I just tried installing again today, and it threw out this error.

If this isn't related, I don't mind opening another issue.

Thanks in advance.

**Comment by nateprewitt** [comment]
@paradox41 this appears to be related to the way pipenv normalizes package names rather than being unable to find the repository. I would consider this a separate bug if you'd like to open a new ticket. Thanks!
