### ISSUE TITLE
pipenv fails right after install

### ISSUE THREAD

**Issue by SergeyPirogov** [kennethreitz/pipenv#13]
I have Ubuntu 14.04

> installed using pip install pipenv

> pipenv producecs stacktrace 
```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/usr/local/lib/python2.7/dist-packages/pipenv/__init__.py", line 1, in <module>
    from .cli import cli
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 9, in <module>
    import delegator
  File "/usr/local/lib/python2.7/dist-packages/delegator.py", line 5, in <module>
    from pexpect.popen_spawn import PopenSpawn
ImportError: No module named popen_spawn
```

Tried to install popen_spawn manually

```
Could not find a version that satisfies the requirement popen_spawn (from versions: )
No matching distribution found for popen_spawn

```

**Comment by jpadilla** [comment]
this should be already fixed by `pipenv==0.1.13`

```
$ pip install pipenv
You are using pip version 7.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pipenv
  Using cached pipenv-0.1.13-py2-none-any.whl
Collecting click (from pipenv)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting virtualenv (from pipenv)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Collecting toml (from pipenv)
Requirement already satisfied (use --upgrade to upgrade): pip in ./.pyenv/versions/pipenv/lib/python2.7/site-packages (from pipenv)
Collecting delegator.py>=0.0.2 (from pipenv)
  Using cached delegator.py-0.0.4-py2-none-any.whl
Collecting crayons (from pipenv)
  Using cached crayons-0.1.1-py2-none-any.whl
Collecting pexpect (from delegator.py>=0.0.2->pipenv)
  Using cached pexpect-4.2.1-py2.py3-none-any.whl
Collecting colorama (from crayons->pipenv)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect->delegator.py>=0.0.2->pipenv)
  Using cached ptyprocess-0.5.1-py2.py3-none-any.whl
Installing collected packages: click, virtualenv, toml, ptyprocess, pexpect, delegator.py, colorama, crayons, pipenv
Successfully installed click-6.7 colorama-0.3.7 crayons-0.1.1 delegator.py-0.0.4 pexpect-4.2.1 pipenv-0.1.13 ptyprocess-0.5.1 toml-0.9.2 virtualenv-15.1.0
```

**Comment by kennethreitz** [comment]
Correct!

**Comment by zackkitzmiller** [comment]
I can reproduce this on the current version (0.2.4)

```
Successfully installed pipenv-0.2.4

zackkitzmiller at Sol in ~/Apps/seatgeek/api on master ⇣
❯ pipenv                                                                                                                                 1s 236ms
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/usr/local/lib/python2.7/site-packages/pipenv/__init__.py", line 1, in <module>
    from .cli import cli
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 9, in <module>
    import delegator
  File "/usr/local/lib/python2.7/site-packages/delegator.py", line 5, in <module>
    from pexpect.popen_spawn import PopenSpawn
ImportError: No module named popen_spawn
```

**Comment by kennethreitz** [comment]
hmm, that shouldn't be happening.

**Comment by zackkitzmiller** [comment]
It seems like it was a conflicting version of `pexpect`. `pip uninstall pexpect; pip uninstall pipenv` followed by a `pip install pipenv` resolved this for me.
