### ISSUE TITLE
pipenv shell fails with traceback if no Pipfile exists

### ISSUE THREAD

**Issue by dvachaiev** [kennethreitz/pipenv#171]
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 783, in shell
    ensure_virtualenv(three=three, python=python)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 80, in ensure_virtualenv
    if not project.virtualenv_exists:
  File "/Library/Python/2.7/site-packages/pipenv/project.py", line 28, in virtualenv_exists
    return os.path.isdir(self.virtualenv_location)
  File "/Library/Python/2.7/site-packages/pipenv/project.py", line 32, in virtualenv_location
    return os.sep.join(self.pipfile_location.split(os.sep)[:-1] + ['.venv'])
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by nateprewitt** [comment]
Yep, looks like this affects `pipenv run` as well and is a direct result of f0cc4ad. I've decoupled finding the Pipfile's location from validating its contents in 54ed73b.

Thanks @dvachaiev! ✨
