### ISSUE TITLE
FileNotFound: 'pew'

### ISSUE THREAD

**Issue by khardix** [kennethreitz/pipenv#182]
When creating new project (== installing first dependency), I'm getting a `FileNotFound` exception:

```
$ pipenv install pelican
Creating a virtualenv for this project...
Traceback (most recent call last):
  File "/home/jstanek/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==3.3.1', 'console_scripts', 'pipenv')()
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py", line 704, in install
    ensure_project(three=three, python=python)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py", line 112, in ensure_project
    ensure_virtualenv(three=three, python=python)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py", line 95, in ensure_virtualenv
    do_create_virtualenv(three=three, python=python)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py", line 330, in do_create_virtualenv
    c = delegator.run(cmd, block=False)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/delegator.py", line 215, in run
    c.run(block=block)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/delegator.py", line 120, in run
    s = PopenSpawn(self._popen_args, **self._default_pexpect_kwargs)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pexpect/popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib64/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pew'
```

Pipenv was installed with pipsi (as per documentation), and this happen on versions 3.3.0, 3.3.1 and latest master commit in the time of writing (7e6affc).

By my estimation, this problem lies in pipsi not installing/linking the `pew` CLI script.

**Comment by nateprewitt** [comment]
Thanks for raising this issue @khardix, a couple of quick debugging questions.

Could you provide what `pipenv --version` and `pipenv run pip freeze` returns?

Could you also verify for me whether or not `$ pew` runs in your terminal?

**Comment by nateprewitt** [comment]
Also your Pipfile contents would be helpful.

**Comment by khardix** [comment]
I installed directly from github, since released pipenv-3.3.1 contains Python3 syntax error (which was fixed in 0d3a751). Install command: `pipsi install git+https://github.com/kennethreitz/pipenv#egg=pipenv`.

`$ pew` gives command not found -- it is not in my `$PATH`.

```
$ pipenv --version
pipenv, version 3.3.1
```
```
$ pipenv run pip freeze
Creating a virtualenv for this project...
Traceback (most recent call last):
  File "/home/jstanek/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==3.3.1', 'console_scripts', 'pipenv')()
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py", line 868, in run
    ensure_project(three=three, python=python, validate=False)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py", line 112, in ensure_project
    ensure_virtualenv(three=three, python=python)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py", line 95, in ensure_virtualenv
    do_create_virtualenv(three=three, python=python)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py", line 327, in do_create_virtualenv
    c = delegator.run(cmd, block=False)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/delegator.py", line 215, in run
    c.run(block=block)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/delegator.py", line 120, in run
    s = PopenSpawn(self._popen_args, **self._default_pexpect_kwargs)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/pexpect/popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib64/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pew'
```

Pipfile: No pipfile before the command, after:
```
$ cat Pipfile
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
```

**Comment by nateprewitt** [comment]
So it looks like pipsi installs everything but to a location that's not on the path by default. I'm able to reproduce this on Linux (Trusty) but wasn't able to on macOS.

`$ export PATH=$PATH/home/jstanek/.local/venvs/pipenv/bin`

Adding the environment to the path above will get you working for now. I'm going to need a bit of time to investigate why this is happening though.

**Comment by khardix** [comment]
For now, I have fixed it by installing `pew` explicitly, and it works. Take your time, and thanks for rapid response 👍.

**Comment by kennethreitz** [comment]
perhaps pipsi isn't the best installation method after all. i'll have to double check.

**Comment by kennethreitz** [comment]
updated installation instructions

**Comment by nateprewitt** [comment]
I think this should be addressed now with the documentation updates.
