### ISSUE TITLE
pipenv shell: UnicodeDecodeError: 'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by juanpabloaj** [kennethreitz/pipenv#201]
when I tried to use `pipenv shell`, I got this message

```
$ pipenv shell
Traceback (most recent call last):
  File "/Users/pablo/.local/bin/pew", line 11, in <module>
    sys.exit(pew())
  File "/Users/pablo/.local/venvs/pew/lib/python2.7/site-packages/pew/pew.py", line 737, in pew
    return command(sys.argv[2:])
  File "/Users/pablo/.local/venvs/pew/lib/python2.7/site-packages/pew/pew.py", line 356, in workon_cmd
    shell(env, cwd=project_dir)
  File "/Users/pablo/.local/venvs/pew/lib/python2.7/site-packages/pew/pew.py", line 201, in shell
    fork_bash(env, cwd)
  File "/Users/pablo/.local/venvs/pew/lib/python2.7/site-packages/pew/pew.py", line 159, in fork_bash
    rcfile.write(bashrc.read())
  File "/Users/pablo/.local/venvs/pew/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd4 in position 1225: invalid continuation byte
```

**Comment by nateprewitt** [comment]
Hey @juanpabloaj, it looks like you have some unicode characters in your .bashrc. This is causing pew to crash in Python 2. The two immediate fixes for this are either setting PIPENV_VENV_IN_PROJECT in your bash environment and creating a new project, or using Python 3.

I think we can also open an issue upstream with pew so they can try to handle this occurance. Thanks for letting us know about this!

**Comment by nateprewitt** [comment]
Sorry, disregard what I said about pew not handling Unicode. This seems to be that your .bashrc is encoded with non-utf-8 bytes (possibly Latin-1?). This is likely a default configuration for your OS setup. I've actually never had to deal with this before so I'll have to research what the best course of action is. For now I'd suggest set the flag listed above.

**Comment by juanpabloaj** [comment]
@nateprewitt thanks, I found this symbol in my `~/.bashrc`  :sweat_smile:

```
print '\xd4'.decode('latin-1')
Ô
```

when I removed the symbol, the problem was fixed, thanks again

**Comment by Freedomisgood** [comment]
It occured to me today, my os is win10, I solve the problem by reboot.

```python
Traceback (most recent call last):
  File "c:\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37-32\Scripts\pipenv.exe\__main__.py", line 5, in <module>
  File "c:\python37-32\lib\site-packages\pipenv\__init__.py", line 23, in <module>
    from .cli import cli
  File "c:\python37-32\lib\site-packages\pipenv\cli\__init__.py", line 3, in <module>
    from .command import cli
  File "c:\python37-32\lib\site-packages\pipenv\cli\command.py", line 7, in <module>
    import crayons
  File "c:\python37-32\lib\site-packages\pipenv\patched\crayons.py", line 49, in <module>
    is_powershell = "powershell" in shellingham.detect_shell()[0]
  File "c:\python37-32\lib\site-packages\pipenv\vendor\shellingham\__init__.py", line 22, in detect_shell
    shell = get_shell(pid, max_depth=max_depth)
  File "c:\python37-32\lib\site-packages\pipenv\vendor\shellingham\nt.py", line 100, in get_shell
    processes = dict(_iter_process())
  File "c:\python37-32\lib\site-packages\pipenv\vendor\shellingham\nt.py", line 78, in _iter_process
    info = {'executable': str(pe.szExeFile.decode('utf-8'))}
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte
```
