### ISSUE TITLE
pipenv --three error

### ISSUE THREAD

**Issue by dct360** [kennethreitz/pipenv#216]
$ python --version
Python 2.7.5
$ which python2
/bin/python2
 
$ python3 --version
Python 3.4.6
$ which python3
/usr/local/bin/python3
 
python 3.4.6 built from source with:
./configure
make altinstall
 
$ python3
Python 3.4.6 (default, Feb  9 2017, 11:06:31)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
 
$ pipenv --three
Creating a Pipfile for this project...
Creating a virtualenv for this project...
⠋Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1132, in install_python
    copy_required_modules(home_dir, symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1062, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1036, in change_prefix
    (filename, prefixes)
AssertionError: Filename /opt/Python-3.4.6/Lib/os.py does not start with any of these prefixes: ['/usr/local', '/usr/local']

**Comment by kennethreitz** [comment]
cannot reproduce.

does regular virtualenv work for you?

can you run `pew new -p python3 testproject`

**Comment by dct360** [comment]
$ pew new -p python3 testproject
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1132, in install_python
    copy_required_modules(home_dir, symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1062, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1036, in change_prefix
    (filename, prefixes)
AssertionError: Filename /opt/Python-3.4.6/Lib/os.py does not start with any of these prefixes: ['/usr/local', '/usr/local']
 
$ pip3.4 show virtualenv
Name: virtualenv
Version: 15.1.0
Summary: Virtual Python Environment builder
Home-page: https://virtualenv.pypa.io/
Author: Jannis Leidel, Carl Meyer and Brian Rosner
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /usr/local/lib/python3.4/site-packages
Requires:
$

**Comment by kennethreitz** [comment]
i'd raise this issue on pew then :)

**Comment by dct360** [comment]
ok thanks!

**Comment by nateprewitt** [comment]
And just to be clear @dct360, the stack trace shows that virtualenv is being run with your primary system Python (2.7). I'd try updating that if you haven't already.
