### ISSUE TITLE
ZSH autocomplete need psutil package

### ISSUE THREAD

**Issue by chenull** [kennethreitz/pipenv#226]
When doing `eval "$(_PIPENV_COMPLETE=source pipenv)"` i got this error:
```
$ pipenv --version
pipenv, version 3.4.1
```

```
Traceback (most recent call last):
  File "/Users/ayik/.local/venvs/pipenv/lib/python3.6/site-packages/click_completion.py", line 409, in get_auto_shell
    import psutil
ModuleNotFoundError: No module named 'psutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ayik/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/ayik/.local/venvs/pipenv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ayik/.local/venvs/pipenv/lib/python3.6/site-packages/click/core.py", line 692, in main
    _bashcomplete(self, prog_name, complete_var)
  File "/Users/ayik/.local/venvs/pipenv/lib/python3.6/site-packages/click_completion.py", line 297, in _shellcomplete
    echo(get_code(prog_name=prog_name, env_name=complete_var))
  File "/Users/ayik/.local/venvs/pipenv/lib/python3.6/site-packages/click_completion.py", line 387, in get_code
    shell = get_auto_shell()
  File "/Users/ayik/.local/venvs/pipenv/lib/python3.6/site-packages/click_completion.py", line 415, in get_auto_shell
    raise click.UsageError("Please explicitly give the shell type or install the psutil package to activate the"
click.exceptions.UsageError: Please explicitly give the shell type or install the psutil package to activate the automatic shell detection.
```

However, i can workaround this issue by installing psutil under pipenv virtualenvs. I installed pipenv using `pipsi`

Should pipenv explicitly state that it requires `psutil` ?

**Comment by nateprewitt** [comment]
This seems to be another case of #182. `pipsi` only installs exactly what you tell it to and ignores nested dependencies.

@kennethreitz, thoughts on adding an addendum to the documentation, or pulling the `pipsi` reference all together?

**Comment by kennethreitz** [comment]
maybe we should declare *all* of our dependencies instead.

**Comment by nateprewitt** [comment]
Ok, this should be addressed in 1937dd2 and will be available in the next release. Please feel free to reopen this is you find there's still a problem @chenull. Thanks again for letting us know!

**Comment by iScrE4m** [comment]
I feel bad re-opening an issue, but when the shoe fits:

```python
Traceback (most recent call last):
  File "/home/david/.local/lib/python3.5/site-packages/pipenv/vendor/click_completion.py", line 409, in get_auto_shell
    import psutil
  File "/home/david/.local/lib/python3.5/site-packages/pipenv/vendor/psutil/__init__.py", line 80, in <module>
    from . import _pslinux as _psplatform
  File "/home/david/.local/lib/python3.5/site-packages/pipenv/vendor/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux'
```

Using pipenv version 8.3.1

**Comment by techalchemy** [comment]
@iScrE4m try doing a full uninstall and reinstall of pipenv

@nateprewitt @erinxocon I've run into similar errors on and off, why are we vendoring psutil?  It needs to link to libraries in order to work properly and when it tries to use the vendored path for imports it seems to break a lot of things...
