### ISSUE TITLE
`pipenv install -r requirements.txt` fails with TypeError on pip-compile requirements file

### ISSUE THREAD

**Issue by paultiplady** [kennethreitz/pipenv#25]
Running `pipenv install -r` on a requirements.txt file generated by pip-compile gives an error:

```
$ pipenv install -r requirements.txt
Traceback (most recent call last):
  File "/Users/paul/.pyenv/versions/3.4.4/bin/pipenv", line 9, in <module>
    load_entry_point('pipenv==0.2.4', 'console_scripts', 'pipenv')()
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pipenv/cli.py", line 345, in install
    package_names = from_requirements_file(r)
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pipenv/cli.py", line 293, in from_requirements_file
    return [p for p in r.read().split('\n') if p and not p.startswith('#')]
TypeError: 'str' does not support the buffer interface
```

I've uploaded a [gist of the requirements file](https://gist.github.com/paultiplady/d140506dd03f11433d50d8add5772056).

**Comment by kennethreitz** [comment]
looks like we'll need to use `codecs.open` for python3 here.

**Comment by kennethreitz** [comment]
I would recommend installing it with python2 for now.

**Comment by kennethreitz** [comment]
this should be fixed now
