### ISSUE TITLE
Trailing comments cause parse error in `pipenv install -r requirements.txt`

### ISSUE THREAD

**Issue by paultiplady** [kennethreitz/pipenv#27]
Running `pipenv install -r requirements.txt` on a file with trailing comments (such as those generated by `pip-compile`) gives the following error:

```
$ pipenv install -r requirements.txt
Installing amqp==2.1.4               # via kombu...

Error:  An error occured while installing amqp==2.1.4               # via kombu
Invalid requirement: 'amqp==2.1.4               # via kombu'
Traceback (most recent call last):
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 26), (line:1, col:27)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/Users/paul/qwil/backend/.venv/lib/python3.4/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'# via ko'"
```

Looks like the requirements parser is just skipping lines which `startwith('#')` but looks like we need to be a bit more cunning to pluck out trailing comments.

**Comment by kennethreitz** [comment]
open to a PR! Should be an easy fix.

**Comment by kennethreitz** [comment]
Related: #25

**Comment by kennethreitz** [comment]
fixed!
