### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by stephenmuss** [kennethreitz/pipenv#310]
I'm getting the following error when attempting to create a new environment.

```
$ pipenv --three
Creating a Pipfile for this project...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 756, in cli
    ensure_project(three=three, python=python)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 134, in ensure_project
    ensure_pipfile(validate=validate)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 99, in ensure_pipfile
    if validate and project.virtualenv_exists:
  File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 43, in virtualenv_exists
    return os.path.isdir(self.virtualenv_location)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 80, in virtualenv_location
    loc = c.out.strip()
  File "/usr/local/lib/python3.5/dist-packages/delegator.py", line 89, in out
    self.__out = self.std_out.read()
ValueError: I/O operation on closed file.
```

This is using pipenv 3.5.6 but it also happens if I downgrade to earlier versions.

Using Ubuntu 16.04.2 LTS.

**Comment by nateprewitt** [comment]
Hey @stephenmuss, this is a bug in delegator.py rather than pipenv. If you install delegator.py==0.0.8 you should find joe problem is solved. We should have this resolved in the next release of delegator.py or pipenv.

**Comment by nateprewitt** [comment]
Please feel free to reopen this if you continue to find problems.

**Comment by stephenmuss** [comment]
That worked. Thank you.
