### ISSUE TITLE
ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by generalavc** [kennethreitz/pipenv#316]
I am getting this with pipenv 3.4.2 and 3.5.6. Running any pipenv command, Ubuntu 16.04. pew is installed, per issue 195. pip is upgraded to latest 9.0.1. 

`Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/rmsadmin/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rmsadmin/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rmsadmin/.local/lib/python3.5/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/rmsadmin/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rmsadmin/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rmsadmin/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 756, in cli
    ensure_project(three=three, python=python)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 134, in ensure_project
    ensure_pipfile(validate=validate)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 99, in ensure_pipfile
    if validate and project.virtualenv_exists:
  File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 43, in virtualenv_exists
    return os.path.isdir(self.virtualenv_location)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 80, in virtualenv_location
    loc = c.out.strip()
  File "/usr/local/lib/python3.5/dist-packages/delegator.py", line 89, in out
    self.__out = self.std_out.read()
ValueError: I/O operation on closed file.`

**Comment by nateprewitt** [comment]
Thanks for opening this @generalavc, this is actually a bug in delegator.py and a dup of #310. Please follow the instructions there to fix the issue.

**Comment by generalavc** [comment]
super! thanks, I didn't find that before.
