### ISSUE TITLE
FileNotFoundError during install on Windows

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#334]
https://github.com/kennethreitz/pipenv/issues/213 is fixed, but now I'm seeing a different error in one of my Windows builds on AppVeyor (https://ci.appveyor.com/project/jacebrowning/env-diff/build/1.0.41):

```
$ pipenv install --dev --ignore-hashes
No package provided, installing all dependencies.
Pipfile found at C:\projects\env-diff\Pipfile. Considering this to be the project home.
Installing dependencies from Pipfile.lock...
An error occured while installing!
Traceback (most recent call last):
  File "C:\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\projects\env-diff\.venv\Scripts\pip.exe\__main__.py", line 9, in <module>
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\__init__.py", line 233, in main
    return command.main(cmd_args)
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\basecommand.py", line 252, in main
    pip_version_check(session)
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\utils\outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\utils\__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\projects\\env-diff\\.venv\\lib\\site-packages\\colorama-0.3.9-py3.6.egg'
```

This is using pipenv 3.6.0 and reinstalling the latest version of pip per @nateprewitt's suggestion.

**Comment by nateprewitt** [comment]
Hey @jacebrowning, so as I said in the other issue, this stacktrace doesn't actually touch any pipenv code but is raised from `pip` itself. I'm doing a little bit of digging to see if I can pinpoint why but this isn't a high priority at the moment.

For now, simply running `pipenv lock` and updating your Pipfile.lock fixes the problem. I'm not sure if you somehow have a bad lockfile or if there's another issue yet.

**Comment by jacebrowning** [comment]
Here is the `Pipfile.lock`: https://github.com/jacebrowning/env-diff/blob/cb2a8763898f70f6a48a13d6ad2ef7dc139cdf16/Pipfile.lock

Weirdly, `Pipfile.lock` calls out "==0.3.7" for colorama, but the error is about a missing "colorama-0.3.9-py3.6.egg".

**Comment by nateprewitt** [comment]
@jacebrowning, yeah, that's one of the anomalies that needs to be looked at. If you update that Pipfile.lock, the error goes away, at least from my experiments in appveyor earlier. That will get env-diff running for now.

**Comment by jacebrowning** [comment]
@nateprewitt Thanks for the tip! My dependencies install correctly after `rm Pipfile.lock; pipenv install`. I don't know how my `Pipfile.lock` got into a bad state, but it would be nice if pipenv could catch this and provide a more helpful error message.

**Comment by kennethreitz** [comment]
closing due to age. will pop up again if it's an issue.
