### ISSUE TITLE
Pipenv crashes on every command

### ISSUE THREAD

**Issue by rubik** [kennethreitz/pipenv#340]
From a fresh install, running any command will result in the following error:
```
$ pipenv --three
Traceback (most recent call last):
  File "/home/user/exp/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/user/exp/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/exp/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/exp/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/user/exp/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/exp/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/exp/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/exp/lib/python3.6/site-packages/pipenv/cli.py", line 798, in cli
    ensure_project(three=three, python=python)
  File "/home/user/exp/lib/python3.6/site-packages/pipenv/cli.py", line 160, in ensure_project
    ensure_pipfile(validate=validate)
  File "/home/user/exp/lib/python3.6/site-packages/pipenv/cli.py", line 125, in ensure_pipfile
    if validate and project.virtualenv_exists:
  File "/home/user/exp/lib/python3.6/site-packages/pipenv/project.py", line 48, in virtualenv_exists
    return os.path.isdir(self.virtualenv_location)
  File "/home/user/exp/lib/python3.6/site-packages/pipenv/project.py", line 85, in virtualenv_location
    loc = c.out.strip()
  File "/home/user/exp/lib/python3.6/site-packages/delegator.py", line 89, in out
    self.__out = self.std_out.read()
ValueError: I/O operation on closed file.
```

**Comment by nateprewitt** [comment]
@rubik can you please confirm for me you have `delegator.py 0.0.9` installed and then upgrade to `delegator.py 0.0.10` to see if that solves the issue? This *should be* a bug there and not in pipenv.

**Comment by rubik** [comment]
@nateprewitt Confirmed, it was `delegator.py==0.0.9` which caused the issue. Upgrading solved it. Thanks!

**Comment by nateprewitt** [comment]
@rubik glad it worked!
