### ISSUE TITLE
The 'pipenv==3.6.2' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by iScrE4m** [kennethreitz/pipenv#355]
System: Ubuntu 16.10
Python version: Python 3.5.2
Pip version: 9.0.1
Installed with: `pip install pipenv --user`
Output doing anything:
```bash
 > per…nal> RSES > pipenv --help                       < 1 ↵ < 0  < master    < 17:37 
Traceback (most recent call last):
  File "/home/david/.local/bin/pipenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/david/rses/lib/python3.6/site-packages/setuptools-28.8.0-py3.6.egg/pkg_resources/__init__.py", line 3017, in <module>
  File "/home/david/rses/lib/python3.6/site-packages/setuptools-28.8.0-py3.6.egg/pkg_resources/__init__.py", line 3003, in _call_aside
  File "/home/david/rses/lib/python3.6/site-packages/setuptools-28.8.0-py3.6.egg/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
  File "/home/david/rses/lib/python3.6/site-packages/setuptools-28.8.0-py3.6.egg/pkg_resources/__init__.py", line 659, in _build_master
  File "/home/david/rses/lib/python3.6/site-packages/setuptools-28.8.0-py3.6.egg/pkg_resources/__init__.py", line 967, in require
  File "/home/david/rses/lib/python3.6/site-packages/setuptools-28.8.0-py3.6.egg/pkg_resources/__init__.py", line 853, in resolve
pkg_resources.DistributionNotFound: The 'pipenv==3.6.2' distribution was not found and is required by the application
```

Lower versions (3.6.0 and 3.6.1) give me:
```bash
Traceback (most recent call last):
  File "/home/david/.local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/home/david/.local/lib/python3.5/site-packages/pipenv/__init__.py", line 14, in <module>
    from .cli import cli
  File "/home/david/.local/lib/python3.5/site-packages/pipenv/cli.py", line 12, in <module>
    import click_completion
  File "/home/david/.local/lib/python3.5/site-packages/pipenv/vendor/click_completion.py", line 16, in <module>
    from click import echo, MultiCommand, Option, Argument, ParamType
ImportError: cannot import name 'echo'

```

**Comment by nateprewitt** [comment]
Hey @iScrE4m, this definitely seems like an issue in your local environment. `pipenv==3.6.2` is available on PyPI as listed [here](https://pypi.python.org/simple/pipenv/). Are you using a third-party PyPI endpoint?

As for the second issue, you're using a different version of Python (Python 3.5) from the first example (Python 3.6). Do you have a local file called `click.py` in your project? If not which version of `click` do you have installed in Python 3.5?

**Comment by iScrE4m** [comment]
Hi, yeah that was weird. the first example probably used virtualenv, despite it being deactivated one command above and then something weird happened - otherwsie I can't explain python3.6.

The click I had installed was version `click-0.4.45.1+16.10.20160916.0ubuntu1` - so i reinstalled pip version and pipenv now works. My bad, sorry :)

**Comment by nateprewitt** [comment]
No worries, glad you got it sorted 😊
