### ISSUE TITLE
Clean install of pipenv not working

### ISSUE THREAD

**Issue by lunemec** [kennethreitz/pipenv#361]
Hello, when doing a clean pipenv install inside debian docker container, the `requests` dependency is installed in incorrect version:

Please note that the docker image has previous version of requests installed:
```
requests==2.4.3
```

```
sudo pip install pip --upgrade
```
Upon fresh pipenv install:
```
sudo pip install pipenv

Collecting pipenv
  Downloading pipenv-4.0.1-py2-none-any.whl (669kB)
    100% |████████████████████████████████| 675kB 1.6MB/s
Collecting pew>=0.1.26 (from pipenv)
  Downloading pew-0.1.26-py2.py3-none-any.whl
Requirement already satisfied: pip in /usr/local/lib/python2.7/dist-packages (from pipenv)
Requirement already satisfied: virtualenv in /usr/local/lib/python2.7/dist-packages (from pipenv)
Collecting pathlib; python_version == "2.7" (from pew>=0.1.26->pipenv)
  Downloading pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 7.3MB/s
Requirement already satisfied: setuptools>=17.1 in /usr/local/lib/python2.7/dist-packages (from pew>=0.1.26->pipenv)
Collecting shutilwhich; python_version == "2.7" (from pew>=0.1.26->pipenv)
  Downloading shutilwhich-1.1.0.tar.gz
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv)
  Downloading virtualenv-clone-0.2.6.tar.gz
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from pew>=0.1.26->pipenv)
Collecting pythonz-bd>=1.10.2 (from pew>=0.1.26->pipenv)
  Downloading pythonz-bd-1.11.4.tar.gz (86kB)
    100% |████████████████████████████████| 92kB 5.3MB/s
Building wheels for collected packages: pathlib, shutilwhich, virtualenv-clone, pythonz-bd
  Running setup.py bdist_wheel for pathlib ... done
  Stored in directory: /root/.cache/pip/wheels/2a/23/a5/d8803db5d631e9f391fe6defe982a238bf5483062eeb34e841
  Running setup.py bdist_wheel for shutilwhich ... done
  Stored in directory: /root/.cache/pip/wheels/0e/28/70/d5cc6586f26d614b26901485f6f6072d35cbbb5bbeffb6ea43
  Running setup.py bdist_wheel for virtualenv-clone ... done
  Stored in directory: /root/.cache/pip/wheels/24/51/ef/93120d304d240b4b6c2066454250a1626e04f73d34417b956d
  Running setup.py bdist_wheel for pythonz-bd ... done
  Stored in directory: /root/.cache/pip/wheels/04/de/c8/da2d21bb0112bb65bfb28bdf9ee8f2c819c25db143c32435b2
Successfully built pathlib shutilwhich virtualenv-clone pythonz-bd
Installing collected packages: pathlib, shutilwhich, virtualenv-clone, pythonz-bd, pew, pipenv
Successfully installed pathlib-1.0.1 pew-0.1.26 pipenv-4.0.1 pythonz-bd-1.11.4 shutilwhich-1.1.0 virtualenv-clone-0.2.6
```

Pipenv raises error when executing:
```
pipenv
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/usr/local/lib/python2.7/dist-packages/pipenv/__init__.py", line 14, in <module>
    from .cli import cli
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 21, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning
```

After upgrading requests
```
sudo pip install requests --upgrade

Collecting requests
  Downloading requests-2.14.2-py2.py3-none-any.whl (560kB)
    100% |████████████████████████████████| 563kB 1.5MB/s
Installing collected packages: requests
  Found existing installation: requests 2.4.3
    Uninstalling requests-2.4.3:
      Successfully uninstalled requests-2.4.3
Successfully installed requests-2.14.2
```

it works
```
pipenv
Usage: pipenv [OPTIONS] COMMAND [ARGS]...

Options:
  --where          Output project home information.
  --venv           Output virtualenv information.
  --rm             Remove the virtualenv.
  --bare           Minimal output.
  --three / --two  Use Python 3/2 when creating virtualenv.
  --python TEXT    Specify which version of Python virtualenv should use.
  -h, --help       Show this message then exit.
  --version        Show the version and exit.


Usage Examples:
   Create a new project using Python 3:
   $ pipenv --three

   Install all dependencies for a project (including dev):
   $ pipenv install --dev

   Create a lockfile:
   $ pipenv lock

Commands:
  check      Checks PEP 508 markers provided in Pipfile.
  install    Installs provided packages and adds them to...
  lock       Generates Pipfile.lock.
  run        Spawns a command installed into the...
  shell      Spawns a shell within the virtualenv.
  uninstall  Un-installs a provided package and removes it...
  update     Updates pip to latest version, uninstalls all...
```

I'm not sure if this is issue with `pip` not detecting I have a older version of requests installed, but when doing `pip install pipenv` it doesn't show `requests` in the collected dependencies, nor does it say that dependency is already satisfied.

Thank you.

**Comment by kennethreitz** [comment]
This was an issue with your pip installation.
