### ISSUE TITLE
"NameError: name 'hashed_deps_path' is not defined"

### ISSUE THREAD

**Issue by edmorley** [kennethreitz/pipenv#371]
With pipenv 4.1.0, whilst running the heroku/heroku-buildpack-python test suite (which runs `pipenv lock --requirements`), I get:
```
Traceback (most recent call last):
  File "/app/.heroku/python/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/tmp/testGjA6x/.heroku/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/testGjA6x/.heroku/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/testGjA6x/.heroku/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/testGjA6x/.heroku/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/testGjA6x/.heroku/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/cli.py", line 944, in lock
    do_init(dev=True, requirements=requirements, no_hashes=no_hashes)
  File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/cli.py", line 618, in do_init
    ignore_hashes=ignore_hashes)
  File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/cli.py", line 257, in do_install_dependencies
    with open(hashed_deps_path) as f:
NameError: name 'hashed_deps_path' is not defined>
```

**Comment by kennethreitz** [comment]
Thanks! We just cut this release.

**Comment by nateprewitt** [comment]
I'll have a hotfix up shortly, thanks @edmorley!

**Comment by nateprewitt** [comment]
Alright, this is resolved in 452764d9 and now available on PyPI in 4.1.1. Thanks again @edmorley.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by edmorley** [comment]
Many thanks! I've opened #372 to add flake8 to the Travis run, to help catch cases like this :-)
