### ISSUE TITLE
`pipenv install` with no arguments results in UnboundLocalError

### ISSUE THREAD

**Issue by anowlcalledjosh** [kennethreitz/pipenv#377]
```
$ pipenv install
Creating a Pipfile for this project...
Creating a virtualenv for this project...
⠋Using base prefix '/usr'
New python executable in /home/josh/.local/share/virtualenvs/pipenv-test-42RWOVQR/bin/python3
Also creating executable in /home/josh/.local/share/virtualenvs/pipenv-test-42RWOVQR/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/josh/.local/share/virtualenvs/pipenv-test-42RWOVQR
No package provided, installing all dependencies.
Pipfile found at /tmp/pipenv-test/Pipfile. Considering this to be the project home.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
⠸Locking [packages] dependencies...
⠴Updated Pipfile.lock!
Installing dependencies from Pipfile.lock...
[================================] 0/0 - 00:00:00
Traceback (most recent call last):
  File "/home/josh/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 827, in install
    do_init(dev=dev, allow_global=system, ignore_hashes=ignore_hashes, ignore_pipfile=ignore_pipfile)
  File "/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 616, in do_init
    ignore_hashes=ignore_hashes)
  File "/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 279, in do_install_dependencies
    if c.return_code != 0:
UnboundLocalError: local variable 'c' referenced before assignment
```

Presumably, the fix to this would be to indent [lines 279–285 of cli.py](https://github.com/kennethreitz/pipenv/blob/master/pipenv/cli.py#L279,L285) to be included in the `if len(vcs_deps):`.

**Comment by kennethreitz** [comment]
I've run into this myself.

**Comment by nateprewitt** [comment]
@kennethreitz do you recall why `if len(vcs_deps)` was added? If not, I don't see a reason why we can't remove it. Otherwise, the other option is to indent the error handling inside of that conditional.

**Comment by iandees** [comment]
Is there a workaround until this is fixed?

**Comment by nateprewitt** [comment]
@iandees, we're currently having some trouble with our CI, but I have a patch ready to go for this. I'm going to try to get a bugfix release out in the next few hours.

**Comment by iandees** [comment]
Ok great, thanks @nateprewitt!

**Comment by kennethreitz** [comment]
@nateprewitt should be working now
