### ISSUE TITLE
Strange error after upgrade on ubuntu 16.04

### ISSUE THREAD

**Issue by SergeyPirogov** [kennethreitz/pipenv#387]
pipenv, version 4.1.0
python 2.7.12

When trying to install any package:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 857, in install
    project.add_package_to_pipfile(package_name, dev)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/project.py", line 251, in add_package_to_pipfile
    self.write_toml(recase_file(p))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 228, in recase_file
    cased_key = proper_case(key)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 189, in proper_case
    r = requests.get('https://pypi.org/pypi/{0}/json'.format(package_name), timeout=1, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 411, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 528, in load_verify_locations
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

**Comment by nateprewitt** [comment]
Hey @SergeyPirogov, it looks like you have something wrong much deeper than Pipenv. OpenSSL is unable to find your root cert for some reason.

My first thought it to try uninstalling pyopenssl and reinstalling it. If that doesn't work. If that doesn't fix it, it could be outside of Python even.

If that doesn't work, could you please supply me with the output of the following commands.

1.) `$ openssl version`
2.) `$ python --version`
3.) `$ pip freeze`

Thanks!

**Comment by SergeyPirogov** [comment]
It seems that I solved it, just by upgrading requests. I think it should be upgraded automatically.

**Comment by nateprewitt** [comment]
I'm glad everything is working as expected now @SergeyPirogov. Unfortunately we can't adjust dependencies when an upgrade is performed on the operating system. I've got a feeling that Ubuntu may have adjusted the system installed version of requests which may have caused your problem.

Hopefully this issue will help anyone else who experiences this problem. Let us know if you have any further questions.
