### ISSUE TITLE
Error generating requirements file with `pipenv lock -r` in 4.1.2 and 4.1.3

### ISSUE THREAD

**Issue by lpomfrey** [kennethreitz/pipenv#390]
Trying to create a requirements.txt file with `pipenv lock -r` in 4.1.2 or 4.1.3 (4.1.1 is fine) fails with the following traceback:

    Traceback (most recent call last):
      File "/.local/bin/pipenv", line 11, in <module>
        sys.exit(cli())
      File "~/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "~/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "~/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "~/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "~/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "~/.local/lib/python3.5/site-packages/pipenv/cli.py", line 927, in lock
        do_init(dev=True, requirements=requirements, no_hashes=no_hashes)
      File "~/.local/lib/python3.5/site-packages/pipenv/cli.py", line 601, in do_init
        ignore_hashes=ignore_hashes)
      File "~/.local/lib/python3.5/site-packages/pipenv/cli.py", line 258, in do_install_dependencies
        click.echo('\n'.join(deps_list))
    TypeError: sequence item 0: expected str instance, tuple found

This seems to occur for any given Pipfile.

**Comment by nateprewitt** [comment]
Hey @lpomfrey, thanks for opening this ticket! This was definitely an oversight, I've fixed the issue and added a test to catch this kind of failure in the future. Things should be fixed in the next release which I'll try to get out sometime this afternoon.

**Comment by lpomfrey** [comment]
Wow, awesome turnaround. Thanks, @nateprewitt.

**Comment by nateprewitt** [comment]
4.1.4 is now available on PyPI. Cheers @lpomfrey 🍻
