### ISSUE TITLE
shell completion fails due to missing jinja2

### ISSUE THREAD

**Issue by hwine** [kennethreitz/pipenv#409]
I installed pew & pip via pipsi, following the instructions for [fancy installation](http://docs.pipenv.org/en/latest/advanced.html#fancy-installation-of-pipenv).

With that setup, shell completion fails following the [shell completion](http://docs.pipenv.org/en/latest/advanced.html#shell-completion) instructions:

```
$ . ~/.local/venvs/pipenv/bin/activate
$ pip freeze | grep jin
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ deactivate
$ env _PIPENV_COMPLETE=source-bash pipenv
Traceback (most recent call last):
  File "/Users/hwine/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/hwine/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hwine/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 692, in main
    _bashcomplete(self, prog_name, complete_var)
  File "/Users/hwine/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click_completion.py", line 299, in _shellcomplete
    echo(get_code('bash', prog_name, complete_var))
  File "/Users/hwine/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click_completion.py", line 385, in get_code
    from jinja2 import Template
ImportError: No module named jinja2
```

Various versions:
```
$ pew version
0.1.26
$ pipenv --version
pipenv, version 5.0.0
$ uname -a
Darwin hwin-28520.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```

**Comment by nateprewitt** [comment]
I have a feeling this is directly related to `pipsi`. Could you please try installing pipenv with pip instead?

**Comment by hwine** [comment]
Same issue -- I am installing under `pyenv`:

```
$ pyenv virtualenv --python /usr/bin/python pyenv_test
Running virtualenv with interpreter /usr/bin/python
New python executable in /Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/bin/python
Installing setuptools, pip, wheel...done.
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages
0 [hwine@hwin-28520 ~]
$ cd /tmp/pipenv/
$ pyenv local pyenv_test
$ python --version
Python 2.7.10
$ pip install pipenv
Collecting pipenv
  Using cached pipenv-5.0.0-py2-none-any.whl
Collecting virtualenv (from pipenv)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Collecting pew>=0.1.26 (from pipenv)
  Using cached pew-0.1.26-py2.py3-none-any.whl
Requirement already satisfied: pip in /Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages (from pipenv)
Collecting pathlib; python_version == "2.7" (from pew>=0.1.26->pipenv)
Requirement already satisfied: setuptools>=17.1 in /Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages (from pew>=0.1.26->pipenv)
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from pew>=0.1.26->pipenv)
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting shutilwhich; python_version == "2.7" (from pew>=0.1.26->pipenv)
Collecting pythonz-bd>=1.10.2 (from pew>=0.1.26->pipenv)
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv)
Installing collected packages: virtualenv, pathlib, backports.shutil-get-terminal-size, shutilwhich, pythonz-bd, virtualenv-clone, pew, pipenv
Successfully installed backports.shutil-get-terminal-size-1.0.0 pathlib-1.0.1 pew-0.1.26 pipenv-5.0.0 pythonz-bd-1.11.4 shutilwhich-1.1.0 virtualenv-15.1.0 virtualenv-clone-0.2.6
$ pip freeze | grep jin
$ env _PIPENV_COMPLETE=source-bash pipenv
Traceback (most recent call last):
  File "/Users/hwine/.pyenv/versions/pyenv_test/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 692, in main
    _bashcomplete(self, prog_name, complete_var)
  File "/Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages/pipenv/vendor/click_completion.py", line 299, in _shellcomplete
    echo(get_code('bash', prog_name, complete_var))
  File "/Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages/pipenv/vendor/click_completion.py", line 385, in get_code
    from jinja2 import Template
ImportError: No module named jinja2
```

**Comment by hwine** [comment]
FTR - pip version:
$ pip --version
pip 9.0.1 from /Users/hwine/.pyenv/versions/3.5.2/envs/pyenv_test/lib/python2.7/site-packages (python 2.7)

**Comment by kennethreitz** [comment]
I have also run into this — I suspect pip-completion doesn't properly depend on jinjia2

**Comment by kennethreitz** [comment]
I'm sure pip is behaving as expected. I think jinjia2 just needs to be added to `setup.py`.

**Comment by nateprewitt** [comment]
`jinja2` is bundled with pipenv in the `vendor` directory though which is why I'm confused. I believe it should be finding it on the path as soon as pipenv runs. Adding it to setup.py means it's installed twice.

**Comment by hwine** [comment]
> ``jinja2`` is bundled with pipenv in the ``vendor`` directory

I'm only starting to learn python packaging, but I see ``setup.py`` explicitly citing vendor packages from the ``vendor`` directory, but jinja2 is not one of them.

I look forward to learning the resolution. :)

**Comment by nateprewitt** [comment]
Thanks for pointing that out @hwine, I'm being particularly dense today. I've pushed 038a3d7 adding jinja2 to the packages list in setup.py. If you have a spare moment could you try installing from the master branch and see if your problem is resolved?

**Comment by hwine** [comment]
Woot! That worked!
```
$ env _PIPENV_COMPLETE=source-bash pipenv

_pipenv_completion() {
    local IFS=$'\t'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _PIPENV_COMPLETE=complete-bash $1 ) )
    return 0
}

complete -F _pipenv_completion -o default pipenv
```

**Comment by nateprewitt** [comment]
@hwine, great to hear! I'm in the process of cleaning up some loose ends and I'll push 5.1.0 in the next couple hours. I'm going to close this as resolved since it will be fixed in the next release. Cheers!
