### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by worudso** [kennethreitz/pipenv#410]
```
*D:\productexporter>pipenv --three --python python
Creating a virtualenv for this project...
Using python to create virtualenv...
Traceback (most recent call last):
  File "C:\Users\sandbox\AppData\Local\Programs\Python\Python36-32\Scripts\pipenv-script.py", line 11, in <module>
    load_entry_point('pipenv==5.0.0', 'console_scripts', 'pipenv')()
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\cli.py", line 780, in cli
    ensure_project(three=three, python=python)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\cli.py", line 162, in ensure_project
    ensure_virtualenv(three=three, python=python)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\cli.py", line 137, in ensure_virtualenv
    do_create_virtualenv(three=three, python=python)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\cli.py", line 396, in do_create_virtualenv
    click.echo(crayons.blue(c.out), err=True)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\delegator.py", line 91, in out
    self.__out = self._pexpect_out
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\delegator.py", line 79, in _pexpect_out
    result += self.subprocess.read()
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\pexpect\spawnbase.py", line 413, in read
    self.expect(self.delimiter)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\pexpect\spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\pexpect\spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\pexpect\expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "c:\users\sandbox\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\pexpect\popen_spawn.py", line 84, in read_nonblocking
    buf += self._decoder.decode(incoming, final=False)
  File "c:\users\hplusmall\appdata\local\programs\python\python36-32\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 97: invalid start byte
```

Pipenv initialization with python 3 in windows doesn't work. Only python 3.6.1 is installed and `python` is aliased to python 3.6.1.

I tried
```
pipenv --three
pipenv --python python
pipenv --three --python python
```
these 3 commands, and they gave me same message like above.

**Comment by jacebrowning** [comment]
If you have a `Pipfile` in your project, make sure all the characters are ASCII.

**Comment by nateprewitt** [comment]
Hey @worudso, it appears you may have a `Á` character in your path. The issue is that a character being returned by the virtualenv creation command but it's encoded as `latin-1` instead of `utf-8`.

Could you please run the command `pew new productexporter -d -p python` for me and see if the output contains that character? Thanks!

**Comment by worudso** [comment]
@nateprewitt 
```
pew new productexporter -d -p python
The path python (from --python=python) does not exist
Error while trying to remove the C:\Users\sandbox\.virtualenvs\productexporter env:
Cannot find directory #The original message was korean
```
I don't think this is what you expected. The virtualenv directory was not even initalized.

**Comment by nateprewitt** [comment]
@worudso there are a few things that are strange here. The message `--python=python does not exist` is the first one that stands out. You said that `python` is bound to 3.6.1? Does `python` launch the interpreter in your terminal?

If you delete `C:\Users\sandbox\.virtualenvs\productexporter env` and run `pew new productexporter -d`, does that have any different effect?

Also, do you happen to be using any characters from the CJK character set in any of your directories or as a terminal encoding default?

**Comment by nateprewitt** [comment]
@worudso, I'm closing this issue due to inactivity but please feel free to provide answers to any of the questions above. At that time we can look into reopening this issue and moving forward.
