### ISSUE TITLE
problem starting pipenv on MacPorts

### ISSUE THREAD

**Issue by gruntfarm** [kennethreitz/pipenv#411]
Hi,

I can't seem to be able to start pipenv after installing it. I don't know if I'm missing a step in the installation process or maybe my setup is not compatible.

I am using pip via MacPorts so my priority PATH locations are  `/opt/local/bin` and `/opt/local/sbin`. I am also using fish as my shell replacement (I actually was introduced to it and started using it because of the shell completion line in your documentation) and using virtualfish with the compatibility aliases activated to allow standard virtualenvwrapper commands (workon, deactivate.. etc).

I installed pipenv by doing `sudo pip install pipenv`. But after I try typing any of the pipenv commands I get `fish: Unknown command 'pipenv'`. Fish seems to recognize all my other usual commands except pipenv for some reason.

**Comment by nateprewitt** [comment]
Hey @gruntfarm, thanks for taking the time to open this issue. So first off, I would *strongly* advise never using `sudo` with pip install commands. This can have unexpected side effects to system level modules and should be unneeded on macOS.

First we'll need to determine where `sudo pip install` actually put pipenv, and then determine whether that location is on the PATH. I'm assuming it's not because it can't find pipenv. Have you tried installing pipenv without sudo?

**Comment by gruntfarm** [comment]
Hi @nateprewitt thanks for your response. using sudo pip install seems to have placed pipenv into `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv`

If I do just `pip install pipenv`, the install fails because using the MacPorts version of pip seems to want to place all pip installs into that /opt/local/ directory.

I can do `pip install pipenv --user` and that installs it into `/Users/$USER/Library/Python/2.7/lib/python/site-packages/pipenv` but again I still can't activate the pipenv command because that location is not on my PATH

**Comment by nateprewitt** [comment]
@gruntfarm, so this very much seems to be an issue with your environment/macports, rather than pipenv. According to [this Stackoverflow](https://stackoverflow.com/questions/6147035/locate-macports-package/6147071#6147071), you may need to add this directory to your PYTHONPATH.

```bash
$ export PYTHONPATH=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
```

Either way, I don't know if there's much for us to do from the pipenv side, so I'm going to close this out for now. Feel free to leave additional comments if you find any additional information not already provided here.

**Comment by nateprewitt** [comment]
It looks like alternatively, you may supposed to be using `python-select` to make sure you're using the correct Python install. I'm not positive though because I don't have any experience with MacPorts.

**Comment by gruntfarm** [comment]
Hm yes I have both that path and `/opt/local/lib/python/site-packages` on my PYTHONPATH.  Not sure what could be causing the issue. Looks like I'll have to stick to using virtualenvwrapper and pip separeately for now.

**Comment by gruntfarm** [comment]
Ok new development. I hope I can post in here even though the issue is closed.

So I was able to run pipenv with this command `python -m pipenv install`, but when I do, this is the error I get:
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/__main__.py", line 4, in <module>
    cli()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/cli.py", line 960, in shell
    ensure_project(three=three, python=python, validate=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/cli.py", line 162, in ensure_project
    ensure_virtualenv(three=three, python=python)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/cli.py", line 137, in ensure_virtualenv
    do_create_virtualenv(three=three, python=python)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/cli.py", line 395, in do_create_virtualenv
    c = delegator.run(cmd, block=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 247, in run
    c.run(block=block, binary=binary)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 146, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by nateprewitt** [comment]
@gruntfarm, can you tell me what the output of `python -m pipenv --venv` is?

**Comment by gruntfarm** [comment]
I get this message
`No virtualenv has been created for this project yet!`

Also just running pipenv like that without any arguments gives me the standard usage/commands doc.

**Comment by gruntfarm** [comment]
Ok so I installed pipsi and pew (via pipsi) and added the pew and pipsi location to the PATH (different from the /opt/local one) and now the install command works!

But I still have to prepend with python -m, and just pipenv still isn't recognized as a shell command.

**Comment by kennethreitz** [comment]
@gruntfarm want to hop on a hangouts?

**Comment by gruntfarm** [comment]
Ooh I'd love to except I'm at my 9-5 right now which doesn't have anything to do with development (so I couldn't pass it off as work-related). But I could probably do it tonight around 8pm EST (sorry not sure what timezone you are in)

**Comment by kennethreitz** [comment]
@gruntfarm ping me then and i'll see if i'm online!
