### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#413]
I maintain a [sample project](https://github.com/jacebrowning/template-python-demo) using pipenv and it regularly fails to install on Windows with Python 2 on Appveyor:

<img width="471" alt="screen shot 2017-06-14 at 11 36 18 am" src="https://user-images.githubusercontent.com/939501/27141313-d2b84d5c-50f5-11e7-8d0a-9a3bb3a70f67.png">

The [error](https://ci.appveyor.com/project/jacebrowning/template-python-demo/build/1.0.617) appears to be coming from a cleanup utility deep inside pip:

```
Virtualenv location: C:\projects\template-python-demo\.venv

$ pipenv run pip --version
pip 9.0.1 from c:\projects\template-python-demo\.venv\lib\site-packages (python 2.7)

$ pipenv install --dev
No package provided, installing all dependencies.
Pipfile found at C:\projects\template-python-demo\Pipfile. Considering this to be the project home.
Installing dependencies from Pipfile.lock...
An error occured while installing!
Collecting testpackage==2.27
  Downloading testpackage-2.27.zip
Requirement already satisfied: setuptools in c:\projects\template-python-demo\.venv\lib\site-packages (from testpackage==2.27)
Building wheels for collected packages: testpackage
  Running setup.py bdist_wheel for testpackage: started
  Running setup.py bdist_wheel for testpackage: finished with status 'done'
  Stored in directory: C:\Users\appveyor\AppData\Local\pip\Cache\wheels\ef\9a\e8\70da16958d7243bfc4e55406d3d19a0d9fa99cf8c116538bdd

Exception:
Traceback (most recent call last):
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Python27\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\Lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\projects\template-python-demo\.venv\lib\site-packages\pip\utils\__init__.py", line 110, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
WindowsError: [Error 2] The system cannot find the file specified: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-build-m6t36c\\testpackage\\ma\xa8dchen.c'
```

While this may not be the responsibility of pipenv, it would be great if pipenv could swallow up this error because it appears that my dependencies installed correctly otherwise.

**Comment by nateprewitt** [comment]
Hey @jacebrowning, this looks like it's definitely outside of the scope of `pipenv`.

The issue here seems to be character encoding in Python 2. Python 3 correctly decodes a daieresis (`¨`) and combines it with the `a` as you'd expect. Python 2 however is choking on `\xa8` as a bytestring and unable to properly locate the file. My feeling is this will happen anytime you build this wheel on windows with Python 2.

**Comment by nateprewitt** [comment]
Sorry, I didn't clarify that I'm referring to the `testpackage` module you're installing with the project.
