### ISSUE TITLE
Uanble to run subliminl ubuntu 16.04

### ISSUE THREAD

**Issue by thomasloldk** [kennethreitz/pipenv#424]
Hey guys !  , I'm no programmer or python expert  but I  usually know my way arround. these kind of stuff

When im running the script it collets videos , But is unable to download the subs. 
`thomas@customer:~$ subliminal download -l da tv/the\ big\ bang\ theory/The\ Big\ Bang\ Theory\ Season\ 09\ \(720p\)\ S09\ Complete\ 9\ MP4\ AAC\ eSub\ HDTV\ \[KoTuWa\]/*
Collecting videos  [####################################]  100%
24 videos collected / 0 video ignored / 3 errors
Downloading subtitles  [#-----------------------------------]    4%  The.Big.Bang.Theory.S09E01.720p.HDTV.[KoTuWa]x.mp4
Traceback (most recent call last):
  File "/home/thomas/.local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/home/thomas/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/thomas/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/thomas/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/thomas/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thomas/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/thomas/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/thomas/.local/lib/python3.5/site-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/home/thomas/.local/lib/python3.5/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/home/thomas/.local/lib/python3.5/site-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/home/thomas/.local/lib/python3.5/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/thomas/.local/lib/python3.5/site-packages/subliminal/providers/podnapisi.py", line 52, in get_matches
    if video.series and sanitize(self.title) == sanitize(video.series):
  File "/home/thomas/.local/lib/python3.5/site-packages/subliminal/utils.py", line 111, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object`

I have tired searched similar cases and tried their fixex but without luck 
I have both tried installaing it systemwide and also just for the user. 
Tried both pip3 and pip (2.7) option. . And ofcoruse i installed / uninstalled In ordre. 

And i puts out same error everytime. 

I'm running . ubuntu server 16.04 

thanks in advance

**Comment by thomasloldk** [comment]
Sorry i post this on the right github page ... My sleeping peels just kicked in ...
