### ISSUE TITLE
pipenv install blows up with unicode errors in Python 2.7 when compilation of a package fails

### ISSUE THREAD

**Issue by schlenk** [kennethreitz/pipenv#433]
German windows, so probably some umlauts in the error messages of the VisualStudio compiler that trigger this:

To reproduce:

- Use a German Windows installation
- Install Python 2.7.13
- Build something with pyldap as a dependency (e.g. clone https://github.com/OpenIDC/pyoidc )
- try to install via 'pipenv install -dev'
- pyldap does not have a wheel, so needs to be built, which fails due to lots missing dependencies
- Watch pipenv fail

When using Pyhon 3.6, the traceback/log is properly shown.

d:\code\gitrepos\pyoidc>c:\tools\bin\pipenv.exe --python c:\Python27_x64\python.exe install --dev
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Using c:\Python27_x64\python.exe to create virtualenv...
Running virtualenv with interpreter c:\Python27_x64\python.exe
New python executable in c:\venvs\pyoidc-wcZyveBj\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: c:\venvs\pyoidc-wcZyveBj
No package provided, installing all dependencies.
Pipfile found at d:\code\gitrepos\pyoidc\Pipfile. Considering this to be the project home.
Installing dependencies from Pipfile.lock...
An error occured while installing! 33/57 - 00:01:19
[================================] 33/57 - 00:01:54
Traceback (most recent call last):
  File "c:\Python27_x64\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27_x64\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\tools\bin\pipenv.exe\__main__.py", line 9, in <module>
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\cli.py", line 824, in install
    do_init(dev=dev, allow_global=system, ignore_hashes=ignore_hashes, ignore_pipfile=ignore_pipfile)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\cli.py", line 607, in do_init
    ignore_hashes=ignore_hashes)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\cli.py", line 275, in do_install_dependencies
    click.echo(crayons.blue(format_pip_output(c.out)))
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\utils.py", line 221, in echo
    message = text_type(message)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\crayons.py", line 89, in __unicode__
    return value.decode('utf8')
  File "d:\code\venv\pipenv\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x94 in position 5582: invalid start byte

**Comment by nateprewitt** [comment]
Thanks for this report, @schlenk. This looks like it's a bug in the crayons library which is expecting utf-8 instead of latin-1 (or possibly Windows-1252). We'll need to look into fixing that over there. If you wouldn't mind raising an issue there, it would be helpful to kick off the bug fix process.
