### ISSUE TITLE
Explosion of pipenv on `pipenv install` when duplicated `[packages]` or `[dev-packages]`

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [kennethreitz/pipenv#453]
# Summary
During merges, sometimes there are duplicates created in the Pipfile. This causes a error that is hard to debug unless you know what your looking at. I'm not sure how this should be handled or if there is some kind of `pipenv verify` command that I am missing. 

There is a error that is buried in the error message. Possibly make this a nicer error or easier to locate in the stack trace?

`toml.TomlDecodeError: What? dev-packages already exists?`

# Attempted path
`pip3 install pipenv`
`pipenv --three`
`pipenv shell`
`pipenv install`

# Expected Result
`pipenv install` should install all dependencies in the Pipfile. 

# Attempted debugging
- Removal of Pipfile.lock in case of bad or merge conflicts on lock file
- Uninstall of pipenv for both pip and pip3
- Removal of all virtualenv directories containing files for pipenv
- Removal of all virtualenv `rm -rf ~/.local/share/virtualenvs/`
- `pipenv upgrade`
- Use of minimal Pipfile with only with single duplicate. 

# Example Pipfile with duplicates. 

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
powerline-status = "*"

[dev-packages]
awsebcli = "*"

[dev-packages]
awsebcli = "*"
```

## Output on duplicates
```
pipenv install
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==5.1.2', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 811, in install
    ensure_project(three=three, python=python)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 160, in ensure_project
    ensure_pipfile(validate=validate)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 126, in ensure_pipfile
    p = project.parsed_pipfile
  File "/usr/lib/python3.6/site-packages/pipenv/project.py", line 155, in parsed_pipfile
    return toml.load(f, _dict=OrderedDict)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/toml.py", line 50, in load
    return loads(f.read(), _dict)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/toml.py", line 258, in loads
    raise TomlDecodeError("What? "+group+" already exists?"+str(currentlevel))
toml.TomlDecodeError: What? dev-packages already exists?OrderedDict([('source', [OrderedDict([('url', 'https://pypi.python.org/simple'), ('verify_ssl', True)])]), ('packages', OrderedDict([('powerline-status', '*')])), ('dev-packages', OrderedDict([('awsebcli', '*')]))])
```

**Comment by kennethreitz** [comment]
Provide proper TOML.
