### ISSUE TITLE
Allow pipenv to run without colors

### ISSUE THREAD

**Issue by omaciel** [kennethreitz/pipenv#454]
Running `pipenv --three` inside a terminal within Emacs, the following traceback can be seen:

```shell
pipenv --three
Creating a Pipfile for this project...
Creating a virtualenv for this project...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 7
22, in __call__                                                                   
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 6
97, in main                                                                       
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1
043, in invoke                                                                    
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 8
95, in invoke                                                                     
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 5
35, in invoke                                                                     
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", 
line 17, in new_func                                                              
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 779, in cli
    ensure_project(three=three, python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 161, in ensure_
project                                                                           
    ensure_virtualenv(three=three, python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 140, in ensure_
virtualenv                                                                        
    do_create_virtualenv(three=three, python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 395, in do_crea
te_virtualenv                                                                     
    click.echo(crayons.blue(c.out), err=True)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 95
, in out                                                                          
    self.__out = self._pexpect_out
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 83
, in _pexpect_out                                                                 
    result += self.subprocess.read()
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/pexpect/spawnbase.py",
 line 413, in read                                                                
    self.expect(self.delimiter)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/pexpect/spawnbase.py",
 line 321, in expect                                                              
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/pexpect/spawnbase.py",
 line 345, in expect_list                                                         
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/pexpect/expect.py", li
ne 107, in expect_loop                                                            
    return self.timeout(e)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/pexpect/expect.py", li
ne 70, in timeout                                                                 
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x1063d7bd0>
searcher: searcher_re:
    0: EOF
<pexpect.popen_spawn.PopenSpawn object at 0x1063d7bd0>
searcher: searcher_re:
    0: EOF
```

Would it be possible to have a `--no-colors` argument perhaps?

**Comment by rochacbruno** [comment]
`pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x1063d7bd0>` looks like this is a TIMEOUT problem while rendering the message. And I agree this may be caused by `crayon` above.

**Comment by kennethreitz** [comment]
It does run without colors, when no TTY is present.

**Comment by nateprewitt** [comment]
We also have the PIPENV_COLORBLIND environment variable which will disable this for you.

**Comment by omaciel** [comment]
Thank you @kennethreitz and @nateprewitt for the response. I'll go ahead and close this issue.

```shell
hacking/castalio » PIPENV_COLORBLIND=1
hacking/castalio » echo $PIPENV_COLORBLIND  
1
hacking/castalio » pipenv --three
Creating a virtualenv for this project...
⠋Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Vers
ions/3.6'                                                                         
New python executable in /Users/omaciel/.virtualenvs/castalio-Svl83nft/bin/python3.
6                                                                                 
Also creating executable in /Users/omaciel/.virtualenvs/castalio-Svl83nft/bin/pytho
n                                                                                 
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/omaciel/.virtualenvs/castalio-Svl83nft
```

**Comment by erinxocon** [comment]
There is also PIPENV_TIMEOUT specified in seconds that will extend the default timeout for long running operations.
