### ISSUE TITLE
Debugging piptools.exceptions.NoCandidateFound

### ISSUE THREAD

**Issue by philfreo** [kennethreitz/pipenv#468]
In trying to convert a fairly large project from `requirements.txt` (201 lines) to start using `pipenv`. The following took about 50 minutes to run ("Converting..." was very slow).

It ended with this `piptools.exceptions.NoCandidateFound` error, that also happens any additional time I run `pipenv install` now.

I assume this is due to some dependency version mismatch (which pip never complained about before). The problem is that there doesn't seem to be an easy way to see _which_ dependencies are asking for conflicting versions of Flask.

I was able to manually find and fix one of the conflicts by running `pipdeptree -r -p Flask` in my old pip virtualenv, but now pipdeptree shows them as resolved, yet this error persists.

Is there some way to see the dependency tree or see which dependencies are causing this error? (As far as I know, all my deps should now be okay with Flask==0.9)

```sh
$ pipenv install        
Requirements file found, instead of Pipfile! Converting...
No package provided, installing all dependencies.
Pipfile found at /Users/me/Sites/foo/Pipfile. Considering this to be the project home.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Traceback (most recent call last):
  File "/Users/philfreo/Library/Python/2.7/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 892, in install
    do_init(dev=dev, allow_global=system, ignore_hashes=ignore_hashes, ignore_pipfile=ignore_pipfile, skip_lock=skip_lock)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 663, in do_init
    do_lock(no_hashes=no_hashes)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 492, in do_lock
    results = resolve_deps(deps, sources=project.sources)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/utils.py", line 49, in resolve_deps
    for result in r.resolve():
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 187, in _resolve_one_round
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 187, in <genexpr>
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 245, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/usr/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 116, in find_best_match
    raise NoCandidateFound(ireq, all_candidates)
piptools.exceptions.NoCandidateFound: Could not find a version that matches Flask==0.9,>=0.10,>=0.7,>=0.8,>=0.9
Tried: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.10, 0.10.1, 0.11, 0.11, 0.11.1, 0.11.1, 0.12, 0.12, 0.12.1, 0.12.1, 0.12.2, 0.12.2
```

I suppose this is a dupe of https://github.com/jazzband/pip-tools/issues/165, but I figured I'd start here because `pipenv` causes this error while `pip` isn't.

**Comment by kennethreitz** [comment]
try `pip install --hashes`, which uses a different dependency resolver.

**Comment by patrick91** [comment]
I have the same issue when trying to install a dev version of graphene:

```
pipenv install "graphene>=2.0.dev20170802065539"
Installing graphene>=2.0.dev20170802065539...
Adding graphene>=2.0.dev20170802065539 to Pipfile's [packages]...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Traceback (most recent call last):
  File "/Users/patrick/.pyenv/versions/3.6.0/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/cli.py", line 989, in install
    do_lock(no_hashes=no_hashes)
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/cli.py", line 531, in do_lock
    results = resolve_deps(deps, sources=project.sources, hashes=(not no_hashes))
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/utils.py", line 62, in resolve_deps
    resolved_tree = resolver.resolve()
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/piptools/resolver.py", line 187, in _resolve_one_round
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/piptools/resolver.py", line 187, in <genexpr>
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/piptools/resolver.py", line 245, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/Users/patrick/.pyenv/versions/3.6.0/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 116, in find_best_match
    raise NoCandidateFound(ireq, all_candidates)
piptools.exceptions.NoCandidateFound: Could not find a version that matches graphene>=2.0.dev20170802065539
Tried: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.5.1, 0.1.5.2, 0.1.5.3, 0.1.6a1, 0.1.6.0, 0.1.6.1, 0.3.0, 0.4.0, 0.4.0.1, 0.4.1, 0.4.1.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9b1, 0.9, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 1.0.dev20160815004752, 1.0.dev20160816073455, 1.0.dev20160822080320, 1.0.dev20160823061102, 1.0.dev20160909040318, 1.0.dev20160909055438, 1.0.dev20160911044410, 1.0.dev20160911051803, 1.0.dev20160917190505, 1.0.dev20160918041239, 1.0.dev20160920015515, 1.0.dev20160920070441, 1.0.dev20160921153356, 1.0.dev20160922020647, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.2, 1.3, 1.4, 1.4.1, 2.0.dev20170724064308, 2.0.dev20170725043308, 2.0.dev20170725061556, 2.0.dev20170727024417, 2.0.dev20170727061432, 2.0.dev20170801053013, 2.0.dev20170801053013, 2.0.dev20170802065539, 2.0.dev20170802065539
```

This works with standard pip

**Comment by kennethreitz** [comment]
there is now a --verbose mode

**Comment by philfreo** [comment]
`--verbose` didn't seem to tell me anything more useful:

```
$ pipenv install --verbose
No package provided, installing all dependencies.
Pipfile found at /Users/foo/bar/Pipfile. Considering this to be the project home.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Traceback (most recent call last):
  File "/Users/philfreo/Library/Python/2.7/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 1008, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, skip_lock=skip_lock, verbose=verbose)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 728, in do_init
    do_lock()
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 601, in do_lock
    results = resolve_deps(deps, sources=project.sources)
  File "/Users/philfreo/Library/Python/2.7/lib/python/site-packages/pipenv/utils.py", line 70, in resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 187, in _resolve_one_round
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 187, in <genexpr>
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 245, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/usr/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 116, in find_best_match
    raise NoCandidateFound(ireq, all_candidates)
piptools.exceptions.NoCandidateFound: Could not find a version that matches Flask==0.9,>=0.10,>=0.7,>=0.8,>=0.9
Tried: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.10, 0.10.1, 0.11, 0.11, 0.11.1, 0.11.1, 0.12, 0

$ pipenv --version
pipenv, version 6.2.1
```

**Comment by kennethreitz** [comment]
oh it's `lock --verbose`

**Comment by philfreo** [comment]
Thanks - that's helpful. 

It seems maybe my issue is that my `editable = true` packages that refers to a specific git sha (of a fork of a pypi module) does _not_ show up in ROUND 1 "Current constraints". So instead, this forked package isn't showing up as a constraint until Round 2 when another dependency expects it, however I think it's then trying to use a standard/published version instead of my specified git sha.

Does this sound like a bug?

**Comment by techalchemy** [comment]
@philfreo it would be more helpful if you provided the output so that we could also look at it

**Comment by HeyHugo** [comment]
I think I'm having the same problem after installing a package: `sqlalchemy-bulk-lazy-loader` 

```
 ➞ pipenv --version
pipenv, version 6.1.6

 ➞ pipenv lock --verbose
Locking [dev-packages] dependencies...

                          ROUND 1
Current constraints:
  flask-flaskwork
  marshmallow-sqlalchemy
  requests

Finding the best candidates:
  found candidate flask-flaskwork==0.1.11 (constraint was <any>)
  found candidate marshmallow-sqlalchemy==0.13.1 (constraint was <any>)
  found candidate requests==2.18.4 (constraint was <any>)

Finding secondary dependencies:
  requests==2.18.4          requires certifi>=2017.4.17, chardet<3.1.0,>=3.0.2, idna<2.7,>=2.5, urllib3<1.23,>=1.21.1
  flask-flaskwork==0.1.11   requires Flask, sqlalchemy
  marshmallow-sqlalchemy==0.13.1 requires marshmallow>=2.0.0, SQLAlchemy>=0.9.7

New dependencies found in this round:
  adding [u'certifi', '>=2017.4.17', '[]']
  adding [u'chardet', '<3.1.0,>=3.0.2', '[]']
  adding [u'flask', '', '[]']
  adding [u'idna', '<2.7,>=2.5', '[]']
  adding [u'marshmallow', '>=2.0.0', '[]']
  adding [u'sqlalchemy', '>=0.9.7', '[]']
  adding [u'urllib3', '<1.23,>=1.21.1', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  certifi>=2017.4.17
  chardet<3.1.0,>=3.0.2
  Flask
  flask-flaskwork
  idna<2.7,>=2.5
  marshmallow>=2.0.0
  marshmallow-sqlalchemy
  requests
  sqlalchemy>=0.9.7
  urllib3<1.23,>=1.21.1

Finding the best candidates:
  found candidate certifi==2017.7.27.1 (constraint was >=2017.4.17)
  found candidate chardet==3.0.4 (constraint was >=3.0.2,<3.1.0)
  found candidate flask==0.12.2 (constraint was <any>)
  found candidate flask-flaskwork==0.1.11 (constraint was <any>)
  found candidate idna==2.6 (constraint was >=2.5,<2.7)
  found candidate marshmallow==2.13.6 (constraint was >=2.0.0)
  found candidate marshmallow-sqlalchemy==0.13.1 (constraint was <any>)
  found candidate requests==2.18.4 (constraint was <any>)
  found candidate sqlalchemy==1.1.14 (constraint was >=0.9.7)
  found candidate urllib3==1.22 (constraint was >=1.21.1,<1.23)

Finding secondary dependencies:
  urllib3==1.22             requires -
  marshmallow-sqlalchemy==0.13.1 requires marshmallow>=2.0.0, SQLAlchemy>=0.9.7
  marshmallow==2.13.6       requires -
  idna==2.6                 requires -
  flask-flaskwork==0.1.11   requires Flask, sqlalchemy
  chardet==3.0.4            requires -
  certifi==2017.7.27.1      requires -
  requests==2.18.4          requires certifi>=2017.4.17, chardet<3.1.0,>=3.0.2, idna<2.7,>=2.5, urllib3<1.23,>=1.21.1
  sqlalchemy==1.1.14        requires -
  flask==0.12.2             requires click>=2.0, itsdangerous>=0.21, Jinja2>=2.4, Werkzeug>=0.7

New dependencies found in this round:
  adding [u'click', '>=2.0', '[]']
  adding [u'itsdangerous', '>=0.21', '[]']
  adding [u'jinja2', '>=2.4', '[]']
  adding [u'werkzeug', '>=0.7', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3
Current constraints:
  certifi>=2017.4.17
  chardet<3.1.0,>=3.0.2
  click>=2.0
  Flask
  flask-flaskwork
  idna<2.7,>=2.5
  itsdangerous>=0.21
  Jinja2>=2.4
  marshmallow>=2.0.0
  marshmallow-sqlalchemy
  requests
  SQLAlchemy>=0.9.7
  urllib3<1.23,>=1.21.1
  Werkzeug>=0.7

Finding the best candidates:
  found candidate certifi==2017.7.27.1 (constraint was >=2017.4.17)
  found candidate chardet==3.0.4 (constraint was >=3.0.2,<3.1.0)
  found candidate click==6.7 (constraint was >=2.0)
  found candidate flask==0.12.2 (constraint was <any>)
  found candidate flask-flaskwork==0.1.11 (constraint was <any>)
  found candidate idna==2.6 (constraint was >=2.5,<2.7)
  found candidate itsdangerous==0.24 (constraint was >=0.21)
  found candidate jinja2==2.9.6 (constraint was >=2.4)
  found candidate marshmallow==2.13.6 (constraint was >=2.0.0)
  found candidate marshmallow-sqlalchemy==0.13.1 (constraint was <any>)
  found candidate requests==2.18.4 (constraint was <any>)
  found candidate sqlalchemy==1.1.14 (constraint was >=0.9.7)
  found candidate urllib3==1.22 (constraint was >=1.21.1,<1.23)
  found candidate werkzeug==0.12.2 (constraint was >=0.7)

Finding secondary dependencies:
  click==6.7                requires -
  jinja2==2.9.6             requires MarkupSafe>=0.23
  marshmallow-sqlalchemy==0.13.1 requires marshmallow>=2.0.0, SQLAlchemy>=0.9.7
  sqlalchemy==1.1.14        requires -
  chardet==3.0.4            requires -
  werkzeug==0.12.2          requires -
  requests==2.18.4          requires certifi>=2017.4.17, chardet<3.1.0,>=3.0.2, idna<2.7,>=2.5, urllib3<1.23,>=1.21.1
  flask-flaskwork==0.1.11   requires Flask, sqlalchemy
  idna==2.6                 requires -
  certifi==2017.7.27.1      requires -
  itsdangerous==0.24        requires -
  flask==0.12.2             requires click>=2.0, itsdangerous>=0.21, Jinja2>=2.4, Werkzeug>=0.7
  urllib3==1.22             requires -
  marshmallow==2.13.6       requires -

New dependencies found in this round:
  adding [u'markupsafe', '>=0.23', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 3: not stable

                          ROUND 4
Current constraints:
  certifi>=2017.4.17
  chardet<3.1.0,>=3.0.2
  click>=2.0
  Flask
  flask-flaskwork
  idna<2.7,>=2.5
  itsdangerous>=0.21
  Jinja2>=2.4
  MarkupSafe>=0.23
  marshmallow>=2.0.0
  marshmallow-sqlalchemy
  requests
  SQLAlchemy>=0.9.7
  urllib3<1.23,>=1.21.1
  Werkzeug>=0.7

Finding the best candidates:
  found candidate certifi==2017.7.27.1 (constraint was >=2017.4.17)
  found candidate chardet==3.0.4 (constraint was >=3.0.2,<3.1.0)
  found candidate click==6.7 (constraint was >=2.0)
  found candidate flask==0.12.2 (constraint was <any>)
  found candidate flask-flaskwork==0.1.11 (constraint was <any>)
  found candidate idna==2.6 (constraint was >=2.5,<2.7)
  found candidate itsdangerous==0.24 (constraint was >=0.21)
  found candidate jinja2==2.9.6 (constraint was >=2.4)
  found candidate markupsafe==1.0 (constraint was >=0.23)
  found candidate marshmallow==2.13.6 (constraint was >=2.0.0)
  found candidate marshmallow-sqlalchemy==0.13.1 (constraint was <any>)
  found candidate requests==2.18.4 (constraint was <any>)
  found candidate sqlalchemy==1.1.14 (constraint was >=0.9.7)
  found candidate urllib3==1.22 (constraint was >=1.21.1,<1.23)
  found candidate werkzeug==0.12.2 (constraint was >=0.7)

Finding secondary dependencies:
  urllib3==1.22             requires -
  marshmallow-sqlalchemy==0.13.1 requires marshmallow>=2.0.0, SQLAlchemy>=0.9.7
  certifi==2017.7.27.1      requires -
  marshmallow==2.13.6       requires -
  chardet==3.0.4            requires -
  markupsafe==1.0           requires -
  jinja2==2.9.6             requires MarkupSafe>=0.23
  flask-flaskwork==0.1.11   requires Flask, sqlalchemy
  itsdangerous==0.24        requires -
  werkzeug==0.12.2          requires -
  requests==2.18.4          requires certifi>=2017.4.17, chardet<3.1.0,>=3.0.2, idna<2.7,>=2.5, urllib3<1.23,>=1.21.1
  click==6.7                requires -
  flask==0.12.2             requires click>=2.0, itsdangerous>=0.21, Jinja2>=2.4, Werkzeug>=0.7
  sqlalchemy==1.1.14        requires -
  idna==2.6                 requires -
------------------------------------------------------------
Result of round 4: stable, done
Locking [packages] dependencies...

                          ROUND 1
Current constraints:
  alembic==0.8.9
  amqp
  aniso8601==1.1.0
  anyjson==0.3.3
  billiard
  bleach==1.4.2
  blinker==1.4
  celery
  click
  cssselect==0.9.1
  flask
  flask-admin
  flask-alembic==2.0.1
  flask-caching==1.3.2
  flask-cors
  flask-flaskwork
  flask-graphql
  flask-httpauth==3.2.1
  flask-jwt
  flask-marshmallow
  ftfy==4.4.3
  graphene-sqlalchemy
  marshmallow-enum
  marshmallow-sqlalchemy
  pillow
  psycopg2
  pyquery
  requests
  sqlalchemy-bulk-lazy-loader

Finding the best candidates:
  found candidate alembic==0.8.9 (constraint was ==0.8.9)
  found candidate amqp==2.2.1 (constraint was <any>)
  found candidate aniso8601==1.1.0 (constraint was ==1.1.0)
  found candidate anyjson==0.3.3 (constraint was ==0.3.3)
  found candidate billiard==3.5.0.3 (constraint was <any>)
  found candidate bleach==1.4.2 (constraint was ==1.4.2)
  found candidate blinker==1.4 (constraint was ==1.4)
  found candidate celery==4.1.0 (constraint was <any>)
  found candidate click==6.7 (constraint was <any>)
  found candidate cssselect==0.9.1 (constraint was ==0.9.1)
  found candidate flask==0.12.2 (constraint was <any>)
  found candidate flask-admin==1.5.0 (constraint was <any>)
  found candidate flask-alembic==2.0.1 (constraint was ==2.0.1)
  found candidate flask-caching==1.3.2 (constraint was ==1.3.2)
  found candidate flask-cors==3.0.3 (constraint was <any>)
  found candidate flask-flaskwork==0.1.11 (constraint was <any>)
  found candidate flask-graphql==1.4.1 (constraint was <any>)
  found candidate flask-httpauth==3.2.1 (constraint was ==3.2.1)
  found candidate flask-jwt==0.3.2 (constraint was <any>)
  found candidate flask-marshmallow==0.8.0 (constraint was <any>)
  found candidate ftfy==4.4.3 (constraint was ==4.4.3)
  found candidate graphene-sqlalchemy==1.1.1 (constraint was <any>)
  found candidate marshmallow-enum==1.4.1 (constraint was <any>)
  found candidate marshmallow-sqlalchemy==0.13.1 (constraint was <any>)
  found candidate pillow==4.2.1 (constraint was <any>)
  found candidate psycopg2==2.7.3.1 (constraint was <any>)
  found candidate pyquery==1.2.17 (constraint was <any>)
  found candidate requests==2.18.4 (constraint was <any>)
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1075, in lock
    do_lock(no_hashes=no_hashes, verbose=verbose, legacy=legacy)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 531, in do_lock
    results = resolve_deps(deps, sources=project.sources, hashes=(not no_hashes))
  File "/usr/local/lib/python2.7/site-packages/pipenv/utils.py", line 62, in resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 187, in _resolve_one_round
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 187, in <genexpr>
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 245, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/usr/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 116, in find_best_match
    raise NoCandidateFound(ireq, all_candidates)
piptools.exceptions.NoCandidateFound: Could not find a version that matches sqlalchemy-bulk-lazy-loader
Tried: (no version found at all)
```

**Comment by kennethreitz** [comment]
I think this is a problem with piptools, not pipenv.

**Comment by kennethreitz** [comment]
Let's get this fixed in pip-tools. I'm comitter over there too, so if you have a patch that fixes it, i'll merge it.

**Comment by philfreo** [comment]
This continuing over in https://github.com/kennethreitz/pipenv/issues/671
