### ISSUE TITLE
FileNotFound: 'pew' 

### ISSUE THREAD

**Issue by dilantha111** [kennethreitz/pipenv#471]
when I issue these commands, "pipenv install requests" within an empty directory. 
I got this. 
Traceback (most recent call last):
  File "/home/randy/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/cli.py", line 879, in install
    ensure_project(three=three, python=python)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/cli.py", line 178, in ensure_project
    ensure_virtualenv(three=three, python=python)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/cli.py", line 157, in ensure_virtualenv
    do_create_virtualenv(three=three, python=python)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/cli.py", line 413, in do_create_virtualenv
    c = delegator.run(cmd, block=False, timeout=PIPENV_TIMEOUT)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/vendor/delegator.py", line 257, in run
    c.run(block=block, binary=binary)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/vendor/delegator.py", line 149, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/home/randy/.local/lib/python3.5/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1541, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pew'

**I tried command pew --version on my terminal it outputs** 

Available commands:

 add:                      Add the specified directories to the Python path for the currently active virtualenv.
 cp:                       Duplicate the named virtualenv to make a new one.
 dir:                      Print the path for the virtualenv directory
 in:                       Run a command in the given virtualenv.
 inall:                    Run a command in each virtualenv.
 install:                  Use Pythonz to download and build the specified Python version
 list_pythons:             List the pythons installed by Pythonz (or all the installable ones)
 locate_python:            Locate the path for the python version installed by Pythonz
 ls:                       List available environments.
 lssitepackages:           Show the content of the site-packages directory of the current virtualenv.
 mkproject:                Create a new project directory and its associated virtualenv.
 mktmpenv:                 Create a temporary virtualenv.
 new:                      Create a new environment, in $WORKON_HOME.
 rename:                   Rename a virtualenv
 restore:                  Try to restore a broken virtualenv by reinstalling the same python version on top of it
 rm:                       Remove one or more environment, from $WORKON_HOME.
 setproject:               Given a virtualenv directory and a project directory, set the
 shell_config:             Prints the path for the current $SHELL helper file
 show
 sitepackages_dir
 toggleglobalsitepackages: Toggle the current virtualenv between having and not having access to the global site-packages.
 uninstall:                Use Pythonz to uninstall the specified Python version
 version:                  Prints current pew version
 wipeenv:                  Remove all installed packages from the current (or supplied) env.
 workon:                   List or change working virtual environments.

I found that this is similar to #182. But I have used pip not pipsi

**Comment by kennethreitz** [comment]
How did you install pipenv?

**Comment by natngmk** [comment]
I also face the same issue. Installed pipenv through Python3 (homebrew).

**Comment by natngmk** [comment]
seems like still having a problem. any idea?

MacBook-Pro:firstEnvTest nat$ python3 -m pipenv shell
Creating a virtualenv for this project...
⠋Traceback (most recent call last):
  File "/usr/local/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/local/lib/python3.6/site-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/local/lib/python3.6/site-packages/pew/pew.py", line 36, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python3.6/site-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Virtualenv location: 
Traceback (most recent call last):
  File "/usr/local/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/local/lib/python3.6/site-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/local/lib/python3.6/site-packages/pew/pew.py", line 36, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python3.6/site-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

**Comment by kennethreitz** [comment]
Looks like you need to set your system locale.

**Comment by kennethreitz** [comment]
See https://github.com/kennethreitz/pipenv/issues/470#issuecomment-327216953 for guidance

**Comment by dilantha111** [comment]
Hi sorry about the delay. I installed pipenv with pip3 @kennethreitz

**Comment by kennethreitz** [comment]
Did you try the [fancy installation method](http://docs.pipenv.org/en/latest/advanced.html#fancy-installation-of-pipenv)?

**Comment by dilantha111** [comment]
I think I am having some trouble installing pipsi. Because I have already installed virtualenv but when I try to install pipsi, it says it needs virtualenv.

**Comment by kennethreitz** [comment]
That's weird. Are you using the same python for both?

**Comment by natngmk** [comment]
Thanks Kennethreitz. At last got it working now.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by jacebrowning** [comment]
I am experiencing this issue on Circle CI (1.0). From their logs:

```
$ pip install pipenv==5.4.2
...

$ pipenv --python=python3.6
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Using python3.6 to create virtualenv...
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-3.6.1/bin/pipenv", line 11, in <module>
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/cli.py", line 864, in cli
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/cli.py", line 181, in ensure_project
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/cli.py", line 174, in ensure_virtualenv
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/cli.py", line 160, in ensure_virtualenv
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/cli.py", line 413, in do_create_virtualenv
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 257, in run
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 149, in run
  File "/home/ubuntu/virtualenvs/venv-3.6.1/lib/python3.6/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 45, in __init__
  File "/opt/circleci/python/3.6.1/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/opt/circleci/python/3.6.1/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pew'

**Comment by kennethreitz** [comment]
doesn't circle ci provide a virtualenv? if so, you're deleting it.

**Comment by kennethreitz** [comment]
Don't run `pipenv --python=python3.6`, just run `pipenv install`

**Comment by jacebrowning** [comment]
Thanks! That seems to work. Any reason I can't create a new working virtual environment on CircleCI? I like to be able to test my full installation instructions.

**Comment by kennethreitz** [comment]
You can, you just have to set the `PIPENV_IGNORE_VIRTUALENVS` environment variable. 

http://docs.pipenv.org/en/latest/advanced.html#configuration-with-environment-variables

**Comment by SandiPandi** [comment]
I tried doing the "Fancy installation method" and got stuck on installing pipsi, here's what happened:
`
$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3 (yes, I want it installed on python3)`
then it told me to add `export PATH=/Users/sahandzarrinkoub/.local/bin:$PATH`, and so I did. Then I went on with the installation:
`$ pipsi install pew
Traceback (most recent call last):
  File "/Users/sahandzarrinkoub/.local/bin/pipsi", line 7, in <module>
    from pipsi import cli
ModuleNotFoundError: No module named 'pipsi'`

What should I do to solve this?

**Comment by kennethreitz** [comment]
That sounds weird.

**Comment by kennethreitz** [comment]
Try again maybe?

**Comment by SandiPandi** [comment]
Indeed, my whole attempt to install pipenv and doing virtualenv's has been littered with errors and "weird" occurances. Could it be that something is wrong with my Python installation altogether?

**Comment by kennethreitz** [comment]
Sounds like — or your shell. 

Want to hop on a hangout?

**Comment by SandiPandi** [comment]
What does a hangout mean? Sry I'm new to this.

**Comment by kennethreitz** [comment]
LIke a video conference.

**Comment by SandiPandi** [comment]
Sure, that'd be great

**Comment by SandiPandi** [comment]
How do we do it?

**Comment by kennethreitz** [comment]
I'm available now — click this link — 

https://hangouts.google.com/hangouts/_/kennethreitz.org/pipenv

**Comment by kennethreitz** [comment]
Got @SandiPandi hooked up! Simple `PATH` issue :)

**Comment by Goloworez** [comment]
Hi guys,

Having exactly the same issue Sahand1993 described a while ago. Also added the suggested PATH. Still giving `ModuleNotFoundError: No module named 'pipsi'.`
Seems you got this sorted out, but the solution stayed behind the scene :) Can you please share some tips?

Thanks in advance!
