### ISSUE TITLE
Pipenv: no such file or directory

### ISSUE THREAD

**Issue by mazzy89** [kennethreitz/pipenv#475]
Whatever command I try to run I get this result:

```python
Creating a virtualenv for this project...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1138, in check
    ensure_project(three=three, python=python, validate=False)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 178, in ensure_project
    ensure_virtualenv(three=three, python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 157, in ensure_virtualenv
    do_create_virtualenv(three=three, python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 413, in do_create_virtualenv
    c = delegator.run(cmd, block=False, timeout=PIPENV_TIMEOUT)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 257, in run
    c.run(block=block, binary=binary)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 149, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I'm running `python2` installed via Homebrew. `pipenv` has been installed via `pip2`

**Comment by kennethreitz** [comment]
hmm, looks like `virtualenv` didn't get installed. 

can you `$ pip2 install pew` and try again?

**Comment by erinxocon** [comment]
@mazzy89 I'd recommend trying the [fancy](http://docs.pipenv.org/en/latest/advanced.html#fancy-installation-of-pipenv) way of installing pipenv.   Pipsi is a great tool and I've never experienced an issue with pipenv using this method of installation.

**Comment by currycoder** [comment]
I've just run in to this issue myself, and the fix for me was to ensure that `/home/{{user}}/.local/bin` was present in my path `PATH`.  Note for linux users, this has to be the absolute path and not `~/.local/bin`.

**Comment by currycoder** [comment]
It might be nice to make a note of this gotcha in the installation docs somewhere, I'd expect a few people to run in to it when trying out pipenv.  The `OSError` can be a little frustrating when everything points to `pew` being installed and runnable in a terminal.

Note, I was getting the same stack trace as OP;
```
File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
```
The Popen call here is not called with `shell=True`, so `~` is not expanded to the user's home directory.

**Comment by kennethreitz** [comment]
I'll add a warning.

**Comment by kennethreitz** [comment]
Warning added :)

**Comment by kennethreitz** [comment]
<img width="591" alt="screen shot 2017-09-14 at 11-1 30 34 am" src="https://user-images.githubusercontent.com/119893/30438804-2904e8ae-9940-11e7-8630-734873db6d55.png">

**Comment by currycoder** [comment]
Great - looks good!
