### ISSUE TITLE
UnicodeDecodeError when running pipenv install --help

### ISSUE THREAD

**Issue by ericfrederich** [kennethreitz/pipenv#482]
This happened on a pretty virgin Linux Mint 18.2.  Fresh install and apt installed all virtualenv/venv packages... then run `bug.sh` and see error below.

# bug.sh
```bash
#!/bin/bash

curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3.5

pipsi install pew
pipsi install pipenv

git init foo
cd foo
pipenv --three
pipenv install --help
```
# output:
```
eric@cinnamint:~/
$ ./bug.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4130  100  4130    0     0   2072      0  0:00:01  0:00:01 --:--:--  2072
Installing pipsi
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/eric/.local/venvs/pipsi/bin/python2
Also creating executable in /home/eric/.local/venvs/pipsi/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting pipsi
  Downloading pipsi-0.9-py2-none-any.whl
Collecting Click (from pipsi)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 443kB/s 
Collecting virtualenv (from pipsi)
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 692kB/s 
Installing collected packages: Click, virtualenv, pipsi
Successfully installed Click-6.7 pipsi-0.9 virtualenv-15.1.0
Installed pipsi binary in /home/eric/.local/bin
pipsi is now installed.
Running virtualenv with interpreter /home/eric/.local/venvs/pipsi/bin/python2
Using real prefix '/usr'
New python executable in /home/eric/.local/venvs/pew/bin/python2
Also creating executable in /home/eric/.local/venvs/pew/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting pew
  Downloading pew-0.1.26-py2.py3-none-any.whl
Collecting pythonz-bd>=1.10.2 (from pew)
  Downloading pythonz-bd-1.11.4.tar.gz (86kB)
    100% |████████████████████████████████| 92kB 1.1MB/s 
Collecting virtualenv-clone>=0.2.5 (from pew)
  Downloading virtualenv-clone-0.2.6.tar.gz
Collecting pathlib; python_version == "2.7" (from pew)
  Downloading pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 3.6MB/s 
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from pew)
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting shutilwhich; python_version == "2.7" (from pew)
  Downloading shutilwhich-1.1.0.tar.gz
Requirement already satisfied: setuptools>=17.1 in ./.local/venvs/pew/lib/python2.7/site-packages (from pew)
Collecting virtualenv>=1.11 (from pew)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Building wheels for collected packages: pythonz-bd, virtualenv-clone, pathlib, shutilwhich
  Running setup.py bdist_wheel for pythonz-bd ... done
  Stored in directory: /home/eric/.cache/pip/wheels/04/de/c8/da2d21bb0112bb65bfb28bdf9ee8f2c819c25db143c32435b2
  Running setup.py bdist_wheel for virtualenv-clone ... done
  Stored in directory: /home/eric/.cache/pip/wheels/24/51/ef/93120d304d240b4b6c2066454250a1626e04f73d34417b956d
  Running setup.py bdist_wheel for pathlib ... done
  Stored in directory: /home/eric/.cache/pip/wheels/2a/23/a5/d8803db5d631e9f391fe6defe982a238bf5483062eeb34e841
  Running setup.py bdist_wheel for shutilwhich ... done
  Stored in directory: /home/eric/.cache/pip/wheels/0e/28/70/d5cc6586f26d614b26901485f6f6072d35cbbb5bbeffb6ea43
Successfully built pythonz-bd virtualenv-clone pathlib shutilwhich
Installing collected packages: pythonz-bd, virtualenv-clone, pathlib, backports.shutil-get-terminal-size, shutilwhich, virtualenv, pew
Successfully installed backports.shutil-get-terminal-size-1.0.0 pathlib-1.0.1 pew-0.1.26 pythonz-bd-1.11.4 shutilwhich-1.1.0 virtualenv-15.1.0 virtualenv-clone-0.2.6
  Linked script /home/eric/.local/bin/pew
Done.
Running virtualenv with interpreter /home/eric/.local/venvs/pipsi/bin/python2
Using real prefix '/usr'
New python executable in /home/eric/.local/venvs/pipenv/bin/python2
Also creating executable in /home/eric/.local/venvs/pipenv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting pipenv
  Downloading pipenv-5.3.5.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 978kB/s 
Collecting virtualenv (from pipenv)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Collecting pew>=0.1.26 (from pipenv)
  Using cached pew-0.1.26-py2.py3-none-any.whl
Requirement already satisfied: pip in ./.local/venvs/pipenv/lib/python2.7/site-packages (from pipenv)
Collecting pip-tools>=1.9.0 (from pipenv)
  Downloading pip_tools-1.9.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=36.3.0 in ./.local/venvs/pipenv/lib/python2.7/site-packages (from pipenv)
Collecting background (from pipenv)
  Downloading background-0.1.1-py2.py3-none-any.whl
Collecting semver (from pipenv)
  Downloading semver-2.7.8.tar.gz
Collecting pythonz-bd>=1.10.2 (from pew>=0.1.26->pipenv)
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv)
Collecting pathlib; python_version == "2.7" (from pew>=0.1.26->pipenv)
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from pew>=0.1.26->pipenv)
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting shutilwhich; python_version == "2.7" (from pew>=0.1.26->pipenv)
Collecting click>=6 (from pip-tools>=1.9.0->pipenv)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting six (from pip-tools>=1.9.0->pipenv)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting first (from pip-tools>=1.9.0->pipenv)
  Downloading first-2.0.1-py2.py3-none-any.whl
Collecting futures (from background->pipenv)
  Downloading futures-3.1.1-py2-none-any.whl
Building wheels for collected packages: pipenv, semver
  Running setup.py bdist_wheel for pipenv ... done
  Stored in directory: /home/eric/.cache/pip/wheels/02/44/3d/ec89a166a58067f951fa4ea4d11f2b99124d6242719731ec04
  Running setup.py bdist_wheel for semver ... done
  Stored in directory: /home/eric/.cache/pip/wheels/dc/45/11/33c3c46fc699c32f15d4d7e05fc8806af62ad653c6abc9e97d
Successfully built pipenv semver
Installing collected packages: virtualenv, pythonz-bd, virtualenv-clone, pathlib, backports.shutil-get-terminal-size, shutilwhich, pew, click, six, first, pip-tools, futures, background, semver, pipenv
Successfully installed background-0.1.1 backports.shutil-get-terminal-size-1.0.0 click-6.7 first-2.0.1 futures-3.1.1 pathlib-1.0.1 pew-0.1.26 pip-tools-1.9.0 pipenv-5.3.5 pythonz-bd-1.11.4 semver-2.7.8 shutilwhich-1.1.0 six-1.10.0 virtualenv-15.1.0 virtualenv-clone-0.2.6
  Linked script /home/eric/.local/bin/pipenv
Done.
Initialized empty Git repository in /home/eric/foo/.git/
Creating a Pipfile for this project...
Creating a virtualenv for this project...
⠋Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/eric/.local/share/virtualenvs/foo-jrXm6hwy/bin/python3
Also creating executable in /home/eric/.local/share/virtualenvs/foo-jrXm6hwy/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

Virtualenv location: /home/eric/.local/share/virtualenvs/foo-jrXm6hwy
Traceback (most recent call last):
  File "/home/eric/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 809, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 496, in get_help
    return self.command.get_help(self)
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 831, in get_help
    return formatter.getvalue().rstrip('\n')
  File "/home/eric/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/formatting.py", line 236, in getvalue
    return ''.join(self.buffer)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 41: ordinal not in range(128)
```

**Comment by ericfrederich** [comment]
Seems the first index is a py2 unicode, all others are py2 strs including one with some utf-8 encoded characters.

2 options to fix
* use a normal dash instead of the [`EM DASH`](http://www.fileformat.info/info/unicode/char/2014/index.htm) in the help string for `--skip-lock`.
* mark that string explicitly as unicode e.g. `u'Ignore locking ...'`

FYI: this is the contents of `buffer`

```python
[u'Usage: pipenv install [OPTIONS] [PACKAGE_NAME] [MORE_PACKAGES]...',
 '\n',
 '\n',
 '  Installs provided packages and adds them to Pipfile, or (if none is\n  given), installs all packages.',
 '\n',
 '\n',
 'Options:\n',
 '  -d, --dev',
 '         ',
 'Install package(s) in [dev-packages].\n',
 '  --three / --two',
 '   ',
 'Use Python 3/2 when creating virtualenv.\n',
 '  --python TEXT',
 '     ',
 'Specify which version of Python virtualenv should use.\n',
 '  --system',
 '          ',
 'System pip management.\n',
 '  --hashes',
 '          ',
 'Use hashes.\n',
 '  --ignore-pipfile',
 '  ',
 'Ignore Pipfile when installing, using the Pipfile.lock.\n',
 '  --skip-lock',
 '       ',
 'Ignore locking mechanisms when installing\xe2\x80\x94use the\n',
 '                    Pipfile, instead.\n',
 '  --help',
 '            ',
 'Show this message and exit.\n']
```

**Comment by kennethreitz** [comment]
let's use a u'' string. want to send a pr?
