### ISSUE TITLE
6.0.0 regression on Python2.7 compat

### ISSUE THREAD

**Issue by ewdurbin** [kennethreitz/pipenv#489]
Python 2.7.13 from python.org installer
MacOS 10.13
pipenv 6.0.0

```
Traceback (most recent call last):
  File "/Users/ernestd/Library/Python/2.7/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 887, in install
    do_init(dev=dev, allow_global=system, ignore_hashes=not hashes, ignore_pipfile=ignore_pipfile, skip_lock=skip_lock)
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 649, in do_init
    do_lock(no_hashes=no_hashes)
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/cli.py", line 492, in do_lock
    results = resolve_deps(deps, sources=project.sources, hashes=(not no_hashes))
  File "/Users/ernestd/Library/Python/2.7/lib/python/site-packages/pipenv/utils.py", line 61, in resolve_deps
    from json.decoder import JSONDecodeError
ImportError: cannot import name JSONDecodeError
```

Issue seems rather clear:

```
$ python3.6
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from json.decoder import JSONDecodeError
>>> ^D
$ python2.7
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from json.decoder import JSONDecodeError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name JSONDecodeError
```

**Comment by ewdurbin** [comment]
This exception class was added in Python3.5

https://docs.python.org/3/library/json.html?highlight=jsondecodeerror#json.JSONDecodeError

**Comment by kennethreitz** [comment]
Thanks, fixing.

**Comment by kennethreitz** [comment]
Finding lots of annoyances with switching my main development interpreter to 3.6.

**Comment by kennethreitz** [comment]
v6.0.2 released, which fixes this. ✨🍰✨
