### ISSUE TITLE
KeyError: 'hashes' during pipenv install --dev

### ISSUE THREAD

**Issue by pior** [kennethreitz/pipenv#502]
I got a crash when running  `pipenv install --dev flake8-import-order`:

```shell
$ pipenv install --dev flake8-import-order
Installing flake8-import-order...
Collecting flake8-import-order
  Downloading flake8_import_order-0.13-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/pior/.local/share/virtualenvs/poipoi-9iPHX8H5/lib/python3.6/site-packages (from flake8-import-order)
Requirement already satisfied: pycodestyle in /home/pior/.local/share/virtualenvs/poipoi-9iPHX8H5/lib/python3.6/site-packages (from flake8-import-order)
Installing collected packages: flake8-import-order
Successfully installed flake8-import-order-0.13

Adding flake8-import-order to Pipfile's [dev-packages]...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
```

```python
Traceback (most recent call last):
  File "/home/pior/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/pior/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pior/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pior/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pior/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pior/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pior/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 989, in install
    do_lock(no_hashes=no_hashes)
  File "/home/pior/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 537, in do_lock
    lockfile['default'][dep['name']]['hashes'] = dep['hashes']
KeyError: 'hashes'
```

```
$ pipenv --version
pipenv, version 6.1.6
```

**Comment by kennethreitz** [comment]
thanks for the report!

**Comment by techalchemy** [comment]
@pior can you share the contents of your Pipfile and your Pipfile.lock?

I suspect you weren't able to connect to PyPI briefly and therefore you don't have any hashes in your lockfile.  Try to run pipenv lock again and see if it works

@kennethreitz is there any reason not to include a key 'hashes' with an empty list if we fail to get any hashes from pypi/pip?

**Comment by kennethreitz** [comment]
yes let's do that.

**Comment by kennethreitz** [comment]
done

**Comment by kennethreitz** [comment]
Closing as fixed. I know what caused this. It's been addressed. Sorry about the bug!

**Comment by pior** [comment]
Wow! Thanks @kennethreitz @techalchemy :1st_place_medal:

**Comment by kennethreitz** [comment]
will release shortly
