### ISSUE TITLE
CLI is broken with v6.2.1 on my mac right now

### ISSUE THREAD

**Issue by erinxocon** [kennethreitz/pipenv#510]
pipenv install --three
Sat Sep  9 23:02:15 2017
Traceback (most recent call last):
  File "/Users/erin/.local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/Users/erin/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/__init__.py", line 13, in <module>
    from .cli import cli
  File "/Users/erin/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/cli.py", line 82, in <module>
    project = Project()
  File "/Users/erin/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/project.py", line 33, in __init__
    os.chdir(self.project_directory)
  File "/Users/erin/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/project.py", line 49, in project_directory
    return os.path.abspath(os.path.join(self.pipfile_location, os.pardir))
  File "/Users/erin/.local/venvs/pipenv/bin/../lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by aatishnn** [comment]
Same here on Ubuntu 16.04

**Comment by kennethreitz** [comment]
fix already landed in master

**Comment by kennethreitz** [comment]
deployed
