### ISSUE TITLE
locking dependencies of editable vcs requirements

### ISSUE THREAD

**Issue by sbidoul** [kennethreitz/pipenv#512]
When we `pip install` then `pip freeze` an editable vcs requirement, the frozen requirements include all dependencies.

With pipenv the dependencies of editable vcs requirements do not appear in Pipfile.lock.

Example:

```bash
$ pipenv install -e git+https://github.com/sbidoul/subdirtest.git#egg=subdirtest\&subdirectory=setup
...
$ cat Pipfile.lock
...
    "default": {
        "subdirtest": {
            "editable": true,
            "git": "https://github.com/sbidoul/subdirtest.git",
            "subdirectory": "setup",
            "ref": "7b18afe980a42bfe8d1a96b5ed52e05f58d9ef6c"
        }
    },
...
$ pipenv run pip freeze
click==6.7
pkg-resources==0.0.0
-e git+https://github.com/sbidoul/subdirtest.git@7b18afe980a42bfe8d1a96b5ed52e05f58d9ef6c#egg=subdirtest&subdirectory=setup
```

Since the installed package depends on `click` I expect to see it in the locked dependencies. 

pip-tools lacks this capability (https://github.com/kennethreitz/pipenv/issues/508#issuecomment-328345816)

**Comment by kennethreitz** [comment]
This is definately out of scope for now — until pip-tools grows this ability — I'd raise the issue over there.

**Comment by AlJohri** [comment]
is there an issue in pip-tools for this that I can follow? if not, can you make one @sbidoul?

**Comment by sbidoul** [comment]
Problem is that I don't know pip-tools so I can't create a meaningful issue in that project. I'd need to do some research on the pip-tools api and how it is used by pipenv.

**Comment by kennethreitz** [comment]
Issue title: "Resolve dependencies for editable requirements, required by pipenv"

contents: the contents of this issue.

**Comment by kennethreitz** [comment]
pip-tools is poorly maintained, so i doubt it'll happen.

**Comment by kennethreitz** [comment]
I'm committer on it though, so if you write a patch to get this to work, I'll merge it!

**Comment by sbidoul** [comment]
@kennethreitz is it supposed to be implemented in 7.3.2?

**Comment by kennethreitz** [comment]
yep!

**Comment by sbidoul** [comment]
Hm, looks like its not working for me with 7.3.5 (the command in the description above).

**Comment by kennethreitz** [comment]
oh i dont' know if it works for subdirectories, i know it works for VCSs in general now though.

**Comment by sbidoul** [comment]
I just tried `pipenv install -e git+https://github.com/kennethreitz/requests#egg=requests` and I don't get the dependencies in the lockfile.

**Comment by kennethreitz** [comment]
ah, it works with the other form.

**Comment by kennethreitz** [comment]
v7.6.3 released, which has this confirmed working!

**Comment by sbidoul** [comment]
Almost there:

```
$ pipenv install -e git+https://github.com/kennethreitz/requests#egg=requests                                                                                           Installing -e git+https://github.com/kennethreitz/requests#egg=requests…
Obtaining requests from git+https://github.com/kennethreitz/requests#egg=requests
  Updating /home/sbi-local/.local/share/virtualenvs/pipenvtest-egFzzt6y/src/requests clone
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/sbi-local/.local/share/virtualenvs/pipenvtest-egFzzt6y/lib/python2.7/site-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in /home/sbi-local/.local/share/virtualenvs/pipenvtest-egFzzt6y/lib/python2.7/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/sbi-local/.local/share/virtualenvs/pipenvtest-egFzzt6y/lib/python2.7/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /home/sbi-local/.local/share/virtualenvs/pipenvtest-egFzzt6y/lib/python2.7/site-packages (from requests)
Installing collected packages: requests
  Running setup.py develop for requests
Successfully installed requests

Adding -e git+https://github.com/kennethreitz/requests#egg=requests to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/home/sbi-local/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/sbi-local/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sbi-local/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sbi-local/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sbi-local/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sbi-local/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sbi-local/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 1500, in install
    do_lock(system=system)
  File "/home/sbi-local/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 942, in do_lock
    project=project
  File "/home/sbi-local/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/utils.py", line 133, in resolve_deps
    extra_constraints = best_matches_from(dep[len('-e '):], which=which, which_pip=which_pip, project=project)
  File "/home/sbi-local/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/utils.py", line 106, in best_matches_from
    setup_py_path = os.path.abspath(os.sep.join([result, 'setup.py']))
TypeError: sequence item 0: expected string, NoneType found
```

**Comment by kennethreitz** [comment]
Ugh, in Python 3 this doesn't result in a type error.
