### ISSUE TITLE
Can't Get pipenv to work on OS X

### ISSUE THREAD

**Issue by Spareo** [kennethreitz/pipenv#518]
I am running OS X Sierra (10.12.6) and have python 2.7.13 installed via home bre

When I do a pip install --user pipenv I get
```
Requirement already satisfied: pipenv in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: virtualenv in /usr/local/lib/python2.7/site-packages (from pipenv)
Requirement already satisfied: pew>=0.1.26 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pipenv)
Requirement already satisfied: requests in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pipenv)
Requirement already satisfied: setuptools>=36.3.0 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pipenv)
Requirement already satisfied: pip-tools>=1.9.0 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pipenv)
Requirement already satisfied: semver in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pipenv)
Requirement already satisfied: pip in /usr/local/lib/python2.7/site-packages (from pipenv)
Requirement already satisfied: pathlib; python_version == "2.7" in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: shutilwhich; python_version == "2.7" in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: pythonz-bd>=1.10.2 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: certifi>=2017.4.17 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from requests->pipenv)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from requests->pipenv)
Requirement already satisfied: idna<2.7,>=2.5 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from requests->pipenv)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from requests->pipenv)
Requirement already satisfied: first in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pip-tools>=1.9.0->pipenv)
Requirement already satisfied: six in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pip-tools>=1.9.0->pipenv)
Requirement already satisfied: click>=6 in /Users/dmitryk/Library/Python/2.7/lib/python/site-packages (from pip-tools>=1.9.0->pipenv)
```

When I navigate to a new directory and do `pipenv install` it always fails with this stack trace
```
Creating a virtualenv for this project...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 994, in install
    ensure_project(three=three, python=python, system=system)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 243, in ensure_project
    ensure_virtualenv(three=three, python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 219, in ensure_virtualenv
    do_create_virtualenv(three=three, python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 516, in do_create_virtualenv
    c = delegator.run(cmd, block=False, timeout=PIPENV_TIMEOUT)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 257, in run
    c.run(block=block, binary=binary)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 149, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I have the following paths exported in my .bash_profile
`export PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:$PATH"`

Output from `pipenv --verson`
```
pipenv, version 6.2.2
```

**Comment by uranusjr** [comment]
You used the `--user` flag, but did not set the appropriate PATH. Add `"$HOME/.local/bin"` to it.

**Comment by Spareo** [comment]
I just tried that and got the same error after sourcing/restarting terminal.

I tried to uninstall pipenv and reinstall with --user flag and have that path in PATH variable but now I can't call pipenv from terminal at all.

This is my .bash_profile now
```
export PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:$HOME/.local/bin:$PATH"
```

Should I try to reinstall it without --user? Do I need to remove all the other dependencies first if I do?

**Comment by Spareo** [comment]
I just went ahead and did the last thing I said in my previous message and now its working again. Not sure what --user was doing exactly, I was following instructions from http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by uranusjr** [comment]
You can find more information about the `--user` flag in [PEP 370](https://www.python.org/dev/peps/pep-0370/). And did you read that yellow box under the instruction telling you to add `~/.local/bin` (effectively the same as `$HOME/.local/bin`) to PATH?

**Comment by Spareo** [comment]
Well the yellow box says to add the USER_BASE path to my $PATH but I did miss the part about the bin part. I added the actual USER_BASE instead of USER_BASE/bin. That was probably the issue. 

The output from `python -m site` on my machine is: 

```
sys.path = [
    '/Users/dmitryk',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
    '/Users/dmitryk/Library/Python/2.7/lib/python/site-packages',
    '/usr/local/lib/python2.7/site-packages',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages',
]
USER_BASE: '/Users/dmitryk/Library/Python/2.7' (exists)
USER_SITE: '/Users/dmitryk/Library/Python/2.7/lib/python/site-packages' (exists)
ENABLE_USER_SITE: True
```

So I added `/Users/dmitryk/Library/Python/2.7` to $PATH and it didn't work but I should have added  `/Users/dmitryk/Library/Python/2.7/bin`. Ooops.

**Comment by DZuz14** [comment]
The official documentation leaves plenty to be desired if errors arise. Wasted a ton of my colleagues time, and Danny Z had to swoop in and figure this Python disaster out. I can attest to Spareos problem. The docs should include an example, with bin appended to an example path.

**Comment by degokay** [comment]
I am having the same issue since yesterday and sadly all the answers are all saying the same thing.

**Comment by techalchemy** [comment]
@degokay you are having which issue?

> sadly all the answers are all saying the same thing.

Do you mean that it is sad because the answers are not helping you? If so, can you provide some information about your issue?
