### ISSUE TITLE
Dependency resolution issues preventing install

### ISSUE THREAD

**Issue by joshourisman** [kennethreitz/pipenv#522]
With pipenv version 6.2.3 I'm experiencing an issue where my Pipfile simply won't install. I've manage to pare my Pipfile down until I have this, very small failing one:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
django = "*"
django-reversion = "*"
```

My larger Pipfile that I extracted this from contains an explicit pytz requirement, so that doesn't seem to be the problem. I've tried locking different versions of both packages, I've tried using Python 2 and 3, but no matter what I do, I get the following error:

```shell
~/Projects $ pipenv --rm                             
Removing virtualenv (/Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP)...                          
~/Projects $ pipenv install --three
Creating a virtualenv for this project...            
⠋Running virtualenv with interpreter /usr/local/bin/python3                                               
Using base prefix '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6'              
New python executable in /Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/bin/python3.6            
Also creating executable in /Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/bin/python            
Installing setuptools, pip, wheel...done.            

Virtualenv location: /Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP                              
No package provided, installing all dependencies.    
Pipfile found at /Users/josho/Projects/Pipfile. Considering this to be the project home.                  
Installing dependencies from Pipfile.lock...         
An error occured while installing! 1/3 - 00:00:07    
Collecting django-reversion==2.0.10                  
  Using cached django-reversion-2.0.10.tar.gz        
    Complete output from command python setup.py egg_info:                                                
    Traceback (most recent call last):               
      File "<string>", line 1, in <module>           
      File "/private/var/folders/k1/qpnzv_415kd1m59nz5z2fnlh0000gn/T/pip-build-shpo6db0/django-reversion/setup.py", line 2, in <module>                                                                             
        from reversion import __version__            
      File "/private/var/folders/k1/qpnzv_415kd1m59nz5z2fnlh0000gn/T/pip-build-shpo6db0/django-reversion/reversion/__init__.py", line 21, in <module>                                                               
        from reversion.revisions import (  # noqa    
      File "/private/var/folders/k1/qpnzv_415kd1m59nz5z2fnlh0000gn/T/pip-build-shpo6db0/django-reversion/reversion/revisions.py", line 7, in <module>                                                               
        from django.core import serializers          
      File "/Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/lib/python3.6/site-packages/django/core/serializers/__init__.py", line 23, in <module>                                                          
        from django.core.serializers.base import SerializerDoesNotExist                                   
      File "/Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/lib/python3.6/site-packages/django/core/serializers/base.py", line 4, in <module>                                                               
        from django.db import models                 
      File "/Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/lib/python3.6/site-packages/django/db/models/__init__.py", line 3, in <module>                                                                  
        from django.db.models.aggregates import *  # NOQA                                                 
      File "/Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/lib/python3.6/site-packages/django/db/models/aggregates.py", line 5, in <module>                                                                
        from django.db.models.expressions import Func, Star                                               
      File "/Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/lib/python3.6/site-packages/django/db/models/expressions.py", line 5, in <module>                                                               
        from django.db.backends import utils as backend_utils                                             
      File "/Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/lib/python3.6/site-packages/django/db/backends/utils.py", line 12, in <module>                                                                  
        from django.utils.timezone import utc        
      File "/Users/josho/.local/share/virtualenvs/Projects-_XCv0GLP/lib/python3.6/site-packages/django/utils/timezone.py", line 8, in <module>                                                                      
        import pytz                                  
    ModuleNotFoundError: No module named 'pytz'      
                                                     
    ----------------------------------------         

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/k1/qpnzv_415kd1m59nz5z2fnlh0000gn/T/pip-build-shpo6db0/django-reversion/                                                        

[================================] 1/3 - 00:00:09
```

If I install each package individually, or even just `pipenv install django-reversion`, there's no problem, and the Pipefile.lock generated does not contain any enlightening differences.

For reference, here's the Pipfile.lock generated from the above Pipfile:

```
{
    "_meta": {
        "hash": {
            "sha256": "222a0b8fd8ea879b222f7b47791a6ad3dc9dff4715676a4886287f193f17d86f"
        },
        "host-environment-markers": {
            "implementation_name": "cpython",
            "implementation_version": "0",
            "os_name": "posix",
            "platform_machine": "x86_64",
            "platform_python_implementation": "CPython",
            "platform_release": "16.7.0",
            "platform_system": "Darwin",
            "platform_version": "Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64",
            "python_full_version": "2.7.13",
            "python_version": "2.7",
            "sys_platform": "darwin"
        },
        "pipfile-spec": 3,
        "requires": {},
        "sources": [
            {
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django": {
            "hashes": [
                "sha256:89162f70a74aac62a53f975128faba6099a7ef2c9d8140a41ae9d6210bda05cd",
                "sha256:1836878162dfdf865492bacfdff0321e4ee8f1e7d51d93192546000b54982b29"
            ],
            "version": "==1.11.5"
        },
        "django-reversion": {
            "hashes": [
                "sha256:9ddadaa38589f6b68d02370f357d835150bb970b7725a01c4280b981d95a6136"
            ],
            "version": "==2.0.10"
        },
        "pytz": {
            "hashes": [
                "sha256:c883c2d6670042c7bc1688645cac73dd2b03193d1f7a6847b6154e96890be06d",
                "sha256:03c9962afe00e503e2d96abab4e8998a0f84d4230fa57afe1e0528473698cdd9",
                "sha256:487e7d50710661116325747a9cd1744d3323f8e49748e287bc9e659060ec6bf9",
                "sha256:43f52d4c6a0be301d53ebd867de05e2926c35728b3260157d274635a0a947f1c",
                "sha256:d1d6729c85acea5423671382868627129432fba9a89ecbb248d8d1c7a9f01c67",
                "sha256:54a935085f7bf101f86b2aff75bd9672b435f51c3339db2ff616e66845f2b8f9",
                "sha256:39504670abb5dae77f56f8eb63823937ce727d7cdd0088e6909e6dcac0f89043",
                "sha256:ddc93b6d41cfb81266a27d23a79e13805d4a5521032b512643af8729041a81b4",
                "sha256:f5c056e8f62d45ba8215e5cb8f50dfccb198b4b9fbea8500674f3443e4689589"
            ],
            "version": "==2017.2"
        }
    },
    "develop": {}
}
```

**Comment by kennethreitz** [comment]
looks like django-reversion is poorly packaged.

**Comment by techalchemy** [comment]
I can take a look at this when I get home

**Comment by kennethreitz** [comment]
the problem is `django-reversion` is not able to install deterministically, due to the fact that it's importing and utilizing django in it's setup.py, which is a big no-no.

**Comment by kennethreitz** [comment]
fixed. the impossible was fixed.

**Comment by techalchemy** [comment]
See b5e8d8fb

**Comment by kennethreitz** [comment]
released!

**Comment by joshourisman** [comment]
That seems to have done it! Thanks for the quick turnaround!

```shell
~/P/p/backend (develop|✔) $ pipenv --rm                                                                   
Removing virtualenv (/Users/josho/.local/share/virtualenvs/backend-7-xBng27)…                             
~/P/p/backend (develop|✔) $ pipenv install --three --dev                                                  
Creating a virtualenv for this project…                                                                   
⠋Running virtualenv with interpreter /usr/local/bin/python3                                               
Using base prefix '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6'              
New python executable in /Users/josho/.local/share/virtualenvs/backend-7-xBng27/bin/python3.6             
Also creating executable in /Users/josho/.local/share/virtualenvs/backend-7-xBng27/bin/python             
Installing setuptools, pip, wheel...done.                                                                 

Virtualenv location: /Users/josho/.local/share/virtualenvs/backend-7-xBng27                               
No package provided, installing all dependencies.                                                         
Pipfile found at /Users/josho/Projects/pingpong/backend/Pipfile.                                          
  Considering this to be the project home.                                                                
Pipfile.lock out of date, updating…                                                                       
Locking [dev-packages] dependencies…                                                                      
⠸Locking [packages] dependencies…                                                                         
⠏Updated Pipfile.lock!                                                                                    
Installing dependencies from Pipfile.lock…                                                                
An error occured while installing django-reversion==2.0.10! Will try again.                               
  🌻   ❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒ 77/77 — 00:03:02                                                   
Installing initially–failed dependencies…                                                                 
Success installing django-reversion==2.0.10! 00:00:00                                                     
  🌵   ❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒❒ 1/1 — 00:00:03                                                     
To activate this project's virtualenv, run the following:                                                 
 $ pipenv shell                                                                                           
~/P/p/backend (develop|✚1) $ 
```

**Comment by kennethreitz** [comment]
✨🍰✨
