### ISSUE TITLE
update doesn't work

### ISSUE THREAD

**Issue by bofm** [kennethreitz/pipenv#525]
```console
# MacOS Sierra
$  pipenv --version
pipenv, version 6.2.4
$  pipenv --update
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1017, in cli
    ensure_latest_pip()
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 154, in ensure_latest_pip
    c = delegator.run('"{0}" install pip'.format(which_pip()))
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 908, in which_pip
    return which('pip')
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 900, in which
    return os.sep.join([project.virtualenv_location] + ['bin/{0}'.format(command)])
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 101, in virtualenv_location
    c = delegator.run('pew dir "{0}"'.format(self.virtualenv_name))
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 78, in virtualenv_name
    sanitized = re.sub(r'[ $`!*@"\\\r\n\t]', '_', self.name)[0:42]
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 42, in name
    self._name = self.pipfile_location.split(os.sep)[-2]
AttributeError: 'NoneType' object has no attribute 'split'
$ python3 -V
Python 3.6.2
```

**Comment by kennethreitz** [comment]
this is currently intended to be run from within a project directory. I'll see if i can whip up a fix.
