### ISSUE TITLE
the recent addition of the 'CADUCEUS' (U+2624) symbol to helps causes UnicodeDecodeError exceptions

### ISSUE THREAD

**Issue by ruslanoid** [kennethreitz/pipenv#529]
> Traceback (most recent call last):
  File "/tmp/tt/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/tmp/tt/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/tt/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/tt/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/tmp/tt/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/tt/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/tt/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/tt/lib/python2.7/site-packages/pipenv/cli.py", line 1026, in cli
    click.echo(format_help(ctx.get_help()))
  File "/tmp/tt/lib/python2.7/site-packages/pipenv/cli.py", line 880, in format_help
    help = help.replace('Usage: pipenv', str('Usage: {0}'.format(crayons.white('☤ pipenv', bold=True))))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16: ordinal not in range(128)

removing it seems to help, but that wouldn't be a solution and I do not know how to workaround it

I am sure this is not happenning to everyone, I am running on Fedora26 if that helps

**Comment by kennethreitz** [comment]
You need to have your locale set on your machine.

**Comment by kennethreitz** [comment]
Make sure `LANG` is set.

**Comment by kennethreitz** [comment]
new release is out, which removes this.
