### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by edubxb** [kennethreitz/pipenv#531]
With the last version, 6.2.7, when running `pipenv` I got this error:

```
$ pipenv
Traceback (most recent call last):
  File "/home/edubxb/.local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/home/edubxb/.local/lib/python3.4/site-packages/pipenv/__init__.py", line 13, in <module>
    from .cli import cli
  File "/home/edubxb/.local/lib/python3.4/site-packages/pipenv/cli.py", line 104, in <module>
    project = Project()
  File "/home/edubxb/.local/lib/python3.4/site-packages/pipenv/project.py", line 36, in __init__
    if 'run' not in sys.argv[1]:
IndexError: list index out of range
```

Also, when using the `shell` subcommand:

```
$ pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
Traceback (most recent call last):
  File "/home/edubxb/.local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/home/edubxb/.local/lib/python3.4/site-packages/pipenv/__init__.py", line 13, in <module>
    from .cli import cli
  File "/home/edubxb/.local/lib/python3.4/site-packages/pipenv/cli.py", line 104, in <module>
    project = Project()
  File "/home/edubxb/.local/lib/python3.4/site-packages/pipenv/project.py", line 36, in __init__
    if 'run' not in sys.argv[1]:
IndexError: list index out of range
```

**Comment by kennethreitz** [comment]
nice catch!

**Comment by kennethreitz** [comment]
This is what open source is all about! next release is out, which fixes this.
