### ISSUE TITLE
AttributeError: '_NamespacePath' object has no attribute 'sort' when running pipenv on arch

### ISSUE THREAD

**Issue by BenDoan** [kennethreitz/pipenv#552]
I installed pipenv (with pip) on my arch machine recently, and it's giving me an exception on startup.

Googling around it seems like it might related to this issue: pypa/setuptools#885, but my setuptools is fully updated which seems to be the fix listed in that thread.

## output
```
→ sudo pip install --upgrade pipenv pip setuptools
→ pipenv --help
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/usr/lib/python3.6/site-packages/pipenv/__init__.py", line 13, in <module>
    from .cli import cli
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 20, in <module>
    import pip
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

## system info
```
→ pip -V
pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)

→ pip show pipenv
Name: pipenv
Version: 7.0.5
Summary: Sacred Marriage of Pipfile, Pip, & Virtualenv.
Home-page: https://github.com/kennethreitz/pipenv
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: MIT
Location: /usr/lib/python3.6/site-packages
Requires: semver, setuptools, pip-tools, pip, pew, virtualenv, requests

→ pip show setuptools
Name: setuptools
Version: 36.4.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/lib/python3.6/site-packages
Requires: 

→ uname -a
Linux jubal 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux

→ python -V
Python 3.6.2

```

**Comment by kennethreitz** [comment]
this looks to be a problem with pip, not with pipenv.

**Comment by hobarrera** [comment]
@BenDoan Did you manage to fix this? I'm having the exact same issue.

**Comment by BenDoan** [comment]
@hobarrera Unfortunately no.

**Comment by hobarrera** [comment]
I looked through https://github.com/pypa/setuptools/issues/885, and I don't entirely follow.

This looks like an issue within `pip`. Specifically, it's due to code vendored in pip. The thing is, I don't quite understand in which sort of scenario pipenv _could_ work, since there seems to be a reliance on a broken upstream feature. 😐

**Comment by kennethreitz** [comment]
we use a patched pip, so we can fix anything needed!

**Comment by hobarrera** [comment]
Ah, good point. I didn't notice pipenv used a patched pip.

If that's the case, then isn't this a `pipenv` issue? The patched/vendored pip seems to be what's failing:
```
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.0.2', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/pipenv/__init__.py", line 17, in <module>
    from .cli import cli
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 22, in <module>
    import pip
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

**Comment by kennethreitz** [comment]
nope, still a pip issue. we just make a few small cosmetic changes to the codebase

**Comment by kennethreitz** [comment]
do not specify setuptools in your Pipfile. that is bad.

**Comment by kennethreitz** [comment]
those are system components.

**Comment by kennethreitz** [comment]
you are using it wrong.

**Comment by hobarrera** [comment]
> do not specify setuptools in your Pipfile. that is bad.

I'm not doing that; I don't have a Pipfile.

> you are using it wrong.

I'm not sure how I'm using it wrong. I'm following the instructions [here](https://pipenv.readthedocs.io/en/latest/basics.html#installing-packages-for-your-project):

```
$ mkdir myproject
$ cd myproject
$ pipenv install requests
```

**Comment by hobarrera** [comment]
> nope, still a pip issue. we just make a few small cosmetic changes to the codebase

This confuses me. If it's a pip issue, and pip is vendored, I don't quite understand how pipenv would work on any other setup. I'm clearly missing something obvious, but I'm not sure what.

**Comment by nikaro** [comment]
Same issue here. What can be done?

**Comment by uranusjr** [comment]
@nikaro 

1. Upgrade to the latest version.
2. Post your actual trackback. Don’t just say it’s the same—the code base has since changed a lot. It is impossible you have the same trackback running the correct version.
3. Supply additional information if asked to.
4. Have patience, and try to debug the problem on your own (or find a real person to debug it physically on your machine). We don’t have access to your environment, and really can’t spend much time on your particular problem (unless it is affecting a lot of people).

**Comment by nikaro** [comment]
Hello,

Sorry for the lack of information. I am already on the latest version.

Here is the traceback:
```
$ pipenv
Traceback (most recent call last):
  File "/home/nicolas/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/cli.py", line 62, in cli
    from . import core
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/core.py", line 25, in <module>
    import pipdeptree
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/vendor/pipdeptree.py", line 16, in <module>
    import pip
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/nicolas/.local/lib/python3.6/site-packages/pipenv/../pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

**Comment by kennethreitz** [comment]
@nikaro are you using ubuntu's pip?

**Comment by nikaro** [comment]
@kennethreitz no, i'm on Fedora 27, python3-pip is installed, but normally i use a local pip (`pip3 install --user -U pip`):
```
$ which pip
/home/nicolas/.local/bin/pip
```
```
$ pip -V
pip 9.0.1 from /home/nicolas/.local/lib/python3.6/site-packages (python 3.6)
```

**Comment by atomotic** [comment]
same problem for me, macos here:

```
➜  ~ python -V
Python 3.6.4
➜  ~ pip -V
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
```

**Comment by tayloramurphy** [comment]
Getting this same error on Mac OS X 10.13.3

Main installed details

```
) pipenv --version
pipenv, version 11.5.3
(pipenvtest-H9Pwl4cU) tmurphy@Doctor-Murphy|~/Projects/GitLab/dev/pipenvtest
) python -V
Python 3.5.3
(pipenvtest-H9Pwl4cU) tmurphy@Doctor-Murphy|~/Projects/GitLab/dev/pipenvtest
) pip -V
pip 9.0.1 from /Users/tmurphy/.local/share/virtualenvs/pipenvtest-H9Pwl4cU/lib/python3.5/site-packages (python 3.5)
```

I'm able to reliably produce the error with the following steps (which or without activating the shell):

```
mkdir pipenvtest
cd pipenvtest
pipenv install --python 3.5.3
pipenv shell #optional
pipenv install requests
pipenv install psycopg2
pipenv install configparser
```
Which results in 
```
) pipenv install configparser
Installing configparser…
Collecting configparser
Installing collected packages: configparser
Successfully installed configparser-3.5.0

Adding configparser to Pipfile's [packages]…
Pipfile.lock (e4feee) out of date, updating to (a88671)…
Locking [dev-packages] dependencies…
ndor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/../pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/../pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/../pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/../pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/../pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

Anything I should try to fix this / get more debug info?

**Comment by kennethreitz** [comment]
Try v11.6.0.

**Comment by tayloramurphy** [comment]
Fixed with the upgrade. Thank you @kennethreitz !

**Comment by kennethreitz** [comment]
I love solving one problem solves another :)

**Comment by gvpinto** [comment]
I way I solved it was to put a print statement print(orig_path) in the offending __init__.py file just before orig_path.sort(key=position_in_sys_path) and that gave me clues as to what was going on and then I found there was a collision between site packages in my case under Python 3.6 install and Anaconda install and I delete the ones in Python 3.6 which I didn't need.
