### ISSUE TITLE
pipenv install --pre <lib>

### ISSUE THREAD

**Issue by foxmask** [kennethreitz/pipenv#602]
Hi,

I met the following error when trying to do 

```python
pipenv install --pre xhtml2pdf 
```

```
Creating a virtualenv for this project…
⠋Using base prefix '/usr/local'
New python executable in /home/foxmask/.local/share/virtualenvs/toto-CkuOmaEa/bin/python3.6
Also creating executable in /home/foxmask/.local/share/virtualenvs/toto-CkuOmaEa/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/foxmask/.local/share/virtualenvs/toto-CkuOmaEa
Creating a Pipfile for this project…
Installing --pre…
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2993, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'--pre'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1469, in install
    c = pip_install(package_name, ignore_hashes=True, allow_global=system, no_deps=False, verbose=verbose)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1123, in pip_install
    if [x for x in requirements.parse(package_name.split('--hash')[0])][0].vcs:
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1123, in <listcomp>
    if [x for x in requirements.parse(package_name.split('--hash')[0])][0].vcs:
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirements/parser.py", line 50, in parse
    yield Requirement.parse(line)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirements/requirement.py", line 220, in parse
    return cls.parse_line(line)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirements/requirement.py", line 198, in parse_line
    pkg_req = Req.parse(line)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3038, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2986, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2995, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'--pre'"
```

it's not very important, it's just in case ...

**Comment by kennethreitz** [comment]
we don't support `--pre`. where did you see that documented?

**Comment by foxmask** [comment]
nowhere, i didnt see that was forbidden ;)

**Comment by kennethreitz** [comment]
this works now!

**Comment by foxmask** [comment]
👍

Would you like a new ticket for this https://twitter.com/foxxmask/status/911186056510410752 ?

**Comment by kennethreitz** [comment]
no i'm not interested in that
