### ISSUE TITLE
pipenv --three , undefined symbol  error

### ISSUE THREAD

**Issue by EddieZhao** [kennethreitz/pipenv#61]
```
[vagrant@dev sync]$ pipenv --three
Creating a virtualenv for this project...
Running virtualenv with interpreter /usr/local/bin/python3
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/local/lib/python3.5/base64.py", line 10, in <module>
    import struct
  File "/usr/local/lib/python3.5/struct.py", line 13, in <module>
    from _struct import *
ImportError: /usr/local/lib/python2.7/site-packages/_struct.so: undefined symbol: PyString_AsString

Virtualenv location: /home/vagrant/test/sync/.venv
```

**Comment by kennethreitz** [comment]
this looks like an issue with virtualenv, not pipenv
