### ISSUE TITLE
UnicodeDecodeError when installing ansible

### ISSUE THREAD

**Issue by marcinkuzminski** [kennethreitz/pipenv#623]
Hi,

I installed pipenv 7.4.3, and trying to install ansible (pipenv install ansible) i get this traceback:

```
Adding ansible to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/Users/marcink/.virtualenvs/cli/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/cli.py", line 1555, in install
    do_lock(system=system)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/cli.py", line 965, in do_lock
    project=project
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/utils.py", line 222, in resolve_deps
    resolved_tree = resolver.resolve()
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/patched/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/patched/pip/download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 551, in untar_file
    path = os.path.join(location, fn)
  File "/Users/marcink/.virtualenvs/cli/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 66: ordinal not in range(128)
```

**Comment by techalchemy** [comment]
Is your locale set up correctly? From the command line what is the value of the following command: `echo $LANG && echo $LC_CTYPE && echo $LC_MESSAGES && echo $LC_COLLATE`

These need to be set to "en_us.UTF-8" in your `.bash_profile` or equivalent file

**Comment by marcinkuzminski** [comment]
Hi,

The output of these is:
```
en_GB.UTF-8
en_GB.UTF-8

```
So last two aren't set. But why pip works, virtualenv works and pipenv throws an error ?

**Comment by kennethreitz** [comment]
pip issue, not pipenv issue

**Comment by AlJohri** [comment]
@marcinkuzminski more specifically, this seems like a pip-tools issue

related issues:
- https://github.com/jazzband/pip-tools/issues/224
- https://github.com/jazzband/pip-tools/issues/439
- https://github.com/jazzband/pip-tools/issues/433
- https://github.com/jazzband/pip-tools/pull/451

if you read through some of the issues, people have a lot of issues reproducing this bug.

> 10 minutes later and the same command doesn't give exception. Everything is 100% the same. Git reset same.
https://github.com/jazzband/pip-tools/issues/439#issuecomment-273664824

>Unfortunately, after fixing it once with @byjott's approach, I was unable to reproduce - if you're debugging, watch out! I can reproduce at-will now though, if anyone would like more info.
https://github.com/jazzband/pip-tools/issues/433#issuecomment-277825142

**Comment by kennethreitz** [comment]
let's get this fixed in pip-tools then!
