### ISSUE TITLE
pipenv update broken

### ISSUE THREAD

**Issue by nishantuniyal** [kennethreitz/pipenv#636]
Upgraded pipenv to the latest release using pipsi and getting an error on trying to upgrade the packages.

> Traceback (most recent call last):
  File "/home/user/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 2094, in update
    do_init(dev=dev, verbose=verbose)
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 1139, in do_init
    do_lock(system=system)
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 941, in do_lock
    project=project
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/utils.py", line 409, in resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/user/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpfOJU0Lbuild/ipython/

**Comment by nishantuniyal** [comment]
After reading the previous closed issues it sounds like a ipython problem rather than pipenv. I will remove ipython from the pipfile and reinstall again.

**Comment by kennethreitz** [comment]
let me know how it goes!
