### ISSUE TITLE
Traceback on installing BeautifulSoup==3.2.1

### ISSUE THREAD

**Issue by cpdean** [kennethreitz/pipenv#651]
Hey there! Trying out pipenv on a project I work on that has a dependency on `BeautifulSoup==3.2.1`

When I try to install this dependency I get an error.  Steps for reproducing and traceback:

```
 🍔  - ❯❯❯ mkdir soup_problem
- - -
~ 0
 🍔  - ❯❯❯ cd soup_problem/
- - -
soup_problem 0
 🍔  - ❯❯❯ python --version
Python 2.7.13
- - -
soup_problem 0
 🍔  - ❯❯❯ pipenv --version
pipenv, version 7.4.6
- - -
soup_problem 0
 🍔  - ❯❯❯ pipenv --two
Creating a virtualenv for this project…
Using /usr/local/bin/python2 to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /Users/cdean/.virtualenvs/soup_problem-7VIi_C6l/bin/python2.7
Also creating executable in /Users/cdean/.virtualenvs/soup_problem-7VIi_C6l/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/cdean/.virtualenvs/soup_problem-7VIi_C6l
Creating a Pipfile for this project…
- - -
soup_problem 0
 🍔  - ❯❯❯ pipenv install BeautifulSoup==3.2.1
Installing BeautifulSoup==3.2.1…
Collecting BeautifulSoup==3.2.1
Installing collected packages: BeautifulSoup
Successfully installed BeautifulSoup-3.2.1

Adding BeautifulSoup==3.2.1 to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1621, in install
    do_lock(system=system)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1009, in do_lock
    project=project
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 447, in resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/lib/python3.6/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.6/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/jc/jdnjsh991dg3zbl75z4p5hh80000gp/T/tmpgx3mhdsobuild/beautifulsoup/
- - -
soup_problem 1
 🍔  - ❯❯❯ pipenv run python -c "import BeautifulSoup; print BeautifulSoup.__version__"
3.2.1
- - -
soup_problem 0
 🍔  - ❯❯❯
```

So the installation works but then something else crashes, causing pipenv to ultimately return an errorcode 1 (as seen in my prompt).

How do I find out what's going wrong behind the exception `pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1` ?  

Thanks!

**Comment by cpdean** [comment]
Additional proof it gets installed correctly, the imported module lives in the venv:

``` 🍔  - ❯❯❯ pipenv run python -c "import BeautifulSoup; print BeautifulSoup.__file__"
/Users/cdean/.virtualenvs/soup_problem-7VIi_C6l/lib/python2.7/site-packages/BeautifulSoup.pyc
```

**Comment by frenetic** [comment]
There is a new Pipenv version, `7.5.1`, would you mind testing with it?

**Comment by kennethreitz** [comment]
Beautiful soup isn't packaged well, and won't run on Python 3. That's your problem.

**Comment by AlJohri** [comment]
@cpdean is it possible to use `beautifulsoup4` in your project?

**Comment by HsuanTingLu** [comment]
beautifulsoup4 can work

**Comment by brainwane** [comment]
@kennethreitz I'd appreciate knowing more about the problem with the packaging for `beautifulsoup` so I can poke the maintainer to fix it.

**Comment by AlJohri** [comment]
@brainwane usually you can clone the problematic package and run `python setup.py egg_info`. the stacktrace should tell you the issue. lots of times its a circular dependency upon itself or assumes some package is installed
