### ISSUE TITLE
FileNotFoundError from 'pipenv install requests' when pwd is a symlink

### ISSUE THREAD

**Issue by tartley** [kennethreitz/pipenv#661]
I cd to my project in this directory:

    $ pwd
    /home/jhartley/docs/code/unfinished/gloopy

But that's actually using a symlink, ~/docs -> ~/Dropbox/jon-data. The actual directory name is:

    $ pwd -P # resolves symlinks to give actual directory name
    /home/jhartley/Dropbox/jon-data/code/unfinished/gloopy

Note 'Dropbox' has a capital 'D'.

I just installed pipenv for first time ever. No Pipfile is present.
    $ pipenv install requests
Gives the traceback below, which includes "Dropbox" spelled incorrectly, with a lower case "d".

pipenv, version 7.6.3.
Ubuntu 17.04.
Pythons 2.7, 3.5 and 3.6 are installed, but 'python' is python2.7.
Using --three doesn't help.

I'm happy to do any more diagnostics if it helps.

```
Installing requests…
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Installing collected packages: idna, chardet, urllib3, certifi, requests
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22

Adding requests to Pipfile's [packages]…
P.S. You have excellent taste! ✨ 🍰 ✨
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Error [Errno 2] No such file or directory: '/home/jhartley/dropbox/jon-data/code/unfinished/gloopy/' while executing command python setup.py egg_info
Traceback (most recent call last):
  File "/home/jhartley/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/cli.py", line 1682, in install
    do_lock(system=system, pre=pre)
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/cli.py", line 1044, in do_lock
    pre=pre
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/utils.py", line 468, in resolve_deps
    resolved_tree.update(resolver.resolve())
  File "/home/jhartley/.local/lib/python3.5/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/jhartley/.local/lib/python3.5/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/jhartley/.local/lib/python3.5/site-packages/piptools/resolver.py", line 262, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/home/jhartley/.local/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/patched/pip/req/req_set.py", line 518, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/patched/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/patched/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/jhartley/.local/lib/python3.5/site-packages/pipenv/patched/pip/utils/__init__.py", line 667, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jhartley/dropbox/jon-data/code/unfinished/gloopy/'
```

**Comment by tartley** [comment]
I'm trying a minimal repro now, from a symlink ~/myproj which points to empty dir ~/MyProj. But no traceback there. I'll keep experimenting and report back...

**Comment by tartley** [comment]
I can't reproduce it in ~/myproj -> ~/MyProj, not even with a wholesale copy of my entire project in there.

And now that I go back to my original project dir, I can't reproduce it there either now - although I saw it happen six or eight times earlier. It only happened when I deleted Pipfile* and removed the virtualenv, so 
that pipenv was working from a clean slate. Darn. If I don't post a reliable minimal repro tonight then feel free to close this. Apologies for the noise.

**Comment by tartley** [comment]
Back in my original project directory.
If I remove the line "-e ." from my requirements.txt, then it works fine.
With that line present, I get the traceback.
It's late for me. I'll try to put that into a minimal repro over the weekend.

**Comment by kennethreitz** [comment]
are you using the latest version?

**Comment by tartley** [comment]
Yes. Installed from PyPI last night.

$ pipenv --version
pipenv, version 7.6.3

$ pip install --user -U pipenv
Requirement already up-to-date: pipenv in /home/jhartley/.local/lib/python3.6/site-packages
[...]

**Comment by kennethreitz** [comment]
Please share your `Pipfile`.

**Comment by kennethreitz** [comment]
cannot reproduce.

**Comment by tartley** [comment]
This morning, neither can I. **Feel free to close**, sorry for the noise.

I'm speculating that I got something into a bad state somehow, maybe something like:
* When I added ~/.local/bin to my PATH in .profile, I just sourced .profile again rather than logging out/in. That sources in turn .bashrc, and is probably not perfectly idempotent (eg. adding things to PATH.)
* When getting started, I was intermingling pipenv commands with my old pip and virtualenvwrapper commands (eg. before I discovered pipenv --rm, I was using rmvirtualenv.)

**Comment by tartley** [comment]
FWIW, yesterday my Pipfile had the erroneously lower-cased path in it, but today it just reads:

```
$ cat Pipfile
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

"0269f63" = {path = "/home/jhartley/Dropbox/jon-data/code/unfinished/gloopy", editable = true}
numpy = "==1.13.0rc2"
pyopengl = "==3.1.0"
"pyopengl-accelerate" = "==3.1.0"
pyglet = "==1.2.4"
requests = "*"


[dev-packages]

```

**Comment by kennethreitz** [comment]
great news! yeah we fixed that bug recently :)

**Comment by kennethreitz** [comment]
\o/

**Comment by kennethreitz** [comment]
we were lower casing all the things until like yesterday

**Comment by ryanhiebert** [comment]
I hit the lowercasing thing today, with the latest pypi version at the time. I'll check to make sure I'm up to date and everything when I get a chance, but I'm hopeful that you have already fixed my issue.
