### ISSUE TITLE
Exception from bad interaction between `safety.zip/yaml` and venv `yaml`

### ISSUE THREAD

**Issue by simonpercivall** [kennethreitz/pipenv#668]
When running `pyenv check` in an environment with `yaml` installed, the `cyaml` import of the optionally compiled `_yaml` runs `import yaml`, which is the venv installed module, causing the exception below.

These versions are all 3.12, AFAICT.

I'm guessing the easiest way of fixing this is to remove the attempt to import `_yaml`.

```
An error occured:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/person/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/safety.zip/__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/person/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/safety.zip/safety/cli.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/person/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/safety.zip/safety/util.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/person/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/safety.zip/dparse/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/person/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/safety.zip/dparse/parser.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/person/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/safety.zip/yaml/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/person/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/safety.zip/yaml/yaml3/__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/person/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/safety.zip/yaml/yaml3/cyaml.py", line 5, in <module>
  File "ext/_yaml.pyx", line 18, in init _yaml (ext/_yaml.c:23185)
AttributeError: module 'yaml' has no attribute 'error'
```

**Comment by kennethreitz** [comment]
make sure you're running the latest version.

**Comment by kennethreitz** [comment]
we should just remove the yaml dependency altogether, as we're not using it, as far as i know

**Comment by simonpercivall** [comment]
Yeah, sorry, should have added the `pipenv` version: It's `7.6.2`.

**Comment by kennethreitz** [comment]
okay a new version of pipenv is out, which removes yaml entirely. try that.

**Comment by kennethreitz** [comment]
let me know how it goes, please!

**Comment by simonpercivall** [comment]
New version works wonderfully. Thank you!

**Comment by kennethreitz** [comment]
\o/

**Comment by kennethreitz** [comment]
nothing like modfying other people code :)
