### ISSUE TITLE
using pipenv in container fails for first run...

### ISSUE THREAD

**Issue by goern** [kennethreitz/pipenv#677]
Moin all, I have been using pipenv in a CentOS7 container, and it fails on the first `pipenv install`. I have attached a log, let me know what else you want to have a look at...

```
$ docker pull centos/python-35-centos7
[...]
$ docker run --rm -ti  centos/python-35-centos7 /bin/bash
(app-root)pip install pipenv
Collecting pipenv
  Downloading pipenv-7.7.9.tar.gz (3.6MB)
    100% |████████████████████████████████| 3.6MB 14.0MB/s
Collecting virtualenv (from pipenv)
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 30.1MB/s
Collecting pew>=0.1.26 (from pipenv)
  Downloading pew-0.1.26-py2.py3-none-any.whl
Collecting pip>=9.0.1 (from pipenv)
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 16.0MB/s
Collecting pip-tools>=1.9.0 (from pipenv)
  Downloading pip_tools-1.9.0-py2.py3-none-any.whl
Collecting requests>2.0.0 (from pipenv)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 90kB 9.8MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools>=17.1 in /opt/app-root/lib/python3.5/site-packages (from pew>=0.1.26->pipenv)
Collecting pythonz-bd>=1.10.2 (from pew>=0.1.26->pipenv)
  Downloading pythonz_bd-1.11.4-py3-none-any.whl (117kB)
    100% |████████████████████████████████| 118kB 16.2MB/s
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv)
  Downloading virtualenv-clone-0.2.6.tar.gz
Collecting click>=6 (from pip-tools>=1.9.0->pipenv)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 73kB 7.4MB/s
Collecting six (from pip-tools>=1.9.0->pipenv)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting first (from pip-tools>=1.9.0->pipenv)
  Downloading first-2.0.1-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>2.0.0->pipenv)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 57kB 10.6MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>2.0.0->pipenv)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 135kB 16.6MB/s
Collecting certifi>=2017.4.17 (from requests>2.0.0->pipenv)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 352kB 10.6MB/s
Collecting urllib3<1.23,>=1.21.1 (from requests>2.0.0->pipenv)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 135kB 30.6MB/s
Collecting resumable-urlretrieve (from pythonz-bd>=1.10.2->pew>=0.1.26->pipenv)
  Downloading resumable_urlretrieve-0.1.5-py2.py3-none-any.whl
Installing collected packages: virtualenv, idna, chardet, certifi, urllib3, requests, resumable-urlretrieve, pythonz-bd, virtualenv-clone, pew, pip, click, six, first, pip-tools, pipenv
  Running setup.py install for virtualenv-clone
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
  Running setup.py install for pipenv
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 click-6.7 first-2.0.1 idna-2.6 pew-0.1.26 pip-9.0.1 pip-tools-1.9.0 pipenv-7.7.9 pythonz-bd-1.11.4 requests-2.18.4 resumable-urlretrieve-0.1.5 six-1.11.0 urllib3-1.22 virtualenv-15.1.0 virtualenv-clone-0.2.6
(app-root)pipenv install requests
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Creating a Pipfile for this project…
Discovering imports from local codebase…
Traceback (most recent call last):
  File "/opt/app-root/bin/pipenv", line 9, in <module>
    load_entry_point('pipenv==7.7.9', 'console_scripts', 'pipenv')()
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/cli.py", line 1610, in install
    ensure_project(three=three, python=python, system=system, warn=True)
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/cli.py", line 593, in ensure_project
    ensure_pipfile(validate=validate)
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/cli.py", line 324, in ensure_pipfile
    for req in import_from_code('.'):
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/cli.py", line 278, in import_from_code
    for r in pipreqs.get_all_imports(path):
  File "/opt/app-root/lib/python3.5/site-packages/pipenv/vendor/pipreqs/pipreqs.py", line 106, in get_all_imports
    with open(join("stdlib"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/app-root/lib/python3.5/site-packages/pipenv/vendor/pipreqs/stdlib'
(app-root)pipenv install requests
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Installing requests…
Requirement already satisfied: requests in /opt/app-root/lib/python3.5/site-packages
Requirement already satisfied: idna<2.7,>=2.5 in /opt/app-root/lib/python3.5/site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/app-root/lib/python3.5/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /opt/app-root/lib/python3.5/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /opt/app-root/lib/python3.5/site-packages (from requests)

Adding requests to Pipfile's [packages]…
P.S. You have excellent taste! ✨ 🍰 ✨
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!
```

**Comment by numshub** [comment]
I found the same behaviour. It looks like during pipenv installation both stdlib and mappings are not copied in the vendor/pipreqs directory.

**Comment by kennethreitz** [comment]
this should now be fixed.
