### ISSUE TITLE
Pipenv install -c fails due to lack of pipreqs/stdlib

### ISSUE THREAD

**Issue by tdi** [kennethreitz/pipenv#680]
pipenv, version 7.7.9 and 7.8.2 too

I wanted to check out the new awesome feature:

```
(roleador-AUjzKksZ) ➜  roleador pipenv install -c .
Discovering imports from local codebase…
Traceback (most recent call last):
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/cli.py", line 1618, in install
    for req in import_from_code(code):
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/cli.py", line 278, in import_from_code
    for r in pipreqs.get_all_imports(path):
  File "/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/vendor/pipreqs/pipreqs.py", line 106, in get_all_imports
    with open(join("stdlib"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tdi/.virtualenvs/roleador-AUjzKksZ/lib/python3.6/site-packages/pipenv/vendor/pipreqs/stdlib'
```

This is what the directory looks like: 

```
(roleador-AUjzKksZ) ➜  roleador ls -l
total 20
-rw-r--r-- 1 tdi staff  204 Sep 23 14:15 Pipfile
-rw-r--r-- 1 tdi staff 5020 Sep 23 14:09 Pipfile.lock
-rw-r--r-- 1 tdi staff  102 Sep 23 14:15 main.py
-rw-r--r-- 1 tdi staff  114 Sep 23 14:11 roles.yaml
```

**Comment by kennethreitz** [comment]
try again with latest

**Comment by kennethreitz** [comment]
v7.8.2

**Comment by tdi** [comment]
I have tried - have the same.

**Comment by kennethreitz** [comment]
it's working for me, and we solved the underlying issue. please ensure you're actually running the latest version. if you used `pipenv --update` if may have failed.
