### ISSUE TITLE
Installing pipenv fails due to syntax in its own Pipfile

### ISSUE THREAD

**Issue by tomviner** [kennethreitz/pipenv#683]
Commit f9c4b59284fd25057065421a79c955351dce4da0 uses this extended spec to the `Pipfile`:
```
"pytest-xdist" = {version = "*", os_name = '"==posix"'}
```

This results in the following error when installing pipenv with pipenv:
```
 $ pipenv --version
pipenv, version 7.4.4

tom:~/dev/pipenv 
 $ pipenv install 
No package provided, installing all dependencies.
Pipfile.lock out of date, updating…
Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "/home/tom/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tom/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 1540, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose)
  File "/home/tom/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 1139, in do_init
    do_lock(system=system)
  File "/home/tom/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 941, in do_lock
    project=project
  File "/home/tom/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/utils.py", line 385, in resolve_deps
    constraint = [c for c in pip.req.parse_requirements(t, session=pip._vendor.requests)][0]
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/req/req_file.py", line 158, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 235, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 91, in __init__
    "Invalid requirement: '%s'\n%s" % (req, add_msg))
pip.exceptions.InstallationError: Invalid requirement: 'pytest-xdist*'
Traceback (most recent call last):
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/home/tom/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "u'*'"
```

**Comment by tomviner** [comment]
Ah think was my fault for using pipenv 7.4.4 instead of latest 7.8.6.
