### ISSUE TITLE
Pipenv tries to install conditional dependency that it should not

### ISSUE THREAD

**Issue by HeyHugo** [kennethreitz/pipenv#695]
Hi!

I think pipenv might be trying to install a package from `extras_require` that has a conditional dependency looking like this `":python_version=='2.7'": ["functools32"],` when running python 3 you can see full setup.py [here](https://github.com/Julian/jsonschema/blob/master/setup.py)

Result is that it is crashing during the locking
`pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/sf/3jbs_z291zj5sh_mc967y1_r0000gn/T/tmpJmGecKbuild/functools32/`

```
➞ pipenv --version
pipenv, version 7.9.2
```

minimal reproducible commands
```
mkdir testenv
cd testenv
pipenv --three
pipenv install jsonschema
```

**Comment by HeyHugo** [comment]
Hm strange can't reproduce this any more :)

**Comment by kennethreitz** [comment]
it will try to install it, and it won't. it'll give you a nice message saying that it's not valid on your system.

**Comment by alercunha** [comment]
I have this issue. Running the commands described by @HeyHugo gives me that exact error. Not sure what the problem is exactly, the library seems to be compatible with python3 no ?

**Comment by vphilippon** [comment]
@alercunha Make sure you have `pipenv` 8.2.7 installed, and be sure to clear the cache with `pipenv lock --clear`. The cache could have invalid dependencies left, caused from a bug that was in 8.2.6.

**Comment by alercunha** [comment]
Great, it works now! From the thread above I thought the issue wasn't fixed.

**Comment by knkski** [comment]
I'm able to reproduce this with `pipenv` 8.2.7:

```
$ mkdir testenv && cd testenv/

$ pipenv --three
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /virtualenvs/testenv-R-rIEEmv/bin/python3
Also creating executable in /virtualenvs/testenv-R-rIEEmv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /virtualenvs/testenv-R-rIEEmv
Creating a Pipfile for this project…

$ pipenv install jsonschema
Installing jsonschema…
Collecting jsonschema
  Using cached jsonschema-2.6.0-py2.py3-none-any.whl
Installing collected packages: jsonschema
Successfully installed jsonschema-2.6.0

Adding jsonschema to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.7', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1847, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1082, in do_lock
    pre=pre
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 452, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 278, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpbXS0x0build/functools32/

$ pipenv lock --clear
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.7', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1969, in lock
    do_lock(verbose=verbose, clear=clear, pre=pre)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1082, in do_lock
    pre=pre
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 452, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 278, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmprDZiZybuild/functools32/
```

**Comment by alercunha** [comment]
I just tried the exact same steps as you did (even creating a virtualenv that already existed -- which I can infere from your logs) but it works just fine here. Are you sure you have 8.2.7 installed?

**Comment by knkski** [comment]
Reasonably sure. Running `pip list | grep pipenv` (or `sudo pip list | grep pipenv`) gives me `pipenv (8.2.7)`, and the output above says `load_entry_point('pipenv==8.2.7', 'console_scripts', 'pipenv')()`.

Additionally, grepping through the libraries from the traceback above shows this:

```
$ grep -r '8\.2\..*' /usr/local/lib/python2.7/dist-packages/pipenv/
/usr/local/lib/python2.7/dist-packages/pipenv/__version__.py:__version__ = '8.2.7'
/usr/local/lib/python2.7/dist-packages/pipenv/pipenv.1:.TH "PIPENV" "1" "Oct 07, 2017" "8.2.7" "pipenv"
Binary file /usr/local/lib/python2.7/dist-packages/pipenv/__version__.pyc matches
```

Are there any other checks that I should do?

**Comment by knkski** [comment]
Is `pipenv` somehow reading the fact that it is itself running on Python 2.7 and getting confused? If I install `pipenv` inside of the virtual environment, and then run `pipenv install jsonschema`, it works:

```
$ mkdir testenv && cd testenv

$ pipenv --three
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /virtualenvs/testenv-E5QAKiRb/bin/python3
Also creating executable in /virtualenvs/testenv-E5QAKiRb/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /virtualenvs/testenv-E5QAKiRb
Creating a Pipfile for this project…

$ pipenv shell
Spawning environment shell (/usr/bin/fish). Use 'exit' to leave.
$ source /virtualenvs/testenv-E5QAKiRb/bin/activate.fish

(testenv-E5QAKiRb) $ pip install pipenv
Collecting pipenv
Collecting flake8 (from pipenv)
  Using cached flake8-3.4.1-py2.py3-none-any.whl
Collecting requests>2.18.0 (from pipenv)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting virtualenv (from pipenv)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in /virtualenvs/testenv-E5QAKiRb/lib/python3.5/site-packages (from pipenv)
Collecting pew>=0.1.26 (from pipenv)
  Using cached pew-1.1.0-py2.py3-none-any.whl
Collecting urllib3>=1.21.1 (from pipenv)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8->pipenv)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8->pipenv)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting pyflakes<1.6.0,>=1.5.0 (from flake8->pipenv)
  Using cached pyflakes-1.5.0-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>2.18.0->pipenv)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>2.18.0->pipenv)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>2.18.0->pipenv)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=17.1 in /virtualenvs/testenv-E5QAKiRb/lib/python3.5/site-packages (from pew>=0.1.26->pipenv)
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv)
Installing collected packages: pycodestyle, mccabe, pyflakes, flake8, idna, chardet, certifi, urllib3, requests, virtualenv, virtualenv-clone, pew, pipenv
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 flake8-3.4.1 idna-2.6 mccabe-0.6.1 pew-1.1.0 pipenv-8.2.7 pycodestyle-2.3.1 pyflakes-1.5.0 requests-2.18.4 urllib3-1.22 virtualenv-15.1.0 virtualenv-clone-0.2.6

(testenv-E5QAKiRb) $ pipenv install jsonschema
Installing jsonschema…
Collecting jsonschema
  Using cached jsonschema-2.6.0-py2.py3-none-any.whl
Installing collected packages: jsonschema
Successfully installed jsonschema-2.6.0

Adding jsonschema to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (1ce420)!
```

**Comment by alercunha** [comment]
Yup, reproduced it here by doing:

```
$ python2 -m pipenv --three
$ python2 -m pipenv install jsonschema
```

**Comment by vphilippon** [comment]
Urgh, that would make sense: `pip` will select the wheels for the current platform, so if it runs under Python 2, it will go with that.
Although, I though there was a patch to be able to tell `pip` which version of python was used. Maybe the patch doesn't cover everything here.

**Comment by HeyHugo** [comment]
I think it was installing pipenv via `pip3` that fixed this for me.
