### ISSUE TITLE
FileNotFoundError when running in subdirectory

### ISSUE THREAD

**Issue by uranusjr** [kennethreitz/pipenv#706]
To reproduce:

```bash
$ mkdir -p project/subdir
$ cd project
$ pipenv --three   # Init project in "project"
$ cd subdir
$ pipenv run python
```

Error message:

```
Traceback (most recent call last):
  File "bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 2036, in run
    ensure_project(three=three, python=python, validate=False)
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 594, in ensure_project
    ensure_pipfile(validate=validate)
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 298, in ensure_pipfile
    if project.pipfile_is_empty:
  File "venvs/pipenv/lib/python3.6/site-packages/pipenv/project.py", line 357, in pipfile_is_empty
    with open('Pipfile', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Pipfile'
```

**Comment by uranusjr** [comment]
```
$ pipenv --version
pipenv, version 8.0.1
```

**Comment by nateprewitt** [comment]
Thanks for opening this issue @uranusjr. This appears to be a bug in `pipfile_is_empty` that uses our `PIPENV_MAX_DEPTH` variable to check if a Pipfile exists, but then unconditionally assumes the Pipfile is in the current directory when it finds one. I've pushed f31a29f which will now open the same file it found while searching to perform the read.

This should be available in the next release.
