### ISSUE TITLE
pipenv lock failing

### ISSUE THREAD

**Issue by fenrrir** [kennethreitz/pipenv#710]
Hi! Pipenv is a awesome project! I'm  trying to migrate my django app to use pipenv and got a error with `pipenv lock`. 

My Pipfile is:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

coverage = "*"
"django-coverage-plugin" = "*"
"django-extensions" = "*"
werkzeug = "*"
"django-test-plus" = "*"
"django-debug-toolbar" = "*"
ipdb = "*"
ipython = "*"
"ipython-genutils" = "*"
"pytest-django" = "*"
"pytest-sugar" = "*"


[packages]

django = "*"
"django-redis" = "*"
redis = "*"
celery = "*"
amqp = "*"
"python-decouple" = "*"
gunicorn = "*"
whitenoise = "*"
"psycopg2" = "*"
"dj-database-url" = "*"


[requires]
python_version = "3.6.2"
```

Command output is 

```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1695, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1223, in do_init
    do_lock(system=system)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 994, in do_lock
    pre=pre
  File "/usr/local/lib/python2.7/site-packages/pipenv/utils.py", line 424, in resolve_deps
    resolved_tree.update(resolver.resolve())
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 442, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/55/5n_mpgqn1ds75f54_kyhyq4c0000gp/T/tmpy7F6xabuild/ipython/
```

**Comment by kennethreitz** [comment]
ipython is known to cause problems. it has a horrible setup.py.

**Comment by fenrrir** [comment]
Hi! I solved the problem, my pipenv was running with python==2.7.13 and the latest version of ipython does not support python 2.x. I just installed pipenv on python 3 and it's works.

**Comment by kennethreitz** [comment]
this issue should be resloved in the latest pipenv
