### ISSUE TITLE
pipenv ContextualVersionConflict

### ISSUE THREAD

**Issue by JostCrow** [kennethreitz/pipenv#724]
I tried to create a new pipenv project and I got this error.

```shell
$ pipenv             
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.15.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('urllib3<1.23,>=1.21.1'), set(['requests']))
```

**Comment by nateprewitt** [comment]
Hey @JostCrow, the exception is saying that your version of urllib3 is incompatible with the version of Requests you have installed. You'll need to upgrade urllib3 to the latest version, or at the very least to a version at 1.21.1 or later.

**Comment by kennethreitz** [comment]
I'll update our setup.py.
