### ISSUE TITLE
Conversion from requirements.txt to Pipfile fails

### ISSUE THREAD

**Issue by joaoqalves** [kennethreitz/pipenv#725]
Hi!

I have a `Pipfile` in the root of my project and then a folder (`subproj`) that contains a `requirements.txt` for a subproject. I'm doing the following:

```bash
$ cd myproj
$ pipenv shell
$ cd subproj
```

Then I'm trying to convert a `requirements.txt` into a `Pipfile` for this subproject, executing `pipenv install -r requirements.txt` and I get this error message:

```
Requirements file provided! Importing into Pipfile…
Traceback (most recent call last):
  File "/Users/joaoalves/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.0.6', 'console_scripts', 'pipenv')()
  File "/Users/joaoalves/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/joaoalves/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/joaoalves/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joaoalves/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/joaoalves/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/joaoalves/.local/lib/python2.7/site-packages/pipenv/cli.py", line 1680, in install
    import_requirements(r=requirements, dev=dev)
  File "/Users/joaoalves/.local/lib/python2.7/site-packages/pipenv/cli.py", line 232, in import_requirements
    assert os.path.isfile(r)
AssertionError
```

I'm not sure if this is a bug _per se_ or if there is some problem in my environment. I can use `virtualenv` and `virtualenvwrapper` without any problem. `Pipenv` works fine too with the `Pipfile` that's on the root project.

**Environment**:
- Mac OS Sierra 10.12.6
- ZSH + Oh My ZSH
- Pyenv with Python 2.7

Best regards,
João

**Comment by kennethreitz** [comment]
please provide the requirements.txt file.

**Comment by kennethreitz** [comment]
Closing until a requirements file is provided.

**Comment by joaoqalves** [comment]
Ups, my bad. The `requirements.txt` is the following:

```
requests==2.12.1
```

(I know that's a simple requirements file, but this is for a workshop)

**Comment by kennethreitz** [comment]
just do `pipenv install` from the root directory.

**Comment by kennethreitz** [comment]
i know what's causing this bug, i'll fix it.

**Comment by kennethreitz** [comment]
basically, this is currently from the root of the project, so,

`pipenv install -r subdir/requirements.txt`

**Comment by kennethreitz** [comment]
even if you're in the subdir. I'm fixing it.

**Comment by kennethreitz** [comment]
8.1.0 released, which fixes this!

**Comment by kennethreitz** [comment]
Sorry for the bug! Thanks for noticing it :)

**Comment by joaoqalves** [comment]
Thank you for being so responsive and fixing it so quickly! 🥇
