### ISSUE TITLE
Exception raised creating Pipfile.lock

### ISSUE THREAD

**Issue by lyndsysimon** [kennethreitz/pipenv#733]
In a new project directory, I attempted to install errbot. It installs successfully, but pipenv loses the ability to create a `Pipfile.lock` - here's the traceback:

```
 ~ > src > mkdir chatops
 ~ > src > cd chatops
 ~ > src > chatops > pipenv install --three errbot
Creating a virtualenv for this project…
Using /usr/local/bin/python3 to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/lyndsy.simon/.virtualenvs/chatops-HQdk3cG3/bin/python3.6
Also creating executable in /Users/lyndsy.simon/.virtualenvs/chatops-HQdk3cG3/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/lyndsy.simon/.virtualenvs/chatops-HQdk3cG3
Creating a Pipfile for this project…
Installing errbot…
Collecting errbot
Collecting rocket-errbot (from errbot)
Collecting colorlog (from errbot)
  Using cached colorlog-3.1.0-py2.py3-none-any.whl
Collecting markdown (from errbot)
Collecting requests (from errbot)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting ansi (from errbot)
Collecting yapsy>=1.11 (from errbot)
Collecting jinja2 (from errbot)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting Pygments>=2.0.2 (from errbot)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting webtest (from errbot)
  Using cached WebTest-2.0.28-py2.py3-none-any.whl
Collecting pygments-markdown-lexer>=0.1.0.dev39 (from errbot)
Collecting dnspython3 (from errbot)
Requirement already satisfied: setuptools in /Users/lyndsy.simon/.virtualenvs/chatops-HQdk3cG3/lib/python3.6/site-packages (from errbot)
Collecting daemonize (from errbot)
  Using cached daemonize-2.4.7-py2.py3-none-any.whl
Collecting bottle (from errbot)
Collecting pyOpenSSL (from errbot)
  Using cached pyOpenSSL-17.3.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->errbot)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->errbot)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->errbot)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->errbot)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->errbot)
Collecting six (from webtest->errbot)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting beautifulsoup4 (from webtest->errbot)
  Using cached beautifulsoup4-4.6.0-py3-none-any.whl
Collecting WebOb>=1.2 (from webtest->errbot)
  Using cached WebOb-1.7.3-py2.py3-none-any.whl
Collecting waitress>=0.8.5 (from webtest->errbot)
  Using cached waitress-1.0.2-py2.py3-none-any.whl
Collecting dnspython==1.15.0 (from dnspython3->errbot)
  Using cached dnspython-1.15.0-py2.py3-none-any.whl
Collecting cryptography>=1.9 (from pyOpenSSL->errbot)
  Using cached cryptography-2.0.3-cp36-cp36m-macosx_10_6_intel.whl
Collecting cffi>=1.7 (from cryptography>=1.9->pyOpenSSL->errbot)
  Using cached cffi-1.11.0-cp36-cp36m-macosx_10_6_intel.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->pyOpenSSL->errbot)
  Using cached asn1crypto-0.23.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7->cryptography>=1.9->pyOpenSSL->errbot)
Installing collected packages: rocket-errbot, colorlog, markdown, certifi, chardet, idna, urllib3, requests, ansi, yapsy, MarkupSafe, jinja2, Pygments, six, beautifulsoup4, WebOb, waitress, webtest, pygments-markdown-lexer, dnspython, dnspython3, daemonize, bottle, pycparser, cffi, asn1crypto, cryptography, pyOpenSSL, errbot
Successfully installed MarkupSafe-1.0 Pygments-2.2.0 WebOb-1.7.3 ansi-0.1.3 asn1crypto-0.23.0 beautifulsoup4-4.6.0 bottle-0.12.13 certifi-2017.7.27.1 cffi-1.11.0 chardet-3.0.4 colorlog-3.1.0 cryptography-2.0.3 daemonize-2.4.7 dnspython-1.15.0 dnspython3-1.15.0 errbot-5.1.2 idna-2.6 jinja2-2.9.6 markdown-2.6.9 pyOpenSSL-17.3.0 pycparser-2.18 pygments-markdown-lexer-0.1.0.dev39 requests-2.18.4 rocket-errbot-1.2.5 six-1.11.0 urllib3-1.22 waitress-1.0.2 webtest-2.0.28 yapsy-1.11.223

Adding errbot to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1800, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1069, in do_lock
    pre=pre
  File "/usr/local/lib/python2.7/site-packages/pipenv/utils.py", line 425, in resolve_deps
    resolved_tree.update(resolver.resolve())
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 442, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/lz/f1mbw51x1qz1j4d83nvlzvg8gxr6jg/T/tmpVxNMzzbuild/errbot/
```

**Comment by kennethreitz** [comment]
Make sure you're using latest. We recently improved compatibility with many modules.

**Comment by kennethreitz** [comment]
the gist is errbot has a crazy setup.py file that cannot be used against arbitrary versions of python.

**Comment by kennethreitz** [comment]
fixed locally. releasing.

**Comment by lyndsysimon** [comment]
I'm using pipenv 8.1.0.

> the gist is errbot has a crazy setup.py file that cannot be used against arbitrary versions of python.

I'll take a stab at fixing that and submitting a PR. Is it just that the setup.py is blowing up in Python 3.6.2?

**Comment by lyndsysimon** [comment]
Oh, LOL. Nevermind then :)

**Comment by kennethreitz** [comment]
We have a patched pip that uses your virtualenv's python instead of it's own. It wasn't operating properly though.

**Comment by kennethreitz** [comment]
v 8.1.3 is out, which fixes this.

**Comment by kennethreitz** [comment]
💫✨🍰✨💫

**Comment by kennethreitz** [comment]
who amazings? we're amazings.

**Comment by kennethreitz** [comment]
it's like butter now

**Comment by kennethreitz** [comment]
:butter:

**Comment by lyndsysimon** [comment]
Upgraded, and I confirm the fix works. You have earned the usage of the "royal we".

**Comment by spott** [comment]
I'm getting the same error, I'm on 8.2.7, and I'm getting it with Matplotlib.

Should I create a new issue?

**Comment by nateprewitt** [comment]
@spott can you run `pipenv lock --clear` and try installing again. If it's still failing, please open a new issue. Thanks!

**Comment by spott** [comment]
@nateprewitt:  That fixed it, thanks.  How did that break?

**Comment by nateprewitt** [comment]
You had cached packages that were causing issues and the new fix wasn't able to function as intended.
