### ISSUE TITLE
Unistall subcommand missing lock argument

### ISSUE THREAD

**Issue by khardix** [kennethreitz/pipenv#74]
The `uninstall` subcommand is declared to have a `--lock` flag, but the actual function signature does not accept such keyword argument. Therefore, a `TypeError` occurs:

```
$ pipenv uinstall
Traceback (most recent call last):
  File "/home/jstanek/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jstanek/.local/venvs/pipenv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: uninstall() got an unexpected keyword argument 'lock'
```

**Comment by kennethreitz** [comment]
thanks!

**Comment by kennethreitz** [comment]
fixed :)
