### ISSUE TITLE
pipenv fails with pgadmin4 release candidate 2

### ISSUE THREAD

**Issue by rnetocombr** [kennethreitz/pipenv#743]
Steps to reproduce:

1.  Download and uncompress (https://www.postgresql.org/ftp/pgadmin/pgadmin4/v2.0-rc2/source/) in a folder;

2. Access folder and create the env:

```bash
rnetocombr@T440s:~/Workspace$ cd pgadmin4-2.0-rc2/
rnetocombr@T440s:~/Workspace/pgadmin4-2.0-rc2$ ls
ci  docs  libraries.txt  LICENSE  Make.bat  Makefile  Make-MinGW.bat  pkg  README  requirements.txt  runtime  web
rnetocombr@T440s:~/Workspace/pgadmin4-2.0-rc2$ pipenv --three
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋Already using interpreter /usr/bin/python3
Using base prefix '/usr'                                                                                                                       
New python executable in /home/rnetocombr/.local/share/virtualenvs/pgadmin4-2.0-rc2-_RI5YMQk/bin/python3                                       
Also creating executable in /home/rnetocombr/.local/share/virtualenvs/pgadmin4-2.0-rc2-_RI5YMQk/bin/python                                     
Installing setuptools, pip, wheel...done.                                                                                                      

Virtualenv location: /home/rnetocombr/.local/share/virtualenvs/pgadmin4-2.0-rc2-_RI5YMQk
Requirements.txt found, instead of Pipfile! Converting…
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did. 
We recommend updating your Pipfile to specify the "*" version, instead.
```

3. Load the env:

```bash
rnetocombr@T440s:~/Workspace/pgadmin4-2.0-rc2$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
source /home/rnetocombr/.local/share/virtualenvs/pgadmin4-2.0-rc2-_RI5YMQk/bin/activate
rnetocombr@T440s:~/Workspace/pgadmin4-2.0-rc2$ source /home/rnetocombr/.local/share/virtualenvs/pgadmin4-2.0-rc2-_RI5YMQk/bin/activate
```

4. Try to install:

```bash
(pgadmin4-2.0-rc2-_RI5YMQk) rnetocombr@T440s:~/Workspace/pgadmin4-2.0-rc2$ pipenv install
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.1.4', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1738, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1250, in do_init
    do_lock(system=system)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1069, in do_lock
    pre=pre
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 425, in resolve_deps
    resolved_tree.update(resolver.resolve())
  File "/usr/local/lib/python3.5/dist-packages/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.5/dist-packages/piptools/resolver.py", line 198, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.5/dist-packages/piptools/resolver.py", line 284, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.5/dist-packages/piptools/repositories/pypi.py", line 170, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/pip/req/req_install.py", line 447, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp360vrydnbuild/importlib/
(pgadmin4-2.0-rc2-_RI5YMQk) rnetocombr@T440s:~/Workspace/pgadmin4-2.0-rc2$ 
```

Additional info:

* pure virtualenv + pip works fine;
* platform:

ubuntu 16.04;
python 3.5.2;

* [requirements.txt](https://github.com/kennethreitz/pipenv/files/1339316/requirements.txt)

**Comment by kennethreitz** [comment]
can't support everything. looks like they have a crazy setup.py file.

**Comment by kennethreitz** [comment]
you can work around this with `pipenv install --skip-lock`

**Comment by kennethreitz** [comment]
make sure you have the latest version installed

**Comment by AlJohri** [comment]
I think `importlib==1.0.3; python_version <= '2.7'` should be using a `<` not `<=`. 

Either way, it fails on https://github.com/brettcannon/importlib/blob/master/setup.py because they use the old `distutils` style setup.py.

```
$ python setup.py egg_info
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'egg_info'
```
