### ISSUE TITLE
pipenv --three not working within anaconda 3.6 environment 

### ISSUE THREAD

**Issue by transmatter** [kennethreitz/pipenv#751]
When I run pipenv --three, following message occurs:

`(py36)  mamoon@mamoon-desktop  ~  pipenv --three
Creating a virtualenv for this project…
Using /home/mamoon/anaconda2/envs/py36/bin/python3 to create virtualenv…
⠋Running virtualenv with interpreter /home/mamoon/anaconda2/envs/py36/bin/python3
Using base prefix '/home/mamoon/anaconda2/envs/py36'
New python executable in /home/mamoon/.local/share/virtualenvs/mamoon-02zYzu3a/bin/python3
Also creating executable in /home/mamoon/.local/share/virtualenvs/mamoon-02zYzu3a/bin/python
/home/mamoon/.local/share/virtualenvs/mamoon-02zYzu3a/bin/python3: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable /home/mamoon/.local/share/virtualenvs/mamoon-02zYzu3a/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/home/mamoon/.local/share/virtualenvs' (should be '/home/mamoon/.local/share/virtualenvs/mamoon-02zYzu3a')
ERROR: virtualenv is not compatible with this system or executable

Virtualenv location: 
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/home/mamoon/anaconda2/envs/py36/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/cli.py", line 1642, in cli
    ensure_project(three=three, python=python, warn=True, site_packages=site_packages)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/cli.py", line 613, in ensure_project
    ensure_pipfile(validate=validate)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/cli.py", line 329, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/home/mamoon/anaconda2/envs/py36/lib/python3.6/site-packages/pipenv/project.py", line 387, in create_pipfile
    data[u'requires'] = {'python_version': python_version(python)[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable`

Following is some version information:
`(py36)  mamoon@mamoon-desktop  ~  conda --version
conda 4.3.21
(py36)  mamoon@mamoon-desktop  ~  anaconda --version
anaconda Command line client (version 1.6.3)
(py36)  mamoon@mamoon-desktop  ~  python --version
Python 3.6.2 :: Continuum Analytics, Inc.
(py36)  mamoon@mamoon-desktop  ~  `

Also, I am using anaconda environment for python 3.6. I was facing the same problem with virtualenv environment creation.

pipenv --two is working fine however:
`(py36)  ✘ mamoon@mamoon-desktop  ~  pipenv --two
Creating a virtualenv for this project…
Using /home/mamoon/anaconda2/bin/python2 to create virtualenv…
⠋Running virtualenv with interpreter /home/mamoon/anaconda2/bin/python2
New python executable in /home/mamoon/.local/share/virtualenvs/mamoon-02zYzu3a/bin/python2
Also creating executable in /home/mamoon/.local/share/virtualenvs/mamoon-02zYzu3a/bin/python
Installing setuptools, pip, wheel...done.`

**Comment by kennethreitz** [comment]
use the system's anaconda's interpreter, not one created within a virtualenv.

**Comment by muzic194** [comment]
@kennethreitz What do you mean? I've installed anaconda, then activate it with `source ~/anaconda3/bin/activate`, then install pipenv with `pip install pipenv` and then try to initialize project with `pipenv --three`. Is it not possible to create python 3 project from within anaconda3 when using pipenv?
