### ISSUE TITLE
Error when installing dependencies to using --system flag

### ISSUE THREAD

**Issue by Gronis** [kennethreitz/pipenv#770]
```
pipenv install --system                                                                                                                                                                                         <452477c ✗>
Installing dependencies from Pipfile.lock…
Traceback (most recent call last):▉▉▉▉ 0/6 — 00:00:00
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1740, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1255, in do_init
    skip_lock=skip_lock, verbose=verbose, concurrent=concurrent)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 805, in do_install_dependencies
    index=index
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1320, in pip_install
    quoted_pip = shellquote(quoted_pip)
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 310, in shellquote
    return '"' + s.replace("'", "'\\''") + '"'
AttributeError: 'NoneType' object has no attribute 'replace'
```
Using pipenv 8.2.0, running on python 3.6, OSX 10.12.6

**Comment by Gronis** [comment]
Installing dependencies to a virtual environment with `pipenv install` works

**Comment by kennethreitz** [comment]
thanks

**Comment by kennethreitz** [comment]
cannot reproduce. is `pip` not in your path?

**Comment by kennethreitz** [comment]
also added support for 'pip2' and 'pip3', which i assume is the issue here.

**Comment by kennethreitz** [comment]
v8.2.2 released, which should fix this.

**Comment by Gronis** [comment]
pip is not in my path, only pip2 and pip3. I have tried the new version and it now works successfully :)

**Comment by kennethreitz** [comment]
excellent news!
