### ISSUE TITLE
Installing zip archives

### ISSUE THREAD

**Issue by helderco** [kennethreitz/pipenv#772]
How do you install zip archives?

```
$ pipenv install https://github.com/divio/django-cms/archive/release/3.4.x.zip
Creating a Pipfile for this project…
Installing https://github.com/divio/django-cms/archive/release/3.4.x.zip…
Collecting https://github.com/divio/django-cms/archive/release/3.4.x.zip
  Downloading https://github.com/divio/django-cms/archive/release/3.4.x.zip (6.0MB)
  Requirement already satisfied (use --upgrade to upgrade): django-cms==3.4.5rc2 from https://github.com/divio/django-cms/archive/release/3.4.x.zip in /Users/helder/.local/share/virtualenvs/pip-XBl5Wj6A/lib/python3.6/site-packages
Requirement already satisfied: Django<2.0,>=1.8 in /Users/helder/.local/share/virtualenvs/pip-XBl5Wj6A/lib/python3.6/site-packages (from django-cms==3.4.5rc2)
Requirement already satisfied: django-classy-tags>=0.7.2 in /Users/helder/.local/share/virtualenvs/pip-XBl5Wj6A/lib/python3.6/site-packages (from django-cms==3.4.5rc2)
Requirement already satisfied: django-formtools>=1.0 in /Users/helder/.local/share/virtualenvs/pip-XBl5Wj6A/lib/python3.6/site-packages (from django-cms==3.4.5rc2)
Requirement already satisfied: django-treebeard>=4.0.1 in /Users/helder/.local/share/virtualenvs/pip-XBl5Wj6A/lib/python3.6/site-packages (from django-cms==3.4.5rc2)
Requirement already satisfied: django-sekizai>=0.7 in /Users/helder/.local/share/virtualenvs/pip-XBl5Wj6A/lib/python3.6/site-packages (from django-cms==3.4.5rc2)
Requirement already satisfied: djangocms-admin-style>=1.0 in /Users/helder/.local/share/virtualenvs/pip-XBl5Wj6A/lib/python3.6/site-packages (from django-cms==3.4.5rc2)
Requirement already satisfied: pytz in /Users/helder/.local/share/virtualenvs/pip-XBl5Wj6A/lib/python3.6/site-packages (from Django<2.0,>=1.8->django-cms==3.4.5rc2)

Adding https://github.com/divio/django-cms/archive/release/3.4.x.zip to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/Users/helder/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.0', 'console_scripts', 'pipenv')()
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/cli.py", line 1808, in install
    do_lock(system=system, pre=pre)
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/cli.py", line 1071, in do_lock
    pre=pre
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/utils.py", line 418, in resolve_deps
    resolved_tree.update(resolver.resolve())
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 88, in resolve
    self.their_constraints))
  File "/Users/helder/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 125, in check_constraints
    raise UnsupportedConstraint(msg, constraint)
piptools.exceptions.UnsupportedConstraint: pip-compile does not support URLs as packages, unless they are editable. Perhaps add -e option? (constraint was: https://github.com/divio/django-cms/archive/release/3.4.x.zip (from -r /var/folders/2v/nmb819xx3wsb7hcqvd68230w0000gn/T/pipenv-FHm_hi-requirement.txt (line 1)))
```

Produces this Pipfile:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
"e682b37" = {path = "https://github.com/divio/django-cms/archive/release/3.4.x.zip"}
```

Editable?
```
$ pipenv install -e https://github.com/divio/django-cms/archive/release/3.4.x.zip
Creating a Pipfile for this project…
Installing -e https://github.com/divio/django-cms/archive/release/3.4.x.zip…
⠦
Error:  An error occurred while installing -e https://github.com/divio/django-cms/archive/release/3.4.x.zip!
https://github.com/divio/django-cms/archive/release/3.4.x.zip should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```

**Comment by kennethreitz** [comment]
this should work. may be a regression. will try to look into it today.

**Comment by kennethreitz** [comment]
landed a fix in master

**Comment by kennethreitz** [comment]
8.2.1 released, which includes this fix. You'll need to re-do the 'install' step. 

We also need to write a test for this.

**Comment by kennethreitz** [comment]
note that we will not resolve dependencies for zipballs

**Comment by helderco** [comment]
Not even with editable git?

**Comment by helderco** [comment]
So none of these resolve dependencies:
```
"e682b37" = {file = "https://github.com/divio/django-cms/archive/release/3.4.x.zip"}
django-cms = {git = "https://github.com/divio/django-cms.git", ref = "release/3.4.x", editable = true}
django-cms = {path = "django-cms", editable = true}
```

My problem is that I want Django 1.11 with Django CMS 3.4, but the latest CMS version is 3.4.4 which requires django<1.11. They have added support in the *release/3.4.x*  branch, but it's not released to pypi yet.

So, with pipenv, how can I resolve this?

**Comment by kennethreitz** [comment]
we only resolve dependencies for editables, and zipballs cannot be editable

**Comment by kennethreitz** [comment]
`django-cms = {git = "https://github.com/divio/django-cms.git", ref = "release/3.4.x", editable = true}` should be fine

**Comment by helderco** [comment]
Ok, I had yet another dependency forcing <1.11.

Thanks!
