### ISSUE TITLE
EOF error when authenticating?

### ISSUE THREAD

**Issue by chepner** [kennethreitz/pipenv#776]
I am trying to install a package from a private repository, but I appear to be getting an EOFError when trying to authenticate.

`pip` alone works:

```
pip install --extra-index-url 'https://<user>:<password>@<host>/artifactory/api/pypi/pypi-all/simple' <my_package>
```

First I set things up

```
% mkdir pipenv-test
% cd pipenv-test
% pipenv lock  # Just to generate an initial Pipfile
```

I add the following to the Pipfile

```
[[source]]
verify_ssl = true
name = "work repo"
url = "https://<user>:<password>@<host>/artifactory/api/pypi/pypi-all/simple"
```

then run 

```
% pipenv lock  # should this be necessary?
% pipenv install <my_package>
```

On attempting to install a program, it looks like something is ignoring the user id in the source URL, and trying to read from empty/closed standard input when prompted for the user id.

```
% pipenv install <my_package>
Installing <my_package>…
Collecting <my_package>
User for <host>:
Error:  An error occurred while installing <my_package>!
Exception:
Traceback (most recent call last):
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 602, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/_vendor/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/Users/clint/.local/share/virtualenvs/pipenv-test-pou_DiX5/lib/python3.6/site-packages/pip/download.py", line 181, in handle_401
    username = six.moves.input("User for %s: " % parsed.netloc)
EOFError: EOF when reading a line
```

Omitting the credentials from the url (https://<host>/artifactory/api/pypi/pypi-all/simple) results in a simpler error:

```
% pipenv install <my_package>
Installing <my_package>…
Collecting <my_package>

Error:  An error occurred while installing <my_package>!
  Could not find a version that satisfies the requirement <my_package> (from versions: )
No matching distribution found for <my_package>
```

It appears no attempt is made to connect to the private repo, and `<my_package>` is of course not on PyPi.

**Comment by kennethreitz** [comment]
does it work with pip?

**Comment by chepner** [comment]
Yes, forgot to include the output of that command:

```
% pip install --extra-index-url 'https://<user>:<password>@<host>/artifactory/api/pypi/pypi-all/simple' <my_package>
Collecting <my_package>
Collecting <some_prereq>==3.0.2 (from <my_package>)
Collecting requests==2.9.1 (from <my_package>)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Installing collected packages: <some_prereq>, requests, <my_package>
Successfully installed <my_package>-0.2.1 <some_prereq>-3.0.2 requests-2.9.1
```

**Comment by techalchemy** [comment]
To answer one of your questions, no, `pipenv lock` is not necessary.  You can just run `pipenv install` and it will generate the pipfile for you.  At a glance it appears that it is not parsing the user/password from your supplied url

If you use a `pip.conf` file with your credentials and omit them from the URL on install, does it work? Not saying this is a permanent solution, just wondering.  The file would be `$HOME/Library/Application Support/pip/pip.conf` if you're on MacOS or `~/.config/pip/pip.conf` on *nix

```ini
[global]
extra-index-url = https://<use>r:<pass>@<host>/artifactory/api/pypi/pypi-all/simple
trusted-host = <host>
```

**Comment by techalchemy** [comment]
Also upon re-reading your issue I think I can make another recommendation. Try creating a pipfile that looks like this:

```ini
[[source]]
url = "https://<user>:<password>@<host>/artifactory/api/pypi/pypi-all/simple"
verify_ssl = true
name = "work"

[packages]
my_package = {version="*", index="work"}
```

After creating this Pipfile, don't run any commands besides `pipenv install`.  I'd be curious to know whether this or the above suggestion are successful.

**Comment by kennethreitz** [comment]
I am curious as well.

**Comment by erinxocon** [comment]
I've set up a provate pypi instance for testing today

**Comment by chepner** [comment]
OK, I'll lead with the good news: adding `my_package = {version="*", index="work"}` to the package section works, as long as the credentials are in the URL.

Regarding the removal of credentials, I get two different failures. Without the `my_package` line, I get the same error I would get as if I only had a `[[source]]` entry for pypi.python.org (as if it were ignoring my private repo entirely). With the my_package line, I get a different, non-traceback, error, though one that doesn't really suggest that the lack of credentials is the issue.

```
% pipenv install
Pipfile.lock out of date, updating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches <my_package>
Tried: (no version found at all)
```

**Comment by techalchemy** [comment]
What if you make your pipfile look like this:

```ini
[[source]]
url = "https://<user>:<password>@<host>/artifactory/api/pypi/pypi-all/simple"
verify_ssl = true
name = "work"
```

And you try the command as `pipenv install --index=work my_package`

**Comment by erinxocon** [comment]
I've been playing around with my private pypi repo and adding another source to my pipfile...everything seems to work as I would expect.  Here is my pipfile:

```ini
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.erincodes.com/simple"
verify_ssl = true
name = "internal"

[packages]
fakepythonpackage = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

Doing a `pipenv install` works as I would expect and it resolves to the internal source correctly.  The following also works when doing `pipenv install`.

```ini
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.erincodes.com/simple"
verify_ssl = true
name = "internal"

[packages]
fakepythonpackage = {version="*", index="internal"}

[dev-packages]

[requires]
python_version = "3.6"
```

When the pipfile is empty with just the source added, `pipenv install fakepythonpackage` works as expected.  I also tried it using another test with basic auth credentials and it worked so long as I had the credentials as a part of the url.

**Comment by techalchemy** [comment]
@erinxocon do both pipfiles work when you add auth and drop in the user/pass in the URL?  or does that only work in the one with the index specified in the extended toml format?

**Comment by erinxocon** [comment]
Nope, all of the above works when I drop in the credentials!  My URL looked like the following

`https://user:pass@pypi.erincodes.com/simple`
