### ISSUE TITLE
pipenv shell only works with --fancy flag

### ISSUE THREAD

**Issue by minskmaz** [kennethreitz/pipenv#778]
Warning the script below creates 2 files (requirements.txt & pybase.dockerfile)

Without fancy flag I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 2057, in shell
    do_shell(three=three, python=python, fancy=fancy, shell_args=shell_args)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1952, in do_shell
    shell = os.path.abspath(PIPENV_SHELL)
  File "/usr/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Also when I run fab I get "ImportError: No module named enum", but no errors thrown during pipenv install -r requirements.txt

```
--- script ---

cat <<EOF > 'requirements.txt'
Fabric
fabric-verbose
EOF


cat <<EOF > 'pybase.dockerfile'
FROM ubuntu:zesty
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing
RUN apt-get install -y python2.7-dev
RUN apt-get install -y python-twisted
RUN apt-get install -y python-pip
RUN pip install pipenv
WORKDIR "/theta"
EOF

docker build -f pybase.dockerfile . -t pybase:latest
docker run -it --rm \
	-v `pwd`:/theta \
	-v `pwd`/virtualenvs:/root/.local/share/virtualenvs/ \
	-w /theta/ \
	pybase:latest \
	/bin/bash -c "pipenv install --system -r requirements.txt && pipenv shell --fancy"
```

**Comment by kennethreitz** [comment]
pipenv shell is not designed to work with --system

**Comment by kennethreitz** [comment]
you must have the SHELL environment variable set, however.

**Comment by minskmaz** [comment]
@kennethreitz apologies for the late response. Thank you for yours. I see the mistake I made. I had read a thread somewhere recommending --system flag in docker builds.

**Comment by kennethreitz** [comment]
--system is great for docker builds, but then shell is no longer necessary

**Comment by kennethreitz** [comment]
We actually have an example dockerfile available now:

- https://github.com/kennethreitz/pipenv/blob/master/Dockerfile
- https://hub.docker.com/r/kennethreitz/pipenv/

**Comment by minskmaz** [comment]
I sometimes copy a virtualenv artifact into multiple flavors of my images so unless you think this is counter indicated with pipenv I'll pass on the --system flag

**Comment by minskmaz** [comment]
Everything works as expected. Thanks. See you at a meetup soon!
