### ISSUE TITLE
Pipenv 8.2.0 fails to update with KeyError: PIP_PYTHON_PATH

### ISSUE THREAD

**Issue by tdi** [kennethreitz/pipenv#782]
Pipenv fails to update itself with pipenv --update. Updating does work with pip. 
```
➜  ~ pipenv --update
Courtesy Notice: Pipenv 8.2.4 is now available. Automatically upgrading!
Collecting pipenv
  Downloading pipenv-8.2.4.tar.gz (3.7MB)
    100% |████████████████████████████████| 3.7MB 2.1MB/s
Exception:
Traceback (most recent call last):
  File "/Users/tdi/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pipenv/patched/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/tdi/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pipenv/patched/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Users/tdi/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/tdi/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Users/tdi/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Users/tdi/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 421, in run_egg_info
    base_cmd = [os.environ['PIP_PYTHON_PATH'], '-c', script]
  File "/Users/tdi/.pyenv/versions/2.7.13/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'PIP_PYTHON_PATH'
Pipenv updated to 8.2.4!
➜  ~ pipenv --version
pipenv, version 8.2.0
```

**Comment by kennethreitz** [comment]
thanks

**Comment by kennethreitz** [comment]
fixed

**Comment by dimitris-k** [comment]
The same when upgrading **from 11.8.0 to 11.8.3**:

```
Courtesy Notice: Pipenv 11.8.3 is now available. Automatically upgrading!
Traceback (most recent call last):
  File "/home/dk/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.8.0', 'console_scripts', 'pipenv')()
  File "/home/dk/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/dk/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/dk/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/dk/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dk/.local/lib/python3.5/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/dk/.local/lib/python3.5/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dk/.local/lib/python3.5/site-packages/pipenv/cli.py", line 147, in cli
    core.ensure_latest_self()
  File "/home/dk/.local/lib/python3.5/site-packages/pipenv/core.py", line 193, in ensure_latest_self
    sys.modules['pip'].main(args)
```

```
$ pipenv --version
pipenv, version 11.8.0
```

**Comment by kennethreitz** [comment]
this has been removed in master
