### ISSUE TITLE
Exception raised when try to reproduce video

### ISSUE THREAD

**Issue by cassiobotaro** [kennethreitz/pipenv#789]
![image](https://user-images.githubusercontent.com/3127847/31051588-686a4f34-a642-11e7-8555-ebae8e4cbf92.png)

I was trying to reproduce [this video](https://vimeo.com/233134524) but when i type `pipenv install maya`, many errors occurs:
<details>
<summary>Traceback</summary>

```python

Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 295, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 297, in ssl_wrap_socket
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.5', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 1849, in install
    do_lock(system=system, pre=pre)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 1080, in do_lock
    pre=pre
  File "/usr/lib/python3.6/site-packages/pipenv/utils.py", line 421, in resolve_deps
    resolved_tree.update(resolver.resolve())
  File "/usr/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 199, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 293, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 625, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [Errno 2] No such file or directory

```
</details>

But seems that maya was installed:

![image](https://user-images.githubusercontent.com/3127847/31051578-1ce6e982-a642-11e7-8572-c3a1b08371ee.png)

**Comment by nateprewitt** [comment]
This is quite peculiar. Could you please provide the contents of `pip freeze` for the Python version you installed pipenv with?

This is related to requests/requests#2863 but the patch for this won't land until 3.0.0 is released. I don't however understand why you're hitting this. Do you have any unique TLS or trust store changes on your machine?

**Comment by kennethreitz** [comment]
looks like you're using a system-provided requests, and not one installed from pypi. try the fancy installation method

https://docs.pipenv.org/install.html#fancy-installation-of-pipenv
