### ISSUE TITLE
Pipenv installation fails

### ISSUE THREAD

**Issue by samotarnik** [kennethreitz/pipenv#794]
When trying to install `pipenv` via `pip3`, I get the following error:
```
$ pip3 install pipenv --user
Collecting pipenv
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f17e9591978>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pipenv/
  Using cached pipenv-8.2.5.tar.gz
Requirement already satisfied: virtualenv in /home/samo/.local/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: pew>=0.1.26 in /home/samo/.local/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: pip>=9.0.1 in /usr/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: requests>2.18.0 in /home/samo/.local/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: flake8 in /home/samo/.local/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: urllib3>=1.21.1 in /home/samo/.local/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /home/samo/.local/lib/python3.6/site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: setuptools>=17.1 in /usr/lib/python3.6/site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: pythonz-bd>=1.10.2 in /home/samo/.local/lib/python3.6/site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/samo/.local/lib/python3.6/site-packages (from requests>2.18.0->pipenv)
Requirement already satisfied: certifi>=2017.4.17 in /home/samo/.local/lib/python3.6/site-packages (from requests>2.18.0->pipenv)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python3.6/site-packages (from requests>2.18.0->pipenv)
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0 in /home/samo/.local/lib/python3.6/site-packages (from flake8->pipenv)
Requirement already satisfied: pyflakes<1.6.0,>=1.5.0 in /home/samo/.local/lib/python3.6/site-packages (from flake8->pipenv)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/samo/.local/lib/python3.6/site-packages (from flake8->pipenv)
Requirement already satisfied: resumable-urlretrieve; python_version == "3.6" in /home/samo/.local/lib/python3.6/site-packages (from pythonz-bd>=1.10.2->pew>=0.1.26->pipenv)
Installing collected packages: pipenv
  Running setup.py install for pipenv ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5ckgjstw/pipenv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-szrykmls-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:

...

    byte-compiling /home/samo/.local/lib/python3.6/site-packages/pipenv/utils.py to utils.cpython-36.pyc
    running install_egg_info
    Copying pipenv.egg-info to /home/samo/.local/lib/python3.6/site-packages/pipenv-8.2.5-py3.6.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5ckgjstw/pipenv/setup.py", line 103, in <module>
        'upload': UploadCommand,
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 557, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install_scripts.py", line 33, in run
        bs_cmd = (self.get_finalized_command('build_scripts', create=False) or
      File "/usr/lib64/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
    AttributeError: 'NoneType' object has no attribute 'ensure_finalized'
```

[Here](https://gist.github.com/samotarnik/19fe34d92a653f3676f9f5e7a0c63228) is a longer trace.

And my system info:
```
$ uname -a                                                                                                                                                                     
Linux wintermute 4.12.5-300.fc26.x86_64 #1 SMP Mon Aug 7 15:27:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ pip3 --version                                                                                                                                                                      
pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)
```

**Comment by kennethreitz** [comment]
I'm not sure why this is happening. Try it again.

**Comment by kennethreitz** [comment]
make sure you have the latest setuptools

**Comment by samotarnik** [comment]
thanks, upgrading `setuptools` solved it.
