### ISSUE TITLE
It is not halloween yet, but pipenv is broken.

### ISSUE THREAD

**Issue by fogfish** [kennethreitz/pipenv#809]
It suppose to be funny but ... 

```
Traceback (most recent call last):
  File "/usr/local/macports/Library/Frameworks/Python.framework/Versions/3.6/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/usr/local/macports/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/__init__.py", line 13, in <module>
    from .cli import cli
  File "/usr/local/macports/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/cli.py", line 77, in <module>
    if ((now.tm_mon == 10) and (now.tm_day == 30)) or ((now.tm_mon == 10) and (now.tm_day == 31)):
AttributeError: 'time.struct_time' object has no attribute 'tm_day'
```

**Comment by uranusjr** [comment]
Duplicate to #783 and #804. Please upgrade.

**Comment by nateprewitt** [comment]
In the future, please check the issues list before opening new ones. This is the 5th duplicate in the last 24 hours.

**Comment by fogfish** [comment]
@nateprewitt 
It is not good if eastern eggs impacts builds, ci/cd and etc... You would have a shorter list of issues... Thanks you that you've managed to fix fast and impact was minimal (at least for us).
