### ISSUE TITLE
Pipenv crashes with "This is likely a bug"

### ISSUE THREAD

**Issue by mapio** [kennethreitz/pipenv#816]
By executing ´pipenv install` in a dir containing just a `requirements.txt` file as follows

```
jupyter
librosa
seaborn
numpy
scipy
matplotlib
```

results in the following error message

```
$ pipenv install
Creating a virtualenv for this project…
⠋New python executable in /Users/santini/.local/share/virtualenvs/pb-YNhSI1_n/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/santini/.local/share/virtualenvs/pb-YNhSI1_n
Requirements.txt found, instead of Pipfile! Converting…
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did. 
We recommend updating your Pipfile to specify the "*" version, instead.
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/cli.py", line 1785, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/cli.py", line 1293, in do_init
    do_lock(system=system)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/cli.py", line 1083, in do_lock
    pre=pre
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/utils.py", line 421, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 97, in resolve
    'This is likely a bug.' % max_rounds)
RuntimeError: No stable configuration of concrete packages could be found for the given constraints after 16 rounds of resolving.
This is likely a bug.
```

**Comment by techalchemy** [comment]
What does the Pipfile look like?

**Comment by mapio** [comment]
There is no `Pipfile` initially… Just make an empty dir and add the above mentioned `requirements.txt` file.

**Comment by techalchemy** [comment]
This is actually installing fine for me, can you show us the output of `pipenv --version` as well as `cat Pipfile` after pipenv creates one from your requirements.txt?

```console
/t/new  cat requirements.txt
jupyter
librosa
seaborn
numpy
scipy
matplotlib

 /t/new  pipenv --rm
Removing virtualenv (/home/hawk/.local/share/virtualenvs/new-X2WGxJLe)…

 /t/new  pipenv install
Creating a virtualenv for this project…
⠋Using base prefix '/home/hawk/.pyenv/versions/3.6.2'
New python executable in /home/hawk/.local/share/virtualenvs/new-X2WGxJLe/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/hawk/.local/share/virtualenvs/new-X2WGxJLe
Installing dependencies from Pipfile.lock (c01a22)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 54/54 — 00:00:31
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

Here is the pipfile it generated for me:

```ini                                                                                                                                                       
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

jupyter = "*"
librosa = "*"
seaborn = "*"
numpy = "*"
scipy = "*"
matplotlib = "*"


[dev-packages]
```

**Comment by mapio** [comment]
So… I'm unable to reproduce now. I had so many error last night that I decided to do a clean install of Python 2 and 3 and of all the site package. I suspect that the error was due to not having a full Python 3 installation of `setuptools`.

I'm now quite busy, I'll try to reproduce the error as soon as possible.

Thank you for your attention and support in the meanwhile.
