### ISSUE TITLE
Problem installing any package

### ISSUE THREAD

**Issue by ZhukovGreen** [kennethreitz/pipenv#862]
There is some issue when pipenv trying to lock dependencies. I can't troubleshoot it by myself. Here is my log:
```
$ pipenv install sklearn                                                             on git:master|…
Installing sklearn…
Collecting sklearn
Collecting scikit-learn (from sklearn)
  Using cached scikit_learn-0.19.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: scikit-learn, sklearn
Successfully installed scikit-learn-0.19.0 sklearn-0.0

Adding sklearn to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.7', 'console_scripts', 'pipenv')()
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/cli.py", line 1851, in install
    do_lock(system=system, pre=pre)
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/cli.py", line 1082, in do_lock
    pre=pre
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/utils.py", line 452, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp858iy8rtbuild/subprocess32/
```

**Comment by ZhukovGreen** [comment]
If I create a new package and doing `pipenv check`, then I have the following issue:
```
$ pipenv check                                                                       on git:master|…
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/safety.zip/__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/safety.zip/safety/cli.py", line 3, in <module>
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3031, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 651, in _build_master
    ws = cls()
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1822, in _has
    zip_path = self._zipinfo_name(fspath)
  File "/home/zhukovgreen/.local/share/virtualenvs/udacity-fB21oxVF/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1688, in _zipinfo_name
    "%s is not a subpath of %s" % (fspath, self.zip_pre)
AssertionError: /home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/EGG-INFO/PKG-INFO is not a subpath of /home/zhukovgreen/.local/lib/python3.6/site-packages/pipenv-8.2.7-py3.6.egg/pipenv/patched/safety.zip/
```

**Comment by ZhukovGreen** [comment]
Btw. I did the same on docker, and here is still the issue:
```
$ cat Dockerfile                                             on git:architecture-changes|✚1…
FROM python

WORKDIR /machine-learning
COPY . .

RUN pip install pipenv
RUN pipenv install --dev
RUN pipenv install requests
```

**Comment by vphilippon** [comment]
That's a bug fixed in 8.2.7 (officially released). Make sure to clear your cache after upgrading (`pipenv lock --clear`)
Was not respecting the platform when selecting wheels to compute dependencies, ending up, as an example, fetching `subprocess32`, which is a Py2 dependency, even on Py3, among other things.

**Comment by ZhukovGreen** [comment]
Thanks, @vphilippon. Yes, it works now

**Comment by erinxocon** [comment]
Thanks for using pipenv @ZhukovGreen!  and Thanks for the support @vphilippon!
