### ISSUE TITLE
IndexError on running pipenv install

### ISSUE THREAD

**Issue by mccartykim** [kennethreitz/pipenv#882]
With a fresh install on Windows 10, I get the following failure and traceback. This is with Python 3.6 installed for all users, with Pipenv installed from `pip install --user pipenv`. I'm curious if this perhaps has something to do with the ["find_windows_executable" function](https://github.com/kennethreitz/pipenv/blob/8685ba80d75c6489bbb4dce19861c9e91c2636ed/pipenv/utils.py#L857).

```
PS C:\Users\mccar\Documents\Software Development\bittorrent> pipenv install
Creating a virtualenv for this project…

Virtualenv location:
Creating a virtualenv for this project…

Virtualenv location:
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\cli.py", line 1785, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy)
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\cli.py", line 1293, in do_init
    do_lock(system=system)
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\cli.py", line 1022, in do_lock
    python=python_version(which('python', allow_global=system)),
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\cli.py", line 1404, in which
    p = find_windows_executable(os.path.join(location, 'Scripts'), command)
  File "C:\Users\mccar\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 820, in find_windows_executable
    return exec_files[0]
IndexError: list index out of range
PS C:\Users\mccar\Documents\Software Development\bittorrent>
```

**Comment by techalchemy** [comment]
Thanks for the report! I think you’re spot on. I wrote this functionality and am working on a fix for some window path issues as well. Can you tell me the output of `pipenv —version`?

**Comment by mccartykim** [comment]
My version is 8.2.6
```PS C:\Users\mccar> pipenv --version
pipenv, version 8.2.6```

**Comment by mccartykim** [comment]
If it helps, I've experienced this error with Python installed through [chocolatey](https://chocolatey.org/packages/python), and I uninstalled chocolatey and installed python through the default 32 bit installer from Python.org, with the box checked to set environmental variables.

Could I manually perhaps add an environmental variable with the path to whatever executives this function wants?  I'd like to work around this if possible.

**Comment by techalchemy** [comment]
Can you provide the output of `pipenv install --verbose` as well as `pipenv --venv`?  This should tell us exactly what is going wrong here.  I suspect it has to do with having a space in your path, which will be fixed whenever #893 is pulled and released (currently waiting on me to write the tests for it).

**Comment by erinxocon** [comment]
Marking this as bug!  Thanks for the work @techalchemy!

**Comment by ofir-shapira-como** [comment]
I've got the same issue, @mccartykim, I wonder if you found some workaround? Thanks

**Comment by Dreamersoul** [comment]
When i tried to run  tests on windows i got the same error and other tests failed because of pew not finding psutil

**Comment by ofir-shapira-como** [comment]
It helped me to uninstall Python, remove all Python user folder, remove all related PATH entries and Re-install.

**Comment by Dreamersoul** [comment]
I hate python on Windows

**Comment by techalchemy** [comment]
@mccartykim can you verify whether this is resolved?

**Comment by mccartykim** [comment]
Hi, yes, I can confirm it works as expected now. I'm not on my Windows machine at the moment, but I can confirm I was able to `pipenv install` and `pipenv shell` after updating my version with no errors. I tried it in just Powershell, however.  If you'd like me to try CMD, I'll try it next time I'm at that machine.

**Comment by techalchemy** [comment]
@mccartykim thanks for the update, I will go ahead and close this out no need to try it out again!
