### ISSUE TITLE
Not able to use a remote url for --requirements

### ISSUE THREAD

**Issue by Yajo** [kennethreitz/pipenv#886]
Take this example:

```
# pipenv install -r https://raw.githubusercontent.com/odoo/odoo/10.0/requirements.txt
Creating a virtualenv for this project…
⠋New python executable in /root/.local/share/virtualenvs/app-4PlAip0Q/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /root/.local/share/virtualenvs/app-4PlAip0Q
Creating a Pipfile for this project…
Requirements file provided! Importing into Pipfile…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1744, in install
    import_requirements(r=project.path_to(requirements), dev=dev)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 234, in import_requirements
    assert os.path.isfile(r)
AssertionError
```

However, `pip install -r https://raw.githubusercontent.com/odoo/odoo/10.0/requirements.txt` works perfectly. I'd expect pipenv's version to work fine too.

**Comment by nateprewitt** [comment]
@Yajo, pipenv does not currently support remote urls. I don't see a particular reason we can't, but it's not a feature that's been added yet. I'll take this as an enhancement for anyone who would like to put a PR for this together.
