### ISSUE TITLE
matplotlib not installable

### ISSUE THREAD

**Issue by goern** [kennethreitz/pipenv#890]
While installing matplotlib there pops an error, I cant identify if it is pipenv or matplotlib...

```
$ uname -a
Darwin tBook 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
[goern@tBook p1]$ pipenv --version
pipenv, version 8.2.6
[goern@tBook p1]$ pipenv install matplotlib
Installing matplotlib…
Requirement already satisfied: matplotlib in /Users/goern/.local/share/virtualenvs/p1-hem_Ny3t/lib/python3.6/site-packages
Requirement already satisfied: cycler>=0.10 in /Users/goern/.local/share/virtualenvs/p1-hem_Ny3t/lib/python3.6/site-packages (from matplotlib)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/goern/.local/share/virtualenvs/p1-hem_Ny3t/lib/python3.6/site-packages (from matplotlib)
Requirement already satisfied: six>=1.10 in /Users/goern/.local/share/virtualenvs/p1-hem_Ny3t/lib/python3.6/site-packages (from matplotlib)
Requirement already satisfied: pytz in /Users/goern/.local/share/virtualenvs/p1-hem_Ny3t/lib/python3.6/site-packages (from matplotlib)
Requirement already satisfied: python-dateutil>=2.0 in /Users/goern/.local/share/virtualenvs/p1-hem_Ny3t/lib/python3.6/site-packages (from matplotlib)
Requirement already satisfied: numpy>=1.7.1 in /Users/goern/.local/share/virtualenvs/p1-hem_Ny3t/lib/python3.6/site-packages (from matplotlib)

Adding matplotlib to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1852, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1083, in do_lock
    pre=pre
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 421, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 199, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 293, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/h0/mm7t_nl57wbbm6hj8xknf49m0000gp/T/tmpalhruqwdbuild/subprocess32/
```

**Comment by vphilippon** [comment]
That's fixed by #833, which is in master but not yet released.

**Comment by goern** [comment]
cool, I can wait a day for the release :)

**Comment by nateprewitt** [comment]
Didn't realize we were waiting on a release from us. I'll try to get something out today.

**Comment by NighTurs** [comment]
@vphilippon continuing discussion from #871, `pipenv lock --verbose --clear` gave me:

```
Creating a virtualenv for this project…
⠋Using base prefix '/usr'
New python executable in /home/nighturs/.local/share/virtualenvs/tmp-9zohn9O5/bin/python3
Also creating executable in /home/nighturs/.local/share/virtualenvs/tmp-9zohn9O5/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/nighturs/.local/share/virtualenvs/tmp-9zohn9O5
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple --trusted-host pypi.python.org

                          ROUND 1                           
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done
Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple --trusted-host pypi.python.org

                          ROUND 1                           
Current constraints:
  matplotlib

Finding the best candidates:
  found candidate matplotlib==2.1.0 (constraint was <any>)

Finding secondary dependencies:
  matplotlib==2.1.0 not in cache, need to check index
  matplotlib==2.1.0         requires cycler>=0.10, matplotlib==2.1.0, numpy>=1.7.1, pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1, python-dateutil>=2.0, pytz, six>=1.10

New dependencies found in this round:
  adding ['cycler', '>=0.10', '[]']
  adding ['matplotlib', '==2.1.0', '[]']
  adding ['numpy', '>=1.7.1', '[]']
  adding ['pyparsing', '!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1', '[]']
  adding ['python-dateutil', '>=2.0', '[]']
  adding ['pytz', '', '[]']
  adding ['six', '>=1.10', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  cycler>=0.10
  matplotlib==2.1.0
  numpy>=1.7.1
  pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  python-dateutil>=2.0
  pytz
  six>=1.10

Finding the best candidates:
  found candidate cycler==0.10.0 (constraint was >=0.10)
  found candidate matplotlib==2.1.0 (constraint was ==2.1.0)
  found candidate numpy==1.13.3 (constraint was >=1.7.1)
  found candidate pyparsing==2.2.0 (constraint was >=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6)
  found candidate python-dateutil==2.6.1 (constraint was >=2.0)
  found candidate pytz==2017.2 (constraint was <any>)
  found candidate six==1.11.0 (constraint was >=1.10)

Finding secondary dependencies:
  matplotlib==2.1.0         requires cycler>=0.10, matplotlib==2.1.0, numpy>=1.7.1, pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1, python-dateutil>=2.0, pytz, six>=1.10
  pytz==2017.2 not in cache, need to check index
  pytz==2017.2              requires pytz==2017.2
  numpy==1.13.3 not in cache, need to check index
  numpy==1.13.3             requires numpy==1.13.3
  cycler==0.10.0 not in cache, need to check index
  cycler==0.10.0            requires cycler==0.10.0, six
  six==1.11.0 not in cache, need to check index
  six==1.11.0               requires six==1.11.0
  pyparsing==2.2.0 not in cache, need to check index
  pyparsing==2.2.0          requires pyparsing==2.2.0
  python-dateutil==2.6.1 not in cache, need to check index
  python-dateutil==2.6.1    requires python-dateutil==2.6.1, six>=1.5

New dependencies found in this round:
  adding ['cycler', '==0.10.0,>=0.10', '[]']
  adding ['numpy', '==1.13.3,>=1.7.1', '[]']
  adding ['pyparsing', '!=2.0.4,!=2.1.2,!=2.1.6,==2.2.0,>=2.0.1', '[]']
  adding ['python-dateutil', '==2.6.1,>=2.0', '[]']
  adding ['pytz', '==2017.2', '[]']
  adding ['six', '==1.11.0,>=1.10,>=1.5', '[]']
Removed dependencies in this round:
  removing ['cycler', '>=0.10', '[]']
  removing ['numpy', '>=1.7.1', '[]']
  removing ['pyparsing', '!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1', '[]']
  removing ['python-dateutil', '>=2.0', '[]']
  removing ['pytz', '', '[]']
  removing ['six', '>=1.10', '[]']
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3                           
Current constraints:
  cycler==0.10.0,>=0.10
  matplotlib==2.1.0
  numpy==1.13.3,>=1.7.1
  pyparsing!=2.0.4,!=2.1.2,!=2.1.6,==2.2.0,>=2.0.1
  python-dateutil==2.6.1,>=2.0
  pytz==2017.2
  six==1.11.0,>=1.10,>=1.5

Finding the best candidates:
  found candidate cycler==0.10.0 (constraint was >=0.10,==0.10.0)
  found candidate matplotlib==2.1.0 (constraint was ==2.1.0)
  found candidate numpy==1.13.3 (constraint was ==1.13.3,>=1.7.1)
  found candidate pyparsing==2.2.0 (constraint was >=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6,==2.2.0)
  found candidate python-dateutil==2.6.1 (constraint was >=2.0,==2.6.1)
  found candidate pytz==2017.2 (constraint was ==2017.2)
  found candidate six==1.11.0 (constraint was >=1.10,==1.11.0,>=1.5)

Finding secondary dependencies:
  six==1.11.0               requires six==1.11.0
  matplotlib==2.1.0         requires cycler>=0.10, matplotlib==2.1.0, numpy>=1.7.1, pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1, python-dateutil>=2.0, pytz, six>=1.10
  numpy==1.13.3             requires numpy==1.13.3
  python-dateutil==2.6.1    requires python-dateutil==2.6.1, six>=1.5
  pyparsing==2.2.0          requires pyparsing==2.2.0
  pytz==2017.2              requires pytz==2017.2
  cycler==0.10.0            requires cycler==0.10.0, six
------------------------------------------------------------
Result of round 3: stable, done
Updated Pipfile.lock (e011c0)!
```
Now it works fine, thanks. So seems like updating to fixed version won't work until you clear cache.

**Comment by nateprewitt** [comment]
8.2.7 was just released to PyPI so this should be resolved and available.

**Comment by goern** [comment]
Affirmative. Thanks!

**Comment by vphilippon** [comment]
@nateprewitt Just in case you skipped it, I noticed there's no tag/release on github for 8.2.7 (which confused me at first).

**Comment by nateprewitt** [comment]
Thanks for catching that @vphilippon. Looks like our release build hiccuped on that step and I didn't notice. Tag is pushed now.

**Comment by AlJohri** [comment]
@nateprewitt I _think_ I'm still running into this one on 8.2.7 as described here: https://github.com/kennethreitz/pipenv/issues/712#issuecomment-338518518

**Comment by AlJohri** [comment]
I take it back - seems to have resolved it self after explicitly running `pipenv install matplotlib`. I was previously just running `pipenv install` with matplotlib listed in the Pipfile. ¯\_(ツ)_/¯ works now!
