### ISSUE TITLE
RuntimeError: No stable configuration

### ISSUE THREAD

**Issue by audiolion** [kennethreitz/pipenv#899]
```python
Adding django-notify-x2==0.5.1 to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "/Users/ryanar/.pyenv/versions/2.7.12/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/cli.py", line 1852, in install
    do_lock(system=system, pre=pre)
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/cli.py", line 1027, in do_lock
    pre=pre
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/utils.py", line 421, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/Users/ryanar/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 97, in resolve
    'This is likely a bug.' % max_rounds)
RuntimeError: No stable configuration of concrete packages could be found for the given constraints after 16 rounds of resolving.
This is likely a bug.
```

I just run the same command again and it works, it looks like it installs fine and then breaks when trying to create the new lockfile, this happens when I install my package within a minute of uploading a new version to `pypi`, not sure if that is related or not.

**Comment by vphilippon** [comment]
@audiolion What's your `pipenv` version?
Also, if you can reproduce (like next time you're about to do a lock after uploading a new package to pypi), could you run `pipenv lock --verbose` and give the verbose output? That will likely help.

**Comment by audiolion** [comment]
Ok ill try that the next time and see what happens, I was on an older version when it was happening, I just did `pipenv --update` so ill see if that solves it

**Comment by erinxocon** [comment]
Closing.  Please comment if the problem persists!
