### ISSUE TITLE
`pipenv install .` in empty dir gives unexpected error

### ISSUE THREAD

**Issue by iandanforth** [kennethreitz/pipenv#911]
##### Describe you environment

        "host-environment-markers": {
            "implementation_name": "cpython",
            "implementation_version": "0",
            "os_name": "posix",
            "platform_machine": "x86_64",
            "platform_python_implementation": "CPython",
            "platform_release": "16.4.0",
            "platform_system": "Darwin",
            "platform_version": "Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64",
            "python_full_version": "2.7.10",
            "python_version": "2.7",
            "sys_platform": "darwin"
        }

1. Pipenv version: 

version 8.2.7

##### Expected result

Either

1. Behaviour equivalent to `pipenv install` with no errors
or
2. An error explaining why specifying the local dir is bad, what is missing, etc.

##### Actual result

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.7', 'console_scripts', 'pipenv')()
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 1793, in install
    c = pip_install(package_name, ignore_hashes=True, allow_global=system, no_deps=False, verbose=verbose, pre=pre)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 1316, in pip_install
    if [x for x in requirements.parse(package_name.split('--hash')[0].split('--trusted-host')[0])][0].vcs:
  File "/Library/Python/2.7/site-packages/pipenv/vendor/requirements/parser.py", line 50, in parse
    yield Requirement.parse(line)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/requirements/requirement.py", line 220, in parse
    return cls.parse_line(line)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/requirements/requirement.py", line 198, in parse_line
    pkg_req = Req.parse(line)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 3042, in parse
    req, = parse_requirements(s)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2990, in parse_requirements
    yield Requirement(line)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2999, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "u'.'"

##### Steps to Reproduce

mkdir foobar
cd foobar
pipenv install .

**Comment by erinxocon** [comment]
I can catch the exception for this but I don't know if we need to add the `.` functionality when `pipenv install` works.

**Comment by iandanforth** [comment]
Catching is fine. The only reason someone might type this is because `pip install .` is a valid command.

**Comment by erinxocon** [comment]
This should be fixed in master, and in the next release!
