### ISSUE TITLE
Cannot install websauna

### ISSUE THREAD

**Issue by Rotonen** [kennethreitz/pipenv#92]
Context: pyenv 1.0.7, macOS 10.12

Steps to reproduce:

```
pyenv install 3.6.0
mkdir sauna-test && cd sauna-test
pyenv local 3.6.0

python -m venv .venv
source .venv/bin/activate

pip install -U setuptools pip wheel
pip list
# pip (9.0.1)
# setuptools (34.0.2)
# wheel (0.29.0)

pip install pipenv==3.1.9
pipenv install

pipenv install websauna
```

Results in the following stacktrace:
```
Traceback (most recent call last):
  File "/Users/joni/temp/test-sauna/.venv/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/joni/temp/test-sauna/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/joni/temp/test-sauna/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/joni/temp/test-sauna/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joni/temp/test-sauna/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/joni/temp/test-sauna/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/joni/temp/test-sauna/.venv/lib/python3.6/site-packages/pipenv/cli.py", line 531, in install
    new_name = proper_case(old_name)
  File "/Users/joni/temp/test-sauna/.venv/lib/python3.6/site-packages/pipenv/cli.py", line 421, in proper_case
    parser.feed(r.content)
  File "/Users/joni/.homebrew/var/pyenv/versions/3.6.0/lib/python3.6/html/parser.py", line 110, in feed
    self.rawdata = self.rawdata + data
TypeError: must be str, not bytes
```

**Comment by nateprewitt** [comment]
Thanks for opening this ticket @Rotonen, this looks like it's a duplicate of #88. It's probably best to consolidate everything to that issue.

**Comment by Rotonen** [comment]
Missed that one, sorry for the noise.

**Comment by kennethreitz** [comment]
this is now fixed!
