### ISSUE TITLE
pip install flask causes TypeError

### ISSUE THREAD

**Issue by nknganda** [kennethreitz/pipenv#95]
***> pip install flask***
Collecting flask
  Using cached Flask-0.12-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask)
Collecting click>=2.0 (from flask)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask)
  Using cached Werkzeug-0.11.15-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from flask)
  Using cached Jinja2-2.9.4-py2.py3-none-any.whl
^COperation cancelled by user
 .venv  newton  ~  Experiments  official-flask-tutorial  $  pipenv install flask
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 531, in install
    new_name = proper_case(old_name)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 424, in proper_case
    return parse_download_fname(collected[-1])[0]
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 218, in parse_download_fname
    name = r['name']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by nateprewitt** [comment]
Thanks for opening this ticket @nknganda. The error you're encountering is because `proper_case` isn't able to locate the package and returns a value of None. `parse_download_fname` is then failing because the value isn't the expected dictionary.  Could you provide the version of `pipenv` you're using?

**Comment by nknganda** [comment]
Thanks for the response @nateprewitt.

 pipenv, version 3.1.9

**Comment by kennethreitz** [comment]
#97 fixes this
