### ISSUE TITLE
pipenv install mkdocs --system failing inside Dockerfile

### ISSUE THREAD

**Issue by ryan-blunden** [kennethreitz/pipenv#955]
Failing to install mkdocs when passing `--system` flag. Works without `--system flag`.

**NOTE!**: This does work if you create a symlink from `/usr/local/bin/python` to `/bin/python` before running the `pipenv install mkdocs --system` command.

##### Describe you environment

1. OSX: 10.12.6 (16G29)
1. Docker version: 17.09.0-ce, build afdb6d4
1. Python version: Python 3.6.3
1. Pipenv version: pipenv, version 8.2.7

##### Expected result

Docker image would be build successfully.

##### Actual result

Docker image failed to build.

##### Steps to replicate

When using a `Dockerfile` with the contents:

```
FROM python:3.6-slim

WORKDIR /usr/src/app

RUN pip install pip --upgrade && pip install pipenv

# Fails
RUN pipenv install mkdocs --system
```
And running `docker image build -t pipenv:latest .`

```
Step 1/5 : FROM python:3.6-slim
 ---> 45454af642e0
Step 2/5 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 994c7ad276b3
Step 3/5 : RUN pip install pip --upgrade && pip install pipenv
 ---> Using cache
 ---> 57dd47271ba9
Step 4/5 : RUN pip install setuptools --upgrade
 ---> Running in 525c7bb9f3e7
Collecting setuptools
  Downloading setuptools-36.6.0-py2.py3-none-any.whl (481kB)
Installing collected packages: setuptools
  Found existing installation: setuptools 36.5.0
    Uninstalling setuptools-36.5.0:
      Successfully uninstalled setuptools-36.5.0
Successfully installed setuptools-36.6.0
 ---> 0fd7f53cd65c
Removing intermediate container 525c7bb9f3e7
Step 5/5 : RUN pipenv install mkdocs --system
 ---> Running in b591e1587884
Creating a Pipfile for this project…
Installing mkdocs…
Collecting mkdocs
  Downloading mkdocs-0.17.0-py2.py3-none-any.whl (1.2MB)
Collecting Markdown>=2.3.1 (from mkdocs)
  Downloading Markdown-2.6.9.tar.gz (271kB)
Collecting tornado>=4.1 (from mkdocs)
  Downloading tornado-4.5.2.tar.gz (483kB)
Collecting livereload>=2.5.1 (from mkdocs)
  Downloading livereload-2.5.1.tar.gz
Collecting Jinja2>=2.7.1 (from mkdocs)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
Collecting click>=3.3 (from mkdocs)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting PyYAML>=3.10 (from mkdocs)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting six (from livereload>=2.5.1->mkdocs)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.7.1->mkdocs)
  Downloading MarkupSafe-1.0.tar.gz
Building wheels for collected packages: Markdown, tornado, livereload, PyYAML, MarkupSafe
  Running setup.py bdist_wheel for Markdown: started
  Running setup.py bdist_wheel for Markdown: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/bf/46/10/c93e17ae86ae3b3a919c7b39dad3b5ccf09aeb066419e5c1e5
  Running setup.py bdist_wheel for tornado: started
  Running setup.py bdist_wheel for tornado: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/b3/47/3a/96e12476829cb196adabc879fedb72f1bb2c8613b6961e78e7
  Running setup.py bdist_wheel for livereload: started
  Running setup.py bdist_wheel for livereload: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/71/95/bf/6ccaa70b36701dd3fa337296d7ec6614bf14f51d58bc3a4a7a
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for MarkupSafe: started
  Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
Successfully built Markdown tornado livereload PyYAML MarkupSafe
Installing collected packages: Markdown, tornado, six, livereload, MarkupSafe, Jinja2, click, PyYAML, mkdocs
Successfully installed Jinja2-2.9.6 Markdown-2.6.9 MarkupSafe-1.0 PyYAML-3.12 click-6.7 livereload-2.5.1 mkdocs-0.17.0 six-1.11.0 tornado-4.5.2

Adding mkdocs to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
CRITICAL:pip.utils:Error [Errno 2] No such file or directory: '/bin/python': '/bin/python' while executing command python setup.py egg_info
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1847, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1082, in do_lock
    pre=pre
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 452, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 667, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/bin/python': '/bin/python'
The command '/bin/sh -c pipenv install mkdocs --system' returned a non-zero code: 1
```

**Comment by erinxocon** [comment]
I think this is related to another bug.  I'll have to look it up.  Let me try to reproduce.

**Comment by erinxocon** [comment]
Can you try with the following dockerfile?

```dockerfile
FROM python:3.6-slim
WORKDIR /usr/src/app
RUN set -ex && pip install pipenv --upgrade
ONBUILD RUN set -ex && pipenv install --deploy --system mkdocs
```
I was able to pull from our example dockerfile to get this to work.
