### ISSUE TITLE
ModuleNotFoundError when running installed packages

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#98]
I am seeing this issue with lots of packages that have a command-line entry point (at least `pytest` and `honcho`):

```
$ pipenv --version
pipenv, version 3.2.0

$ pipenv install honcho
Installing honcho...
Collecting honcho
  Using cached honcho-0.7.1-py2.py3-none-any.whl
Installing collected packages: honcho
Successfully installed honcho-0.7.1

Adding honcho to Pipfile's [packages]...

$ pipenv run honcho
Traceback (most recent call last):
  File "<root>/.venv/bin/honcho", line 7, in <module>
    from honcho.command import main
ModuleNotFoundError: No module named 'honcho'
```

**Comment by nateprewitt** [comment]
Hmm, I'm actually unable to reproduce this on macOS 10.12.2 with a standard bash shell. @jacebrowning What version of python and shell are you using? Could you also provide what `pipenv run pip list` returns for me? Thanks!

**Comment by jacebrowning** [comment]
I'm running ZSH and Python 3.6.0 on macOS 10.12.2.

```
$ pipenv run pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.0)
honcho (0.7.1)
httpie (0.9.9)
packaging (16.8)
pip (9.0.1)
py (1.4.32)
Pygments (2.2.0)
pyparsing (2.1.10)
pytest (3.0.6)
requests (2.13.0)
setuptools (34.0.2)
six (1.10.0)
wheel (0.29.0)
```

**Comment by nateprewitt** [comment]
So I've tried to recreate this with the same dependencies both locally and on Travis without success. I think there may either be a conflict on your path that's causing problems, or this may be something specific to ZSH.

Have you tried running `pipenv uninstall` to purge your pipenv and starting over? Are you getting an identical `ModuleNotFoundError` for pytest?

Without a consistent repro, I'm not sure much more can be done to debug this right now.

**Comment by jacebrowning** [comment]
Yes, I get the same error with `pytest`:

```
$ pipenv uninstall
No package provided, un-installing all packages.
Found 10 installed package(s), purging...
Uninstalling appdirs-1.4.0:
  Successfully uninstalled appdirs-1.4.0
Uninstalling honcho-0.7.1:
  Successfully uninstalled honcho-0.7.1
Uninstalling httpie-0.9.9:
  Successfully uninstalled httpie-0.9.9
Uninstalling packaging-16.8:
  Successfully uninstalled packaging-16.8
Uninstalling py-1.4.32:
  Successfully uninstalled py-1.4.32
Uninstalling Pygments-2.2.0:
  Successfully uninstalled Pygments-2.2.0
Uninstalling pyparsing-2.1.10:
  Successfully uninstalled pyparsing-2.1.10
Uninstalling pytest-3.0.6:
  Successfully uninstalled pytest-3.0.6
Uninstalling requests-2.13.0:
  Successfully uninstalled requests-2.13.0
Uninstalling six-1.10.0:
  Successfully uninstalled six-1.10.0

Environment now purged and fresh!

$ pipenv install pytest
Installing pytest...
Collecting pytest
  Using cached pytest-3.0.6-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest)
  Using cached py-1.4.32-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.venv/lib/python3.6/site-packages (from pytest)
Collecting appdirs>=1.4.0 (from setuptools->pytest)
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting six>=1.10.0 (from setuptools->pytest)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools->pytest)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools->pytest)
  Using cached pyparsing-2.1.10-py2.py3-none-any.whl
Installing collected packages: py, pytest, appdirs, six, pyparsing, packaging
Successfully installed appdirs-1.4.0 packaging-16.8 py-1.4.32 pyparsing-2.1.10 pytest-3.0.6 six-1.10.0

Adding pytest to Pipfile's [packages]...

$ pipenv run pytest
Traceback (most recent call last):
  File "<root>/.venv/bin/pytest", line 7, in <module>
    from pytest import main
ModuleNotFoundError: No module named 'pytest'
```

**Comment by jacebrowning** [comment]
Weirdly, `$ pipenv run python -m pytest` does work.

**Comment by nateprewitt** [comment]
Could you tell me what `$ pipenv run python --version` and `$ ls -l .venv/bin/python` return respectively? The only thing I can think of at this point is there's possibly something going on with having multiple python versions accessible via pyenv.

**Comment by jacebrowning** [comment]
```
$ pipenv run python --version
Python 3.6.0

$ ls -l .venv/bin/python
lrwxr-xr-x  1 Browning  staff  9 Jan 25 16:50 .venv/bin/python -> python3.6
```

**Comment by nateprewitt** [comment]
Aright, I think I've gotten a bit closer. I was able to repro this by deleting `.venv/lib/python3.6/site-packages/honcho` but leaving `.venv/lib/python3.6/site-packages/honcho-0.7.1.dist-info/` in place. When you run `pipenv install honcho` it locates the dist-info and assumes the package is already there. This seems to be functionality of `pip` itself though.

Can you check the contents of your `.venv/lib/python3.6/site-packages` for me @jacebrowning. I'm going to recommend deleting your current .venv directory and creating a new one with `pipenv --three`? See if you are able to reproduce it again after that.

**Comment by jacebrowning** [comment]
@nateprewitt Sorry, no luck there:

```
$ pipenv --version
pipenv, version 3.2.2

$ rm -rf .venv

$ pipenv --three
Creating a virtualenv for this project...
Running virtualenv with interpreter /Users/Browning/.pyenv/versions/3.6.0/bin/python3
Using base prefix '/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6'
New python executable in /Users/Browning/Programs/myproject/.venv/bin/python3
Also creating executable in /Users/Browning/Programs/myproject/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/Browning/Programs/myproject/.venv

$ pipenv install honcho
Installing honcho...
Collecting honcho
  Using cached honcho-0.7.1-py2.py3-none-any.whl
Installing collected packages: honcho
Successfully installed honcho-0.7.1

Adding honcho to Pipfile's [packages]...

$ pipenv run honcho
Traceback (most recent call last):
  File "/Users/Browning/Programs/myproject/.venv/bin/honcho", line 7, in <module>
    from honcho.command import main
ModuleNotFoundError: No module named 'honcho'

$ l .venv/lib/python3.6/site-packages
total 576
drwxr-xr-x  21 Browning  staff   714B Jan 25 23:33 .
drwxr-xr-x  58 Browning  staff   1.9K Jan 25 23:33 ..
drwxr-xr-x   6 Browning  staff   204B Jan 25 23:33 __pycache__
drwxr-xr-x   9 Browning  staff   306B Jan 25 23:33 appdirs-1.4.0.dist-info
-rw-r--r--   1 Browning  staff    22K Jan 25 23:33 appdirs.py
-rw-r--r--   1 Browning  staff   126B Jan 25 23:33 easy_install.py
drwxr-xr-x  12 Browning  staff   408B Jan 25 23:33 honcho
drwxr-xr-x  11 Browning  staff   374B Jan 25 23:33 honcho-0.7.1.dist-info
drwxr-xr-x  12 Browning  staff   408B Jan 25 23:33 packaging
drwxr-xr-x   9 Browning  staff   306B Jan 25 23:33 packaging-16.8.dist-info
drwxr-xr-x  23 Browning  staff   782B Jan 25 23:33 pip
drwxr-xr-x  10 Browning  staff   340B Jan 25 23:33 pip-9.0.1.dist-info
drwxr-xr-x   4 Browning  staff   136B Jan 25 23:33 pkg_resources
drwxr-xr-x   9 Browning  staff   306B Jan 25 23:33 pyparsing-2.1.10.dist-info
-rw-r--r--   1 Browning  staff   224K Jan 25 23:33 pyparsing.py
drwxr-xr-x  36 Browning  staff   1.2K Jan 25 23:33 setuptools
drwxr-xr-x  12 Browning  staff   408B Jan 25 23:33 setuptools-34.0.2.dist-info
drwxr-xr-x   9 Browning  staff   306B Jan 25 23:33 six-1.10.0.dist-info
-rw-r--r--   1 Browning  staff    29K Jan 25 23:33 six.py
drwxr-xr-x  20 Browning  staff   680B Jan 25 23:33 wheel
drwxr-xr-x  11 Browning  staff   374B Jan 25 23:33 wheel-0.29.0.dist-info
```

**Comment by jacebrowning** [comment]
I may have stumbled onto something. The scripts in `.venv/bin` differ between `pipenv` and `virtualenv` directly.

Using `pipenv`:

```
$ cat .venv/bin/honcho
#!/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from honcho.command import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())


$ .venv/bin/honcho --version
Traceback (most recent call last):
  File ".venv/bin/honcho", line 7, in <module>
    from honcho.command import main
ModuleNotFoundError: No module named 'honcho'
```

Using `virtualenv` directly:

```
$ virtualenv --version
15.1.0

$ virtualenv .venv
Using base prefix '/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6'
New python executable in /Users/Browning/Programs/myproject/.venv/bin/python
Installing setuptools, pip, wheel...done.

$ .venv/bin/pip install honcho
Collecting honcho
  Using cached honcho-0.7.1-py2.py3-none-any.whl
Installing collected packages: honcho
Successfully installed honcho-0.7.1

$ cat .venv/bin/honcho
#!/Users/Browning/Programs/myproject/.venv/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from honcho.command import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

$ .venv/bin/honcho --version
honcho 0.7.1
```

So, the difference is in the hashbang line. Shouldn't `pipenv` create scripts with a hashbang that points to the Python binary in the virtual environment?

**Comment by nateprewitt** [comment]
@jacebrowning It definitely should, the ones being generated in your `pipenv` versions aren't correct. As to *why* that's happening, I'm not yet sure, but I think we're much closer.

When you run `$ python3`, which version does it boot into and where does the symbolic link point?

pipenv is running this exact command to create it's virtual environment. Which shebang do you get when running it in your terminal?
`$ virtualenv /Users/Browning/Programs/myproject/.venv --prompt=(myproject) -p python3`

**Comment by jacebrowning** [comment]
I ran those commands, but <details>
<summary>not much to see.</summary>

```
$ python3
Python 3.6.0 (default, Dec 27 2016, 00:13:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

$ which python3
/Users/Browning/.pyenv/shims/python3

$ cat `which python3`
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/Users/Browning/.pyenv"
exec "/usr/local/Cellar/pyenv/1.0.6/libexec/pyenv" exec "$program" "$@"

$ virtualenv /Users/Browning/Programs/myproject/.venv --prompt="(myproject)" -p python3
Running virtualenv with interpreter /Users/Browning/.pyenv/versions/3.6.0/bin/python3
Using base prefix '/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6'
New python executable in /Users/Browning/Programs/myproject/.venv/bin/python3
Also creating executable in /Users/Browning/Programs/myproject/.venv/bin/python
Installing setuptools, pip, wheel...done.

$ cat myproject/.venv/bin/wheel
#!/Users/Browning/Programs/myproject/.venv/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from wheel.tool import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

$ myproject/.venv/bin/pip install honcho
Collecting honcho
  Using cached honcho-0.7.1-py2.py3-none-any.whl
Installing collected packages: honcho
Successfully installed honcho-0.7.1

$ cat myproject/.venv/bin/honcho
#!/Users/Browning/Programs/myproject/.venv/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from honcho.command import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

</details>

-----

However, I have now isolated the problem to a difference between `pipenv install` and `pip install`. Using `pipenv install`:

```
$ pipenv install honcho
Installing honcho...
Collecting honcho
  Using cached honcho-0.7.1-py2.py3-none-any.whl
Installing collected packages: honcho
Successfully installed honcho-0.7.1

Adding honcho to Pipfile's [packages]...

$ cat .venv/bin/honcho
#!/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from honcho.command import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Using `pip install` in the same virtual environment after `pipenv uninstall honcho`:

```
$ .venv/bin/pip install honcho
Collecting honcho
  Using cached honcho-0.7.1-py2.py3-none-any.whl
Installing collected packages: honcho
Successfully installed honcho-0.7.1

$ cat .venv/bin/honcho
#!/Users/Browning/Programs/myproject/.venv/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from honcho.command import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by jacebrowning** [comment]
I found a related issue (https://github.com/pypa/setuptools/issues/769) and the [culprit line](https://github.com/pypa/setuptools/blob/ac325f34b73c534fd19204400afa598bf63ea301/setuptools/command/easy_install.py#L1940) in `setuptools`.

I don't know the purpose of `__PYVENV_LAUNCHER__` nor why it is getting set when I run `pipenv`.

There is more discussion here: https://bugs.python.org/issue22490

**Comment by fny** [comment]
I'm having this exact same issue with a new package I'm working on... https://github.com/fny/thecurator/tree/pipenv-failure

The jsonschema package can't be found in the tests even though it's clearly installed in the virtualenv.

```
(thecurator-9LuGzVpd) bash-4.4 $ pipenv run pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
jsonschema (2.6.0)
pip (9.0.3)
pyaml (17.12.1)
PyYAML (3.12)
setuptools (39.0.1)
SQLAlchemy (1.2.5)
wheel (0.30.0)

(thecurator-9LuGzVpd) bash-4.4$ pipenv run pytest tests
================================================================================ test session starts ================================================================================
platform darwin -- Python 3.6.4, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /Users/faraz/Workspace/thecurator, inifile:
collected 5 items / 1 errors

====================================================================================== ERRORS =======================================================================================
______________________________________________________________________ ERROR collecting tests/test_curation.py ______________________________________________________________________
ImportError while importing test module '/Users/faraz/Workspace/thecurator/tests/test_curation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_curation.py:2: in <module>
    from thecurator.private import IS_PYPY, pypy_incompatible
thecurator/__init__.py:4: in <module>
    from .private.table_description import Registry
thecurator/private/table_description.py:6: in <module>
    import jsonschema
E   ModuleNotFoundError: No module named 'jsonschema'
```

**Comment by techalchemy** [comment]
@fny `pipenv run python -m pytest tests`, also you don’t need to be inside the virtualenv to do this

**Comment by hvgab** [comment]
I have what seems to be the same problem.
I'm on windows 10 with python 3.6.
some packages won't run with `pipenv run py *something*`
but 
```cmd
pipenv shell
py *something*
```  
works just fine.
example i'm sitting with now is `toml`

**Comment by techalchemy** [comment]
`py` is the python finder. It uses special methods spelled out in pep 514 to search for python executables. Since `pipenv run` doesn’t alter your environment as thoroughly as `pipenv shell`, the pep-514 style finder will not know where to search for libraries besides the normal places. That is to say, `pipenv run` simply puts `virtualenv\Scripts` at the head of your `PATH` environment variable. The windows finder doesn’t even look there to execute things, so it will never be affected by this. 

With pipenv, you’ve already set up a virtual environment with a python executable in it. So you shouldn’t use the finder, you should just use `pipenv run python <script>`

````

**Comment by volkanunsal** [comment]
I have the same problem on Mac OS X. Python 3.7.3.

**Comment by volkanunsal** [comment]
I figured out that I was not installing the packages in `dev-packages` block. Using `pipenv install -d` solved the problem.
